### ISSUE TITLE
Backup exits with AttributeError

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida-core#1675]
When running start_backup.py that was generated by following the instructions at 
http://aiida-core.readthedocs.io/en/stable/backup/index.html

an exception occurs
```
(aiidapy) aiida@ubuntu-aiida-vm1:~/.aiida/backup$ ./start_backup.py
Traceback (most recent call last):
  File "/home/aiida/aiidapy/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/verdilib.py", line 1056, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/verdilib.py", line 1041, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/verdilib.py", line 886, in run
    exec (f, globals_dict)
  File "./start_backup.py", line 13, in <module>
    backup_inst.run()
  File "/home/aiida/aiida-code/aiida_core/aiida/common/additions/backup_script/backup_base.py", line 450, in run
    self._read_backup_info_from_file(self._backup_info_filepath)
  File "/home/aiida/aiida-code/aiida_core/aiida/common/additions/backup_script/backup_base.py", line 104, in _read_backup_info_from_file
    self._read_backup_info_from_dict(backup_variables)
  File "/home/aiida/aiida-code/aiida_core/aiida/common/additions/backup_script/backup_base.py", line 125, in _read_backup_info_from_dict
    query_node_res = self._query_first_node()
  File "/home/aiida/aiida-code/aiida_core/aiida/common/additions/backup_script/backup_sqlalchemy.py", line 47, in _query_first_node
    res = aiida.backends.sqlalchemy.get_scoped_session().query(
AttributeError: 'NoneType' object has no attribute 'query'
```

Moreover, the default profile is Django and the exception is at SQLA.
This was tested with the current deveop code (commit e2a8269)

**Comment by DanielMarchand** [comment]
Does the rsync end up taking a long time? Do you have a sense of how many files are in your repository (I suspect its probably the same or greater than mine, in which case I can probably do this as well).

As for the database dump, do you have the command for this? Is there a separate dump for each profile?

**Comment by ltalirz** [comment]
@szoupanos Can you please comment on whether this is relevant to 0.12.x (as suggested by the milestone) or just to 1.0.0.

If it is not relevant to 0.12.x, please change the milestone.
If it is relevant to 0.12.x, please move it to the 0.12.4 milestone I just created.

**Comment by sphuber** [comment]
The old backup functionality will be completely removed and replaced with the new repository implementation which is slated for v2.0.0
