### ISSUE TITLE
calculation gets stuck in SUBMITTING state if no default queue is available

### ISSUE THREAD

**Issue by PhilippRue** [aiidateam/aiida-core#2226]
If a calculation is submitted without setting a queue name but there are no default queues specified the calculation gets stuck in the SUBMITTED state.

Output of `verdi calculation list`:
```
  PK  Creation    State           Type                Computer        Job state
----  ----------  --------------  ------------------  --------------  -----------------
 216  11m ago     Waiting | None  kkr.voro            iff003_via_iff  SUBMITTING | None
```

Output of `verdi calculation logshow`:
```
*** 216 [Test voronoi]: SUBMITTING
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 5 LOG MESSAGES:
+-> ERROR at 2018-11-21 09:32:21.720250+00:00
 | iteration 1 of do_submit excepted, retrying after 20 seconds
+-> ERROR at 2018-11-21 09:32:48.242780+00:00
 | iteration 2 of do_submit excepted, retrying after 40 seconds
+-> ERROR at 2018-11-21 09:33:34.459750+00:00
 | iteration 3 of do_submit excepted, retrying after 80 seconds
+-> ERROR at 2018-11-21 09:35:00.718076+00:00
 | iteration 4 of do_submit excepted, retrying after 160 seconds
+-> WARNING at 2018-11-21 09:37:47.107576+00:00
 | maximum attempts 5 of calling do_submit, exceeded
```

The scheduler to which I tried to submit the calculation is `torque` and the corresponding log message of the deamon is:
```
11/21/2018 10:33:33 AM <1671> aiida.work.job_processes: [INFO] submitting calculation<216>
11/21/2018 10:33:34 AM <1671> aiida.scheduler.plugins.pbsbaseclasses: [INFO] submitting with: qsub '_aiidasubmit.sh'
11/21/2018 10:33:34 AM <1671> aiida.scheduler.plugins.pbsbaseclasses: [ERROR] Error in _parse_submit_output: retval=189; stdout=; stderr=qsub: No default queue specified MSG=cannot locate queue

11/21/2018 10:33:34 AM <1671> aiida.work.transports: [ERROR] Exception whilst using transport:
Traceback (most recent call last):
  File "/Users/ruess/sourcecodes/aiida/aiida_core/aiida/work/transports.py", line 106, in request_transport
    yield transport_request.future
  File "/Users/ruess/sourcecodes/aiida/aiida_core/aiida/work/job_processes.py", line 138, in do_submit
    raise Return(execmanager.submit_calculation(node, transport, calc_info, script_filename))
  File "/Users/ruess/sourcecodes/aiida/aiida_core/aiida/daemon/execmanager.py", line 237, in submit_calculation
    job_id = scheduler.submit_from_script(workdir, script_filename)
  File "/Users/ruess/sourcecodes/aiida/aiida_core/aiida/scheduler/__init__.py", line 415, in submit_from_script
    return self._parse_submit_output(retval, stdout, stderr)
  File "/Users/ruess/sourcecodes/aiida/aiida_core/aiida/scheduler/plugins/pbsbaseclasses.py", line 714, in _parse_submit_output
    "stdout={}\nstderr={}".format(retval, stdout, stderr))
SchedulerError: Error during submission, retval=189
stdout=
stderr=qsub: No default queue specified MSG=cannot locate queue
``` 

Maybe the calculation can be terminated directly since none of the retries of the deamon to submit the calculation will be successful.

**Comment by sphuber** [comment]
The problem with this is that it will be difficult to distinguish errors in the submission that are recoverable. As far as AiiDA is concerned, this error looks exactly the same as where the submission fails due to the scheduler being temporarily unavailable (in which case a restart will make sense). They are both just raised as exceptions. Now we could try to add some parsing of the exception and determine those that are non-recoverable, but that will be difficult especially also since they are scheduler plugin specific, as in this example. I am therefore going to close this issue.
