### ISSUE TITLE
import of aiida export file from django backend fails in sqlalchemy 

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2385]
On aiida-core release_v0.12.3, the import of [this export file](https://www.dropbox.com/s/3f4895jq9eskqw3/export.aiida?dl=1) fails in sqlalchemy with

```
DETAIL:  Token "NaN" is invalid.
CONTEXT:  JSON data, line 1: ..._energy_average": 0.0, "temperature_average": NaN...
 [SQL: 'INSERT INTO db_dbnode (uuid, type, label, description, ctime, mtime, nodeversion, public, attributes, extras, dbcomputer_id, user_id) VALUES (%(uuid)s, %(type)s, %(label)s, %(description)s, %(ctime)s, %(mtime)s, %(nodeversion)s, %(public)s, %(attributes)s, %(extras)s, %(dbcomputer_id)s, %(user_id)s) RETURNING db_dbnode.id'] [parameters: {'user_id': 3, 'ctime': datetime.datetime(2019, 1, 11, 11, 51, 56, 534518, tzinfo=<UTC>), 'description': u'', 'label': u'', 'extras': '{}', 'mtime': datetime.datetime(2019, 1, 11, 11, 51, 56, 537577, tzinfo=<UTC>), 'attributes': '{"total_energy_dev": 2.52629, "host_ads_coulomb_energy_average": 0.0, "temperature_average": NaN, "framework_density_units": "kg/m^3", "cell_volume_units": "A^3", "ads_ads_coulomb_energy_unit": "kJ/mol", "enthalpy_of_adsorption_units": "K", "ads_ads_vdw_energy_dev": 0.0158061636474754, "host_ads_vdw_energy_average": -0.0877961516455398, "pressure_average": 0.0, "host_ads_total_energy_dev": 0.0176859477631525, "adsorbate_density_dev": 0.10199, "enthalpy_of_adsorption_dev": 1.161817, "ads_ads_total_energy_average": -0.315361667962928, "ads_ads_total_energy_dev": 0.0158061303896158, "adsorbate_density_average": 3.7248, "ads_ads_vdw_energy_average": -0.315361692906323, "framework_heat_capacity_dev": 0.10089, "host_ads_total_energy_average": -0.0877961765889345, "ads_ads_coulomb_energy_dev": 0.0, "total_energy_average": -48.48873, "pressure_units": "Pa", "total_energy_units": "K", "exceeded_walltime": false, "host_ads_coulomb_energy_dev": 0.0, "cell_volume_dev": 0.00098, "host_ads_total_energy_unit": "kJ/mol", "adsorbate_density_units": "kg/m^3", "host_ads_vdw_energy_dev": 0.0176859061908279, "enthalpy_of_adsorption_average": -314.23365, "host_ads_coulomb_energy_unit": "kJ/mol", "temperature_dev": NaN, "framework_heat_capacity_units": "J/mol/K", "cell_volume_average": 37717.30829, "host_ads_vdw_energy_unit": "kJ/mol", "framework_density": "0.355004051315", "ads_ads_total_energy_unit": "kJ/mol", "ads_ads_coulomb_energy_average": 0.0, "framework_heat_capacity_average": 0.7042, "ads_ads_vdw_energy_unit": "kJ/mol", "temperature_units": "K", "pressure_dev": 0.0}', 'dbcomputer_id': None, 'nodeversion': 1, 'type': u'data.parameter.ParameterData.', 'public': False, 'uuid': u'0202623d-c941-48fe-91bf-170623b46dc8'}]
...
```

It seems, "NaN" is allowed as a value of attributes in the django backend and exported, but then not allowed when importing to sqlalchemy.

**Comment by ltalirz** [comment]
@szoupanos Could you please at least comment on how we should fix this?
And whether this is an issue in 1.0 as well?

I can then look into fixing this myself

**Comment by szoupanos** [comment]
@ltalirz Let me have a short look at it and I will let you know

**Comment by ltalirz** [comment]
Thanks!

**Comment by szoupanos** [comment]
You are welcome.

I checked out v1.0.0b3 and it seems that the export file can not be migrated to version 0.4 (the provided export file is at version 0.3)
```

(aiidapy2) aiida@ubuntu_vm1_new:~/issue_2385$ verdi -p dj1 import export.aiida 
Info: importing archive export.aiida
READING DATA AND METADATA...
EXTRACTING NODE DATA...
Warning: Export file version is 0.3, can import only version 0.4
Do you want to try and migrate export.aiida to the newest export file version?
Note: This will not change your current file. [Y/n]: 
Info: migrating archive export.aiida
READING DATA AND METADATA...
EXTRACTING NODE DATA...
Critical: cannot migrate from version 0.3
```

So this should be an independent problem - the migration of the provided export file to v0.4

I will have a look what happens with 0.12

**Comment by szoupanos** [comment]
So, if I understand well, you refer to the following exception

```
(aiidapy2) aiida@ubuntu_vm1_new:~/issue_2385$ verdi -p sqla1 import export.aiida
**** Importing file export.aiida
READING DATA AND METADATA...
EXTRACTING NODE DATA...
NEW aiida.backends.djsite.db.models.DbUser: aliaksandr.yakutovich@epfl.ch (2->3)
NEW aiida.backends.djsite.db.models.DbComputer: 5e115e65-bc72-49fa-af16-420781cea749 (1->1)
STORING NEW NODE FILES & ATTRIBUTES...
Rolling back
Traceback (most recent call last):
  File "/home/aiida/aiida-code/aiida_core/aiida/cmdline/commands/importfile.py", line 87, in run
    import_data(filename)
  File "/home/aiida/aiida-code/aiida_core/aiida/orm/importexport.py", line 316, in import_data
    silent=silent)
  File "/home/aiida/aiida-code/aiida_core/aiida/orm/importexport.py", line 1265, in import_data_sqla
    session.flush()
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2112, in flush
    self._flush(objects)
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2230, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2194, in _flush
    flush_context.execute()
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 178, in save_obj
    mapper, table, insert)
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 804, in _emit_insert_statements
    execute(statement, params)
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/aiida/aiidapy2/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DataError: (psycopg2.DataError) invalid input syntax for type json
LINE 1: ...11T11:51:56.537577+00:00'::timestamptz, 1, false, '{"total_e...
                                                             ^
DETAIL:  Token "NaN" is invalid.
CONTEXT:  JSON data, line 1: ..._energy_average": 0.0, "temperature_average": NaN...
 [SQL: 'INSERT INTO db_dbnode (uuid, type, label, description, ctime, mtime, nodeversion, public, attributes, extras, dbcomputer_id, user_id) VALUES (%(uuid)s, %(type)s, %(label)s, %(description)s, %(ctime)s, %(mtime)s, %(nodeversion)s, %(public)s, %(attributes)s, %(extras)s, %(dbcomputer_id)s, %(user_id)s) RETURNING db_dbnode.id'] [parameters: {'user_id': 3, 'uuid': u'0202623d-c941-48fe-91bf-170623b46dc8', 'description': u'', 'label': u'', 'extras': '{}', 'mtime': datetime.datetime(2019, 1, 11, 11, 51, 56, 537577, tzinfo=<UTC>), 'attributes': '{"total_energy_dev": 2.52629, "host_ads_coulomb_energy_average": 0.0, "temperature_average": NaN, "framework_density_units": "kg/m^3", "cell_volume_units": "A^3", "ads_ads_coulomb_energy_unit": "kJ/mol", "enthalpy_of_adsorption_units": "K", "ads_ads_vdw_energy_dev": 0.0158061636474754, "host_ads_vdw_energy_average": -0.0877961516455398, "pressure_average": 0.0, "host_ads_total_energy_dev": 0.0176859477631525, "adsorbate_density_dev": 0.10199, "enthalpy_of_adsorption_dev": 1.161817, "ads_ads_total_energy_average": -0.315361667962928, "ads_ads_total_energy_dev": 0.0158061303896158, "adsorbate_density_average": 3.7248, "ads_ads_vdw_energy_average": -0.315361692906323, "framework_heat_capacity_dev": 0.10089, "host_ads_total_energy_average": -0.0877961765889345, "ads_ads_coulomb_energy_dev": 0.0, "total_energy_average": -48.48873, "pressure_units": "Pa", "total_energy_units": "K", "exceeded_walltime": false, "host_ads_coulomb_energy_dev": 0.0, "cell_volume_dev": 0.00098, "host_ads_total_energy_unit": "kJ/mol", "adsorbate_density_units": "kg/m^3", "host_ads_vdw_energy_dev": 0.0176859061908279, "enthalpy_of_adsorption_average": -314.23365, "host_ads_coulomb_energy_unit": "kJ/mol", "temperature_dev": NaN, "framework_heat_capacity_units": "J/mol/K", "cell_volume_average": 37717.30829, "host_ads_vdw_energy_unit": "kJ/mol", "framework_density": "0.355004051315", "ads_ads_total_energy_unit": "kJ/mol", "ads_ads_coulomb_energy_average": 0.0, "framework_heat_capacity_average": 0.7042, "ads_ads_vdw_energy_unit": "kJ/mol", "temperature_units": "K", "pressure_dev": 0.0}', 'dbcomputer_id': None, 'nodeversion': 1, 'type': u'data.parameter.ParameterData.', 'public': False, 'ctime': datetime.datetime(2019, 1, 11, 11, 51, 56, 534518, tzinfo=<UTC>)}]

> There has been an exception during the import of file
> export.aiida
> Do you want to continue (c) or stop (S, default)? 
```
The obvious remark is that NaN values can not be stored in the database or the database adapter (psycopg2) complains.

According to https://www.json.org/ a JSON value can be null but I don't see NaN to be mentioned anywhere. So maybe NaN is not a valid JSON value. This is interesting because when I do a json.dumps of the problematic node (in the django backend where everything was imported correctly), I get a JSON with NaN

```
In [8]: json.dumps(n.get_attrs())
Out[8]: '{"total_energy_dev": 2.52629, "host_ads_coulomb_energy_average": 0.0, "temperature_average": NaN, "framework_density_units": "kg/m^3", "cell_volume_units": "A^3", "ads_ads_coulomb_energy_unit": "kJ/mol", "enthalpy_of_adsorption_units": "K", "ads_ads_vdw_energy_dev": 0.0158061636474754, "host_ads_vdw_energy_average": -0.0877961516455398, "pressure_average": 0.0, "host_ads_total_energy_dev": 0.0176859477631525, "adsorbate_density_dev": 0.10199, "enthalpy_of_adsorption_dev": 1.161817, "ads_ads_total_energy_average": -0.315361667962928, "ads_ads_total_energy_dev": 0.0158061303896158, "adsorbate_density_average": 3.7248, "ads_ads_vdw_energy_average": -0.315361692906323, "framework_heat_capacity_dev": 0.10089, "host_ads_total_energy_average": -0.0877961765889345, "ads_ads_coulomb_energy_dev": 0.0, "total_energy_average": -48.48873, "pressure_units": "Pa", "total_energy_units": "K", "exceeded_walltime": false, "host_ads_coulomb_energy_dev": 0.0, "cell_volume_dev": 0.00098, "host_ads_total_energy_unit": "kJ/mol", "adsorbate_density_units": "kg/m^3", "host_ads_vdw_energy_dev": 0.0176859061908279, "enthalpy_of_adsorption_average": -314.23365, "host_ads_coulomb_energy_unit": "kJ/mol", "temperature_dev": NaN, "framework_heat_capacity_units": "J/mol/K", "cell_volume_average": 37717.30829, "host_ads_vdw_energy_unit": "kJ/mol", "framework_density": "0.355004051315", "ads_ads_total_energy_unit": "kJ/mol", "ads_ads_coulomb_energy_average": 0.0, "framework_heat_capacity_average": 0.7042, "ads_ads_vdw_energy_unit": "kJ/mol", "temperature_units": "K", "pressure_dev": 0.0}'
```

When I export a dictionary with `None` values, I get null as value, not NaN
```
In [10]: json.dumps({'a': None})
Out[10]: '{"a": null}'
```

So, I guess that this is a borderline case where NaN is not allowed but supported in some cases and the database adapter or postgresql complains (note that in Django EAV, we don't store JSON) since it wants to follow a strict JSON syntax (nothing bad until here)

So I would look why that value is NaN and what does it mean. Does it imply that the value is None. If yes, then maybe the correct value is null and not NaN.

The place where all these changes should take place are at line 1257 of importexport.py.

Of course, if we decide to convert NaN to nulls then we should be coherent at the export (the export method is common for both backends) and we should not have NaN in some cases and none in others.

(I hope I did not miss anything and I understood correctly the problem - I am a bit tired)

**Comment by ltalirz** [comment]
Thanks for looking into this!

Concerning how we get to this NaN value, here just no way for reference:
```
In [2]: import numpy as np

In [3]: np.nan
Out[3]: nan

In [4]: a = { 'a': np.nan }

In [5]: import json

In [6]: json.dumps(a)
Out[6]: '{"a": NaN}'
```

From the `json.dumps` documentation

> If ``allow_nan`` is false, then it will be a ``ValueError`` to
serialize out of range ``float`` values (``nan``, ``inf``, ``-inf``) in
strict compliance of the JSON specification, instead of using the
JavaScript equivalents (``NaN``, ``Infinity``, ``-Infinity``).

So, maybe the proper solution going forward is actually to enforce `allow_nan=False` here:
https://github.com/aiidateam/aiida_core/blob/521b77824c0e066f5ba0f58045b98f7a0269b9ef/aiida/common/json.py#L47
This will prevent people from storing the `NaN` values in AiiDA nodes (some people may need to adapt their plugins but I think this is the way to go).

The question then becomes: What should we do for existing databases that contain the `NaN` values?

We need at least a practical solution - e.g.  is there an SQL query that you can apply to your database to simply replaces all `NaN` with `None`?
I'm not an SQL expert, so a hint on this would be very much appreciated.


For reference, here a link to the line you mentioned:
https://github.com/aiidateam/aiida_core/blob/110ac3017093ca968e9f1015f074c462a15a9b02/aiida/orm/importexport.py#L1257

**Comment by szoupanos** [comment]
Hm.....

I would like to think a bit more but I would say than NaN can be converted to null.
And then you can apply an SQL update statement to convert all the NaN to nulls by scanning the full db_dbattribute table and changing all the NaN values to nulls

```
aiidadb_dj1=# \d db_dbattribute
                                      Table "public.db_dbattribute"
  Column   |           Type           | Collation | Nullable |                  Default
-----------+--------------------------+-----------+----------+--------------------------------------------
 id        | integer                  |           | not null | nextval('db_dbattribute_id_seq'::regclass)
 key       | character varying(1024)  |           | not null |
 datatype  | character varying(10)    |           | not null |
 tval      | text                     |           | not null |
 fval      | double precision         |           |          |
 ival      | integer                  |           |          |
 bval      | boolean                  |           |          |
 dval      | timestamp with time zone |           |          |
 dbnode_id | integer                  |           | not null |
Indexes:
    "db_dbattribute_pkey" PRIMARY KEY, btree (id)
    "db_dbattribute_dbnode_id_key_c589e447_uniq" UNIQUE CONSTRAINT, btree (dbnode_id, key)
    "db_dbattribute_datatype_91c4dc04" btree (datatype)
    "db_dbattribute_datatype_91c4dc04_like" btree (datatype varchar_pattern_ops)
    "db_dbattribute_dbnode_id_253bf153" btree (dbnode_id)
    "db_dbattribute_key_ac2bc4e4" btree (key)
    "db_dbattribute_key_ac2bc4e4_like" btree (key varchar_pattern_ops)
    "tval_idx_for_daemon" btree (tval) WHERE tval = ANY (ARRAY['COMPUTED'::text, 'WITHSCHEDULER'::text, 'TOSUBMIT'::text])
Foreign-key constraints:
    "db_dbattribute_dbnode_id_253bf153_fk_db_dbnode_id" FOREIGN KEY (dbnode_id) REFERENCES db_dbnode(id) DEFERRABLE INITIALLY DEFERRED
```

I tried to add a NaN value to a Django EAV AiiDA (commit 875f3dbbd) but I failed - it refused to store it...

```
In [10]: n = CalculationNode()

In [11]: n.set_attribute('a', np.nan)
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-11-8fdb3dce7de1> in <module>()
----> 1 n.set_attribute('a', np.nan)

/home/aiida/aiida-code/aiida_core/aiida/orm/utils/mixins.pyc in set_attribute(self, key, value, **kwargs)
    197             raise ModificationNotAllowed('Cannot change the immutable attributes of a stored node')
    198
--> 199         super(Sealable, self).set_attribute(key, value, stored_check=False, **kwargs)
    200
    201     @override

/home/aiida/aiida-code/aiida_core/aiida/orm/nodes/node.pyc in set_attribute(self, key, value, clean, stored_check)
    381
    382         if clean:
--> 383             value = clean_value(value)
    384
    385         if self.is_stored:

/home/aiida/aiida-code/aiida_core/aiida/orm/utils/node.pyc in clean_value(value)
    203     # but is not an integer, I still accept it)
    204
--> 205     return clean_builtin(value)
    206
    207

/home/aiida/aiida-code/aiida_core/aiida/orm/utils/node.pyc in clean_builtin(val)
    179         if isinstance(val, numbers.Real) and (math.isnan(val) or math.isinf(val)):
    180             # see https://www.postgresql.org/docs/current/static/datatype-json.html#JSON-TYPE-MAPPING-TABLE
--> 181             raise exceptions.ValidationError("nan and inf/-inf can not be serialized to the database")
    182         # This fixes #2773 - in python3, ``numpy.int64(-1)`` cannot be json-serialized
    183         if isinstance(val, numbers.Integral) and not isinstance(val, bool):

ValidationError: nan and inf/-inf can not be serialized to the database
```

So it is interesting to understand how we managed to store NaN in the first place (very likely in the past we allowed it and during import we allow it in Django EAV). But maybe this might not be the most critical point.

What's good (and I would keep) is that in the latest version of AiiDA Django EAV, we cannot store NaN. (And the same should stand for AiiDA SQLA - so it looks that we are coherent in both backends)

In any case, in order to correct the existing NaNs, my approach would be to have a look at the db_dbattribute to see where we store NaN and then, I would write an update query that would change all the NaN values to nulls.

https://www.w3schools.com/sql/sql_update.asp

Let me know what you think (if I miss anything).

**Comment by ltalirz** [comment]
> So it is interesting to understand how we managed to store NaN in the first place (very likely in the past we allowed it and during import we allow it in Django EAV).

Indeed, the following works in aiida-core 0.12 but not (the equivalent) in 1.0:
```
In [1]: import numpy as np

In [2]: from aiida.orm import Node

In [4]: from aiida.orm.data.parameter import ParameterData

In [7]: p = ParameterData(dict={'key': np.nan })
```
We should probably still add `allow_nan=False` both in 0.12 and in 1.0.

As for the SQL query, in which columns should I replace?
```
select * from db_dbattribute where false;
 id | key | datatype | tval | fval | ival | bval | dval | dbnode_id
----+-----+----------+------+------+------+------+------+-----------
```
Something like this?
```
update db_dbattributes set tval = replace(fval, NaN, 'None')
```

**Comment by ltalirz** [comment]
Just encountered this issue again during the migration of the tc-applicability database for Materials Cloud (see [archive entry](https://archive.materialscloud.org/record/2019.0024/v3)).

 * This is a database created with aiida 0.x
 * The export file was successfully migrated to 1.3.0
 * The import of the migrated database then fails:

```
$ verdi -p tc-applicability import .aiida/repository/tc-applicability/archives_migrated/database_tc_test.aiida 
Info: importing archive .aiida/repository/tc-applicability/archives_migrated/database_tc_test.aiida
                                                                                                     
IMPORT
--------  ----------------------
Archive   database_tc_test.aiida
 
Parameters
--------------------------  ------
Comment rules               newest
New Node Extras rules       import
Existing Node Extras rules  kcl
Error: an exception occurred while importing the archive .aiida/repository/tc-applicability/archives_migrated/database_tc_test.aiida
DataError: invalid input syntax for type json
LINE 1: ...-27T18:49:49.343787+00:00'::timestamptz, 2, NULL, '{"total_e...
                                                             ^
DETAIL:  Token "Infinity" is invalid.
CONTEXT:  JSON data, line 1: ...50354, "enthalpy_of_adsorption_average": Infinity...
```

This is, of course, a legacy issue but we may put in place replacement rules for the migration of invalid JSON data (like NaN, infinity, ...)

**Comment by greschd** [comment]
See also related issues: https://github.com/aiidateam/aiida-core/issues/3450 https://github.com/aiidateam/aiida-core/issues/2412

**Comment by ltalirz** [comment]
Ah, thanks. Since the migration of the old values is the main concern left in this issue, I will close it in favor of #3450 and reference my comment there.
