### ISSUE TITLE
Randomly failing test (test_daemon_start_number)

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-core#3051]
```
======================================================================
FAIL: test_daemon_start_number (aiida.backends.tests.cmdline.commands.test_daemon.TestVerdiDaemon)
Test `verdi daemon start` with a specific number of workers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/aiidateam/aiida_core/aiida/backends/tests/cmdline/commands/test_daemon.py", line 67, in test_daemon_start_number
    self.assertIn('info', worker_response, worker_response)
AssertionError: {'status': 'error', 'errno': 5, 'reason': 'command \'{"command":"stats","properties":{"name":"aiida-test_django"},"id":"ad45b801da144c8bb244d534128a4f1b"}\': psutil.NoSuchProcess process no longer exists (pid=30005)', 'time': 1560954880.50928, 'tb': 'Traceback (most recent call last):\n  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/circus/controller.py", line 200, in dispatch\n    resp = cmd.execute(self.arbiter, properties)\n  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/circus/commands/stats.py", line 119, in execute\n    "info": watcher.info(props.get(\'extended\'))}\n  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/circus/util.py", line 479, in _log\n    return func(self, *args, **kw)\n  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/circus/watcher.py", line 840, in info\n    for proc in self.processes.values()])\n  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/circus/process.py", line 523, in info\n    info["children"].append(get_info(child))\n  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/circus/util.py", line 234, in get_info\n    info[\'mem\'] = round(get_memory_percent(process), 3)\n  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/circus/process.py", line 68, in get_memory_percent\n    return proc.memory_percent()\n  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/psutil/__init__.py", line 1189, in memory_percent\n    metrics = fun()\n  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/psutil/_common.py", line 344, in wrapper\n    return fun(self)\n  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/psutil/__init__.py", line 1151, in memory_info\n    return self._proc.memory_info()\n  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/psutil/_pslinux.py", line 1525, in wrapper\n    raise NoSuchProcess(self.pid, self._name)\nNoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=30005)\n', 'id': 'ad45b801da144c8bb244d534128a4f1b'}
----------------------------------------------------------------------
```

[Full Travis log here](https://github.com/aiidateam/aiida_core/files/3306956/log.txt) (print it in a terminal to see the colors)

Restarting the job makes it work.

**Comment by csadorf** [comment]
This is still an issue for the **(3.5, sqlalchemy)** environment, see for example this failed run: https://github.com/aiidateam/aiida-core/runs/549101599?check_suite_focus=true Restarting the workflow fixes the issue _sometimes_.

I've attached the log file with the output of the failing job: [12_Run test suite.txt](https://github.com/aiidateam/aiida-core/files/4410043/12_Run.test.suite.txt)

@sphuber @ltalirz I recommend that we skip this test for this particular environment temporarily, because it is severely disrupting our CI workflow.

**Comment by sphuber** [comment]
Except that there is no reason to suspect that this is only a problem for python 3.5 and/or SqlAlchemy. It should be completely unrelated and I expect it to be able to happen for any of the other configurations as well. So then it should be skipped in general

**Comment by csadorf** [comment]
> Except that there is no reason to suspect that this is only a problem for python 3.5 and/or SqlAlchemy. It should be completely unrelated and I expect it to be able to happen for any of the other configurations as well. So then it should be skipped in general

@sphuber True, I just saw it only fail for that particular combination anecdotally. I'll create a PR to skip this test for all combinations.

**Comment by giovannipizzi** [comment]
Ok for disabling, still we shouldn't forget about this.

I have a feeling this is due to a timeout?

A simple script that runs forever to test if this happens:
```python
from click.testing import CliRunner
from aiida.cmdline.commands import cmd_daemon
from aiida.engine.daemon.client import DaemonClient
from aiida.manage.configuration import get_config
import time

cli_runner = CliRunner()
daemon_client = DaemonClient(get_config().current_profile)
from aiida.manage.configuration import get_config

tb = None
while tb is None:
  cli_runner.invoke(cmd_daemon.start, ["36"])
  daemon_response = daemon_client.get_daemon_info()
  worker_response = daemon_client.get_worker_info()
  info = worker_response.get('info')
  tb = worker_response.get('tb')
  print(info)
  cli_runner.invoke(cmd_daemon.stop, [])
  time.sleep(1)

print(tb)
```

I have been trying on my Mac but I don't seem to reproduce the problem... Maybe we should test on Ubuntu with py3.5
