### ISSUE TITLE
Fix `verdi data structure show`

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#3074]
On `develop` branch, with python 3.6:

```python
>> verdi data structure show -F vesta 3770
Traceback (most recent call last):
  File "//anaconda/envs/aiida-workshop/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/cmdline/utils/decorators.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/cmdline/commands/cmd_data/cmd_structure.py", line 116, in structure_show
    show_function(fmt, data)
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/cmdline/commands/cmd_data/cmd_show.py", line 152, in _show_vesta
    tmpf.write(structure._exportcontent('cif')[0])
  File "//anaconda/envs/aiida-workshop/lib/python3.6/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
TypeError: write() argument must be str, not bytes
```

Also the same for other formats that write a temporary file.
One way to fix this is to use `six.ensure_str`

**Comment by sphuber** [comment]
This has been fixed in PR #3417
