### ISSUE TITLE
CalcJob retrieval task excepted

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#3089]
```python
$ verdi process report 7743
*** 7743: None
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 1 LOG MESSAGES:
+-> REPORT at 2019-06-26 06:50:30.454777+00:00
 | [7743|PwCalculation|on_except]: Traceback (most recent call last):
 |   File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/plumpy/processes.py", line 1079, in step
 |     next_state = yield self._run_task(self._state.execute)
 |   File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/plumpy/processes.py", line 499, in _run_task
 |     tornado.stack_context.StackContext(self._process_scope), functools.partial(coro, *args, **kwargs))
 |   File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "//anaconda/envs/aiida-workshop/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
 |     yielded = self.gen.send(value)
 |   File "/Users/cjs14/GitHub/aiida_core_develop/aiida/engine/processes/calcjobs/tasks.py", line 330, in execute
 |     calc_info, script_filename = yield self._launch_task(task_upload_job, node, transport_queue, *args)
 | TypeError: 'bool' object is not iterable
```

I think it was due to a temporary downed connection with PBSPro. In which case, this should have triggered the normal exponential back off and pause procedure.

**Comment by sphuber** [comment]
It seems the future from `self._launch_task` returned a boolean, which when then attempted to expand in the tuple `calc_info, script_filename` raises the exception. We should check why `task_upload` did not return the tuple if it did work. And if it excepted, it should have bubbled up the exception to the `Waiting.execute` method. Did you have the loglevel at `INFO` by any chance and if so, could you find the daemon logs around the time of this exception?

**Comment by sphuber** [comment]
This code has changed significantly and so probably the bug is no longer relevant. Please reopen if it occurs again
