### ISSUE TITLE
`verdi process watch` error

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida-core#3128]
There seems to be a problem with the command `verdi process watch` where the following exception was reached:

```
07/04/2019 01:08:40 PM <19245> kiwipy.rmq.communicator: [ERROR] Exception in broadcast receiver
Traceback (most recent call last):
  File "/home/bonan/miniconda3/envs/aiida-1.0-main/lib/python2.7/site-packages/kiwipy/rmq/communicator.py", line 237, in _on_broadcast
    msg[messages.BroadcastMessage.CORRELATION_ID])
  File "/home/bonan/miniconda3/envs/aiida-1.0-main/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/bonan/miniconda3/envs/aiida-1.0-main/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/bonan/miniconda3/envs/aiida-1.0-main/lib/python2.7/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/home/bonan/miniconda3/envs/aiida-1.0-main/lib/python2.7/site-packages/kiwipy/filters.py", line 33, in __call__
    self._subscriber(communicator, body, sender, subject, correlation_id)
TypeError: _print() takes exactly 4 arguments (5 given)
```
The `_print` function takes 4 arguments:

https://github.com/aiidateam/aiida_core/blob/e232f946e2b5c1c55c8f8b2c903f05355fe9deea/aiida/cmdline/commands/cmd_process.py#L262-L273

But the callback gives 5 arguments in `kiwipy` here:

https://github.com/aiidateam/kiwipy/blob/f0b3ea3c6cd1ec9653586ee5ca5bdb6dcc84e565/kiwipy/filters.py#L9-L33

The `communicator` argument was not included in the `_print` function.

BTW I am not quite sure what exactly this command does and it appears to hang most of the time....

**Comment by sphuber** [comment]
I think the "hanging" is not so much hanging but rather the intended behavior. The idea of the command is that it attaches itself as a listener to the process to receive broadcasts that the process sends. The process does this for example between state transitions. In principle then what happens when you launch this command is that it will start waiting and print these broadcast messages when it receives them. In any case at some point you simply have to abort the command to stop listening.
