### ISSUE TITLE
Error exporting/importing archive

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#3144]
I created [this archive](https://github.com/chrisjsewell/aiida_core/tree/9d40b8fcbc6beb75a5ef5ea91aa5c607578f300f/aiida/backends/tests/fixtures/graphs/graph1.aiida) using `verdi export create -N 1 2 3 -- path/to/graph1.aiida`. However, when I create a new database/repository and try `verdi import path/to/graph1.aiida`, I get:

```python
Info: importing archive aiida/backends/tests/fixtures/graphs/graph1.aiida
READING DATA AND METADATA...
EXTRACTING NODE DATA...
Comment mode: newest
existing User: chrisj_sewell@hotmail.com (1460->1)
NEW Computer: 77664d7f-bf77-4ffd-a4cd-a8bc54b6e07f (1474->2)
STORING NEW NODE FILES...
STORING NEW NODE ATTRIBUTES...
STORING NEW NODE EXTRAS...
STORING NEW NODE ATTRIBUTES...
STORING NEW NODE EXTRAS...
STORING NEW NODE ATTRIBUTES...
STORING NEW NODE EXTRAS...
STORING NEW NODE ATTRIBUTES...
STORING NEW NODE EXTRAS...
Error: an exception occurred while importing the archive aiida/backends/tests/fixtures/graphs/graph1.aiida
Traceback (most recent call last):
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/cmdline/commands/cmd_import.py", line 67, in _try_import
    import_data(file_to_import, group, **kwargs)
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/tools/importexport/dbimport/__init__.py", line 54, in import_data
    return import_data_dj(in_path, group=group, silent=silent, **kwargs)
  File "/Users/cjs14/GitHub/aiida_core_develop/aiida/tools/importexport/dbimport/backends/django/__init__.py", line 360, in import_data_dj
    "file".format(object_.uuid))
ValueError: Unable to find the repository folder for node with UUID=93cd9b2f-d3ce-4214-b331-5808f55073b3 in the exported file
```

**Comment by CasperWA** [comment]
I mean - the error message is not wrong :sweat_smile: the repo folder is truly missing for your CalcJobNode. So it must be a problem in the export function somewhere. I'll try and take a look through it. To be better prepared, could you walk me through how you created the nodes in question, and what nodes "`1 2 3`" refer to?

**Comment by sphuber** [comment]
I remember that this can happen when people manually delete repository folders. The export functionality will not complain and just create the archive. The import clearly does complain. The only "solution" is to recreate an empty repository folder for the affected nodes and recreate the archive.

**Comment by CasperWA** [comment]
In agreement with @sphuber, I will implement a similar "safeguard" in the export function as already exists in the import function, i.e., raise when a repo folder cannot be found for any given Node.

**Comment by chrisjsewell** [comment]
Here's how to create the entire archive!

```python
from aiida import orm
from aiida.engine import ProcessState
from aiida.common.links import LinkType
from aiida.orm.utils.builders.computer import ComputerBuilder
from aiida.orm.utils.builders.code import CodeBuilder
from aiida.plugins.entry_point import get_entry_point

computer_builder = ComputerBuilder(
    label="example_computer",
    description='an example computer',
    transport='local',
    scheduler='direct',
    hostname='localhost',
    prepend_text='',
    append_text='',
    work_dir='/path/to/work_dir',
    shebang='#!/bin/bash',
    mpiprocs_per_machine=1,
    mpirun_command='mpiexec'
)
computer = computer_builder.new()
computer.store()

code_builder = CodeBuilder(
    **{
        'label': 'example_code@example_computer',
        'description': 'an example code',
        'code_type': CodeBuilder.CodeType.ON_COMPUTER,
        'computer': computer,
        'prepend_text': '',
        'append_text': '',
        'input_plugin': get_entry_point('aiida.calculations', 'arithmetic.add'),
        'remote_abs_path': '/path/to/exec'
    }
)
c1 = code_builder.new()
c1.store()

pd0 = orm.Dict()
pd0.label = "pd0"
pd0.store()

pd1 = orm.Int(3)
pd1.label = "pd1"
pd1.store()

wc1 = orm.WorkChainNode()
wc1.set_process_state(ProcessState.RUNNING)
wc1.add_incoming(c1, link_type=LinkType.INPUT_WORK, link_label='code')
wc1.add_incoming(pd0, link_type=LinkType.INPUT_WORK, link_label='input1')
wc1.add_incoming(pd1, link_type=LinkType.INPUT_WORK, link_label='input2')
wc1.store()

calc1 = orm.CalcJobNode()
calc1.computer = computer
calc1.set_option('resources', {"num_machines": 1,
                               "num_mpiprocs_per_machine": 1})
calc1.label = "calc1"
calc1.set_process_state(ProcessState.FINISHED)
calc1.set_exit_status(0)
calc1.add_incoming(c1, link_type=LinkType.INPUT_CALC, link_label='code')
calc1.add_incoming(pd0, link_type=LinkType.INPUT_CALC, link_label='input1')
calc1.add_incoming(pd1, link_type=LinkType.INPUT_CALC, link_label='input2')
calc1.add_incoming(wc1, link_type=LinkType.CALL_CALC, link_label='call1')
calc1.store()

rd1 = orm.RemoteData()
rd1.label = "rd1"
rd1.set_remote_path("/x/y.py")
rd1.computer = computer
rd1.store()
rd1.add_incoming(calc1, link_type=LinkType.CREATE, link_label='output')

pd2 = orm.Str("abc")
pd2.label = "pd2"
pd2.store()

calcf1 = orm.CalcFunctionNode()
calcf1.label = "calcf1"
calcf1.set_process_state(ProcessState.FINISHED)
calcf1.set_exit_status(200)
calcf1.add_incoming(rd1, link_type=LinkType.INPUT_CALC, link_label='input1')
calcf1.add_incoming(pd2, link_type=LinkType.INPUT_CALC, link_label='input2')
calcf1.add_incoming(wc1, link_type=LinkType.CALL_CALC, link_label='call2')
calcf1.store()

pd3 = orm.Dict()
pd3.label = "pd3"

fd1 = orm.FolderData()
fd1.label = "fd1"

pd3.add_incoming(calcf1, link_type=LinkType.CREATE, link_label='output1')
pd3.store()
fd1.add_incoming(calcf1, link_type=LinkType.CREATE, link_label='output2')
fd1.store()

pd3.add_incoming(wc1, link_type=LinkType.RETURN, link_label='output1')
fd1.add_incoming(wc1, link_type=LinkType.RETURN, link_label='output2')

print(f"dict1_uuid = '{pd0.uuid}'")
print(f"calc1_uuid = '{calc1.uuid}'")

path = "graph.aiida"
print(
    f"verdi export create -X {c1.id} -N {pd0.id} {pd1.id} {wc1.id} {calc1.id} {rd1.id} {pd2.id} {calcf1.id} {pd3.id} {fd1.id} -- {path}")
```

**Comment by CasperWA** [comment]
Thanks @chrisjsewell, could you perhaps also check if you have the repo folder locally related to the CalcJobNode in question?

**Comment by chrisjsewell** [comment]
Yeh the repo folder is there, but obviously empty, which appears to be the problem. Just tried adding something to its repo before exporting, and the import now looks to be working.

**Comment by chrisjsewell** [comment]
So I guess in the export function, you need to make sure the repo is still created, even if it is empty
