### ISSUE TITLE
Consistently failing REST API test on Jenkins

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3152]
The following test has been failing consistently on Jenkins builds:
```

======================================================================

FAIL: test_computers_mixed1 (aiida.backends.tests.test_restapi.RESTApiTestSuite)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/var/jenkins_home/workspace/aiida_core_aiidateam_PR-3150/aiida/backends/tests/test_restapi.py", line 648, in test_computers_mixed1

    self, "computers", "/computers?id>" + str(node_pk) + "&limit=2&offset=3", expected_list_ids=[4])

  File "/var/jenkins_home/workspace/aiida_core_aiidateam_PR-3150/aiida/backends/tests/test_restapi.py", line 314, in process_test

    self.assertEqual(expected_node_uuids, result_node_uuids)

AssertionError: Lists differ: ['e3ea25a8-db14-447d-ad2a-d05b... != ['f533c879-bf94-46e9-8c01-4ab6...


First differing element 0:

'e3ea25a8-db14-447d-ad2a-d05b99375af8'

'f533c879-bf94-46e9-8c01-4ab629dba20d'


- ['e3ea25a8-db14-447d-ad2a-d05b99375af8']

+ ['f533c879-bf94-46e9-8c01-4ab629dba20d']
```

**Comment by giovannipizzi** [comment]
Probably the test does not enforce order, and the tests happens to run ok on travis for random reasons. Could you make sure results that are tested are returned in a consistent order?

**Comment by sphuber** [comment]
I just had a case where it also failed on Travis
[log.txt](https://github.com/aiidateam/aiida-core/files/3509011/log.txt)
