### ISSUE TITLE
Doc builds failing on readthedocs

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3244]
The builds on readthedocs are currently failing ([link to list of builds](https://readthedocs.org/projects/aiida-core/builds/)).

It seems `pymatgen` is the issue, or rather, the dependency on `numpy` within `pymatgen`, which requires Python >= v3.5, and readthedocs builds using Python 2.7.

The "full" error can be seen below, starting from when `pymatgen` is being installed.

```shell
Collecting pymatgen==2018.12.12 (from -r docs/requirements_for_rtd.txt (line 51))
  Using cached https://files.pythonhosted.org/packages/d6/b9/f386300f232c8523f562e39bf07bae0d9c4e6379f423f71df7cd622ddae7/pymatgen-2018.12.12.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-BmFdVZ/pymatgen/setup.py'"'"'; __file__='"'"'/tmp/pip-install-BmFdVZ/pymatgen/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-BmFdVZ/pymatgen/
    Complete output (51 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-BmFdVZ/pymatgen/setup.py", line 177, in <module>
        'get_environment = pymatgen.cli.get_environment:main',
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/home/docs/.pyenv/versions/2.7.16/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/docs/.pyenv/versions/2.7.16/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/v0.12.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-HAjBlb/numpy-1.17.0/setup.py", line 31, in <module>
        self.include_dirs.append(numpy.get_include())
    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by CasperWA** [comment]
Diving further into this, it is weird, because readthedocs used to use Python v3.7, not v2.7.

Also, as a side-note - @ltalirz, could you update the repository link [here](https://readthedocs.org/projects/aiida-core/) to point to "aiida-core" instead of "aiida_core"?

**Comment by CasperWA** [comment]
I guess we should do [this](https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-v1)

**Comment by ltalirz** [comment]
Re this issue: we already discussed this via email

This is from @sphuber 

> I switched the interpreter for RTD back to py2 and launched another build for 0.12.4, but unfortunately no dice:
> https://readthedocs.org/projects/aiida-core/builds/9449443/
> I know remember the reason that I switched to py3, because the problem is a setup dependency of pymatgen
> on numpy which installs a version that is only py3 compatible.
> We put a hack in place on `develop`: https://github.com/aiidateam/aiida-core/commit/a7575d80b717b8361ab96e2117c4544c39bc87ee
> Long story short: docs of 0.12.4 is broken.
> Cannot build with py2, because that will install incompatible numpy
> Cannot build with py3, because 0.12.4 is not py3-compatible.
> Only solution I see is to apply the same hack we did for develop and release 0.12.5 if the docs are really crucial.

This is what I suggested (not sure anyone tried so far):

> Hm... that is indeed a bit of an issue - we would need to install a particular version of numpy before installing pymatgen but I don't know how to do that on RTD.
> An alternative hack could be to:
>  * figure out which numpy version is present on RTD
>  * change the numpy version of the RTD dependencies to that version

I.e. you would make a small edit [here](https://github.com/aiidateam/aiida-core/blob/develop/docs/update_req_for_rtd.py#L37)

**Comment by ltalirz** [comment]
> - @ltalirz, could you update the repository link here to point to "aiida-core" instead of "aiida_core"?

Done

**Comment by ltalirz** [comment]
> I guess we should do this

Maybe? Feel free to look into this. Also, just let me know your rtd username and I can add you to the project

**Comment by CasperWA** [comment]
> (..) Also, just let me know your rtd username and I can add you to the project

I logged in using GitHub, so should be CasperWA

**Comment by ltalirz** [comment]
> I logged in using GitHub, so should be CasperWA

Sorry for the insane delay - have finally added you!

**Comment by sphuber** [comment]
I think this can be closed, no? Documentation builds have not failed in a long time. If not feel free to reopen
