### ISSUE TITLE
cannot import name 'is_dbenv_loaded' from 'aiida.backends.utils'

### ISSUE THREAD

**Issue by chenweiguang82** [aiidateam/aiida-core#3252]
Hi,
I have installed aiida, the following is what i installed:
aiida-ase         1.0.1
aiida-core        1.0.0b5
aiida-diff        1.0.0b1
aiida-vasp        0.2.4
----------------------
I want to set the pseudopotential for VASP calculations, but the error occur when i run the following command:
`verdi data vasp-potcar uploadfamily --path=/home/zznu/vasp_pot/potpaw_PBE --name=PBE.54 --description="PBE potentials for version 5.4"` 

> Traceback (most recent call last):
  File "/home/zznu/.virtualenvs/aiida/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/click/core.py", line 1135, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/click/core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/aiida_vasp/commands/potcar.py", line 23, in try_grab_description
    potcar_data_cls = get_data_class('vasp.potcar')
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/aiida_vasp/utils/aiida_utils.py", line 19, in decorated_function
    load_dbenv_if_not_loaded()
  File "/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/aiida_vasp/utils/aiida_utils.py", line 8, in load_dbenv_if_not_loaded
    from aiida.backends.utils import load_dbenv, is_dbenv_loaded
ImportError: cannot import name 'is_dbenv_loaded' from 'aiida.backends.utils' (/home/zznu/.virtualenvs/aiida/lib/python3.7/site-packages/aiida/backends/utils.py)

**Comment by sphuber** [comment]
The problem is that the version `aiida-vasp==0.2.4` is not compatible with `aiida-core==1.0.0b5`. The migration of the VASP plugin is underway in [this branch](https://github.com/aiida-vasp/aiida-vasp/commits/migration_beta). To install it, you have to clone the repository, checkout the branch and install it:
```
git clone git@github.com:aiida-vasp/aiida-vasp.git
cd aiida-vasp
git checkout migration_beta
pip install -e .'
reentry scan
```
This should solve the problem

**Comment by chenweiguang82** [comment]
Thanks for you response.
I did what you said, but aiida-vasp require pymatgen==2018.12.12.
I have installed latest pymatgen, an error occurred while compiling version 2018.12.12
[install.log](https://github.com/aiidateam/aiida-core/files/3504913/install.log)
