### ISSUE TITLE
`verdi data cif show {CifData}` not working in aiida-1.0.0b5

### ISSUE THREAD

**Issue by danieleongari** [aiidateam/aiida-core#3277]
As shown in the example, a correct CifData fails to show (`-F jmol` and `-F vesta` give similar errors).

```
$verdi data cif content 7755
data_crystal
_audit_creation_method AiiDA-ddec_plugin 
 
_cell_length_a    4.00001
_cell_length_b    5.52648
_cell_length_c    4.59630
_cell_angle_alpha 90.00000
_cell_angle_beta  90.00000
_cell_angle_gamma 90.00000
 
_symmetry_space_group_name_Hall 'P 1'
_symmetry_space_group_name_H-M  'P 1'
 
loop_
_symmetry_equiv_pos_as_xyz
 'x,y,z' 
 
loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_charge
O          O       0.50000   0.50000   0.56487  -0.77829
H          H       0.50000   0.63811   0.43513   0.38914
H          H       0.50000   0.36189   0.43513   0.38915

$ verdi data cif show 7726
Traceback (most recent call last):
  File "/home/daniele/anaconda3/envs/aiida1/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daniele/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/daniele/anaconda3/envs/aiida1/lib/python3.6/site-packages/aiida/cmdline/utils/decorators.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/daniele/anaconda3/envs/aiida1/lib/python3.6/site-packages/aiida/cmdline/commands/cmd_data/cmd_cif.py", line 87, in cif_show
    show_function(fmt, data)
  File "/home/daniele/anaconda3/envs/aiida1/lib/python3.6/site-packages/aiida/cmdline/commands/cmd_data/cmd_show.py", line 63, in _show_jmol
    tmpf.write(trajectory._exportcontent('cif', **kwargs)[0])
  File "/home/daniele/anaconda3/envs/aiida1/lib/python3.6/tempfile.py", line 485, in func_wrapper
    return func(*args, **kwargs)
TypeError: write() argument must be str, not bytes
```

**Comment by danieleongari** [comment]
Hi, this is still not working in `aiida-1.0.0b6`,
is it fixed in the `develop` branch?
I would gently ask some priority on this, since it is a pretty basic function.

**Comment by sphuber** [comment]
Should be fixed now on `develop`

**Comment by danieleongari** [comment]
Just tested, thanks @sphuber !
