### ISSUE TITLE
interface of "verdi data bands export"

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3282]
Currently, the `verdi data bands export` command has a slightly weird interface, where for some formats it is OK to print the results to screen while for other options one needs to specify an output file.

Unlike the documentation claims, this is not only necessary for commands that produce more than one output file but also leads to decoding errors for other options, e.g.

```
$ verdi data bands export --format mpl_pdf 247
Traceback (most recent call last):
  File "/home/max/.virtualenvs/aiida/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/max/codes/aiida_core/aiida/cmdline/utils/decorators.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/max/codes/aiida_core/aiida/cmdline/commands/cmd_data/cmd_bands.py", line 146, in bands_export
    data_export(datum, output, fmt, other_args=args, overwrite=force)
  File "/home/max/codes/aiida_core/aiida/cmdline/commands/cmd_data/cmd_export.py", line 116, in data_export
    echo.echo(filetext.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 10: invalid start byte
```

I find this interface is not very user friendly and would propose to:
 * remove the possibility to print to screen
 * have a default output file name based on the node (just like `verdi node graph generate`), with the possibility to modify it just as before

@sphuber @giovannipizzi Does this sound reasonable?

**Comment by giovannipizzi** [comment]
I would say that it's ok to make the behavior uniform. However, just for me to remember if there was a reason for not writing on a file, which are the ones writing on stdout?

**Comment by ltalirz** [comment]
>  just for me to remember if there was a reason for not writing on a file, which are the ones writing on stdout?

The ones that currently don't crash when writing to stdout are: agr, dat_blocks, dat_multicolumn, json, mpl_singlefile,

**Comment by sphuber** [comment]
I am not sure, because I have never really used these endpoints nor developed them. One potential downside of removing the printing to stdout is that it makes using it in shell pipe lines more complicated. It might be useful to pipe the formatted output directly into the visualizing software. Making the output file optional with a sensible default _if_ we decide to remove stdout as option, seems sensible

**Comment by giovannipizzi** [comment]
Good point - indeed, I think that I used to typically pipe the plot directly to `xmgrace` (even if probably we have the `show` command for this, but maybe sometimes you have to do it over SSH or similar).
Also I think that I originally implemented this with stdout only, to then realise that there are cases where this is not possible (more than one file needed).

Maybe indeed one option is to make writing to a file the default, but use the convention that writing to `-` is stdout, and raise if there is more than one file for the specific format chosen
