### ISSUE TITLE
Meet ERROR when setup a profile

### ISSUE THREAD

**Issue by 1976114031** [aiidateam/aiida-core#3307]
The version i used is 0.12.4.  
When i setup a profile as follows:  

```
(aiida) wangl@ubuntu:~$ verdi setup aiida_02
Setting up profile aiida_02.
AiiDA backend (available: django, sqlalchemy - sqlalchemy is in beta mode): django
Default user email: 1976114031@qq.com
Database engine (available: postgresql_psycopg2, mysql - mysql is deprecated): postgresql_psycopg2
PostgreSQL host: localhost
PostgreSQL port: 5432
AiiDA Database name: aiidadb
AiiDA Database user: aiida
AiiDA Database password: 1q2w3e
AiiDA repository directory: /home/wangl/.aiida/repository-aiida_02/

```
I meet this error
```
The repository /home/wangl/.aiida/repository-aiida_02/ will be created.
Executing now a migrate command...
...for Django backend
Traceback (most recent call last):
  File "/home/wangl/anaconda3/envs/aiida/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/cmdline/verdilib.py", line 1050, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/cmdline/verdilib.py", line 1035, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/cmdline/verdilib.py", line 356, in run
    _setup_cmd.invoke(ctx)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/cmdline/verdilib.py", line 410, in _setup_cmd
    setup(**kwargs)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/cmdline/verdilib.py", line 529, in setup
    profile=gprofile)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/cmdline/__init__.py", line 136, in pass_to_django_manage
    load_dbenv(profile=profile)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/backends/utils.py", line 79, in load_dbenv
    process=process, profile=profile, *args, **kwargs)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/backends/djsite/utils.py", line 27, in load_dbenv
    check_schema_version()
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/backends/djsite/utils.py", line 163, in check_schema_version
    db_schema_version = get_db_schema_version()
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/backends/djsite/utils.py", line 206, in get_db_schema_version
    return get_global_setting('db|schemaversion')
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/backends/utils.py", line 201, in get_global_setting
    return get_global_setting(key)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/aiida_core-0.12.4-py2.7.egg/aiida/backends/djsite/globalsettings.py", line 65, in get_global_setting
    return DbSetting.objects.get(key=key).getvalue()
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/wangl/anaconda3/envs/aiida/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column db_dbsetting.datatype does not exist
LINE 1: SELECT "db_dbsetting"."id", "db_dbsetting"."key", "db_dbsett...
                                                          ^


```  

How can i solve it ?

**Comment by ltalirz** [comment]
hi @1976114031 , this is indeed a bit of a strange error, since it is complaining about a missing database column when setting up the profile.
Is it possible you are reusing a postgres database that was previously used with aiida 1.0? I.e. before you executed the command, was the `aiidadb` empty?

In any case, I would suggest if possible to use aiida 1.0.0b6 - the 1.0 release is near and the 0.12.x series will only see bug fixes.

**Comment by sphuber** [comment]
Since we have not received any more information we are going to close this for the time being. If this is still a problem for you and you can provide some more information, please feel free to reopen this issue.
