### ISSUE TITLE
Daemon runners launched by Circus could except

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3333]
This was encountered when preparing the AWS machine for the SINTEF tutorial starting from the Xiamen image. The daemon, started automatically upon boot through systemd, worked just fine. However, when restarting it, the new daemon appeared to be unresponsive, even though Circus seemed to be working fine and it reported a running worker through `verdi daemon status`. The problem was that the worker was dying as soon as it was launched and Circus was just reviving it, giving the impression one was alive at all times.

To show the problem one should run the Circus daemon directly and in the foreground, through the command `verdi daemon start-circus --foreground`. Note that this is a hidden command and so won't be auto-completed. Once doing this, the problem becomes obvious as the daemon runner excepts:
```
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/max/.virtualenvs/aiida/bin/verdi", line 6, in <module>
    from aiida.cmdline.commands.cmd_verdi import verdi
  File "/home/max/codes/aiida-core/aiida/cmdline/commands/__init__.py", line 21, in <module>
    from aiida.cmdline.commands import (
  File "/home/max/codes/aiida-core/aiida/cmdline/commands/cmd_process.py", line 18, in <module>
    from kiwipy import communications
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/kiwipy/__init__.py", line 5, in <module>
    from .communications import *
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/kiwipy/communications.py", line 3, in <module>
    import concurrent.futures
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

This was with Ubuntu 18.04 and `aiida-core==1.0.0b6` and it is not yet clear why this exception does not occur when the daemon is launched through systemd. Besides finding the origin to this problem and fixing it, we should see if we can change the configuration of Circus such that these exceptions in the daemon runners also make it to the Circus log, which currently does not happen.

**Comment by ltalirz** [comment]
Just to mention: the cause of the issue is that a later version of the aiidalab metapackage installed the `futures` package, which is a backport of `concurrent.futures` provided by python 3.

This was introduced here and should be removed
https://github.com/aiidalab/aiidalab-metapkg/commit/117b3e25677602960b2384232aedaa2392342d3c
