### ISSUE TITLE
missing attribute in CifData after migration

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3463]
after migrating an aiida 0.12 export file (containing even older calculations), I'm getting an issue with a CifData node missing an attribute:

```
Traceback (most recent call last):
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/implementation/django/nodes.py", line 182, in get_attribute
    return self._dbmodel.attributes[key]
KeyError: 'scan_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/wrapt/wrappers.py", line 564, in __call__
    args, kwargs)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/cmdline/utils/decorators.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/cmdline/commands/cmd_node.py", line 440, in graph_generate
    print_func=print_func
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/tools/visualization/graph.py", line 659, in recurse_ancestors
    node, link_types=link_types, annotate_links=annotate_links, return_pks=False
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/tools/visualization/graph.py", line 509, in add_incoming
    self.add_node(link_triple.node)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/tools/visualization/graph.py", line 441, in add_node
    id_type=self._node_id_type
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/tools/visualization/graph.py", line 304, in _add_graphviz_node
    sublabel = node_sublabel_func(node)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/tools/visualization/graph.py", line 221, in default_node_sublabels
    formulae = [str(f).replace(' ', '') for f in node.get_formulae() or []]
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/nodes/data/cif.py", line 525, in get_formulae
    for datablock in self.values.keys():
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/nodes/data/cif.py", line 414, in values
    c = CifFile.ReadCif(handle, scantype=self.get_attribute('scan_type'))  # pylint: disable=no-member
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/nodes/node.py", line 352, in get_attribute
    attribute = self.backend_entity.get_attribute(key)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/orm/implementation/django/nodes.py", line 184, in get_attribute
    raise AttributeError('attribute `{}` does not exist'.format(exception))
AttributeError: attribute `'scan_type'` does not exist
```

This may well be on me - when this change was made, I did not realize that changing a data class requires a corresponding migration.

I'm wondering how to best fix this now.

E.g. in the documentation of `get_attribute` I see a note about default values:
https://github.com/aiidateam/aiida-core/blob/d750d513f7adf5126d43a230c9fb378de02f0772/aiida/orm/implementation/nodes.py#L179
@sphuber How do you specify a default value for an attribute?

**Comment by ltalirz** [comment]
Thanks, that's what I expected - I was confused by the fact that the signature of the abstract method does not have the `default`:

https://github.com/aiidateam/aiida-core/blob/d750d513f7adf5126d43a230c9fb378de02f0772/aiida/orm/implementation/nodes.py#L167-L180

Also the django/sqlalchemy implementations don't have it; it is handled at the ORM node interface (which makes sense).
I guess I should simply adapt the docstrings of the abstract & django/sqla implementations, correct?

> If the implementation requires each node to have that attribute but that is not necessarily the case, then the CifData class will have to provide a default itself everytime it accesses the scan_type

Right - so, the idea would be to introduce a class attribute `scan_type`  that will call `self.get_attribute('scan_type', 'default-value')`, right?

**Comment by sphuber** [comment]
I am not sure if it should be a class attribute, but for now I would just change the internal calls to the attribute to specify a default. What that default should be can of course be defined as a class attribute
