### ISSUE TITLE
Bug in the `--print-groups` option of `verdi node show`

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#3493]
When using the `--print-groups` option of `verdi node show`, the following error is printed:
```
verdi node show 103 --print-groups
Property     Value
-----------  ------------------------------------
type         PwCalculation
state        Finished [0]
pk           103
uuid         7b2b2cb0-e211-4109-9a07-b8180b906524
label
description
ctime        2019-07-22 17:50:58.935829+02:00
mtime        2019-07-22 17:51:10.816327+02:00
computer     [1] localhost

Inputs         PK    Type
-------------  ----  -------------
pseudos
    Si         36    UpfData
code           1     Code
kpoints        102   KpointsData
parameters     101   Dict
parent_folder  91    RemoteData
structure      2     StructureData

Outputs              PK  Type
-----------------  ----  ----------
output_array        106  ArrayData
output_band         108  BandsData
output_parameters   107  Dict
remote_folder       104  RemoteData
retrieved           105  FolderData
#### GROUPS:
Traceback (most recent call last):
  File "/home/pizzi/.virtualenvs/aiida_core/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/pizzi/.virtualenvs/aiida_core/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/pizzi/.virtualenvs/aiida_core/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/pizzi/.virtualenvs/aiida_core/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pizzi/.virtualenvs/aiida_core/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pizzi/.virtualenvs/aiida_core/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pizzi/.virtualenvs/aiida_core/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pizzi/git/aiida_core/aiida/cmdline/utils/decorators.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/pizzi/git/aiida_core/aiida/cmdline/commands/cmd_node.py", line 161, in node_show
    if qb.count() == 0:
  File "/home/pizzi/git/aiida_core/aiida/orm/querybuilder.py", line 2142, in count
    query = self.get_query()
  File "/home/pizzi/git/aiida_core/aiida/orm/querybuilder.py", line 2035, in get_query
    query = self._build()
  File "/home/pizzi/git/aiida_core/aiida/orm/querybuilder.py", line 1867, in _build
    self._build_projections(vertex['tag'])
  File "/home/pizzi/git/aiida_core/aiida/orm/querybuilder.py", line 1192, in _build_projections
    self._add_to_projections(alias, property_name, **extraspec)
  File "/home/pizzi/git/aiida_core/aiida/orm/querybuilder.py", line 1151, in _add_to_projections
    entity_to_project = self._get_projectable_entity(alias, column_name, attr_key, cast=cast)
  File "/home/pizzi/git/aiida_core/aiida/orm/querybuilder.py", line 1127, in _get_projectable_entity
    entity = self._impl.get_column(column_name, alias)
  File "/home/pizzi/git/aiida_core/aiida/orm/implementation/querybuilder.py", line 289, in get_column
    '\n'.join(alias._sa_class_manager.mapper.c.keys())  # pylint: disable=protected-access
aiida.common.exceptions.InputValidationError: name is not a column of aliased(DbGroup)
Valid columns are:
id
uuid
label
type_string
time
description
user_id

```
Probably a leftover of the rename of `name`->`label`?

**Comment by sphuber** [comment]
Fixed in PR #3495
