### ISSUE TITLE
Bug in config migration?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3583]
We're trying to upgrade an AiiDA 0.12.2 installation to 1.0 and, after updating the packages, we run in to the error

```
(aiida1) kdeeg@LSMOPC17:~$ verdi status
Traceback (most recent call last):
  File "/home/kdeeg/miniconda3/envs/aiida1/bin/verdi", line 7, in <module>
    from aiida.cmdline.commands.cmd_verdi import verdi
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/__init__.py", line 50, in <module>
    configure_logging()
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/common/log.py", line 168, in configure_logging
    config = evaluate_logging_configuration(copy.deepcopy(LOGGING))
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/common/log.py", line 143, in evaluate_logging_configuration
    result[key] = evaluate_logging_configuration(value)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/common/log.py", line 143, in evaluate_logging_configuration
    result[key] = evaluate_logging_configuration(value)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/common/log.py", line 145, in evaluate_logging_configuration
    result[key] = value()
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/common/log.py", line 91, in <lambda>
    'level': lambda: get_config_option('logging.aiida_loglevel'),
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/manage/configuration/__init__.py", line 209, in get_config_option
    config = get_config(create=True)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/manage/configuration/__init__.py", line 185, in get_config
    CONFIG = load_config(create=create)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/manage/configuration/__init__.py", line 129, in load_config
    config = Config(filepath, check_and_migrate_config(config_dictionary))
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/manage/configuration/migrations/utils.py", line 28, in check_and_migrate_config
    config = migrate_config(config)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/manage/configuration/migrations/utils.py", line 62, in migrate_config
    config = _MIGRATION_LOOKUP[get_current_version(config)].apply(config)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/manage/configuration/migrations/migrations.py", line 41, in apply
    config = self.migrate_function(config)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/manage/configuration/migrations/migrations.py", line 74, in _2_simplify_default_profiles
    config['default_profile'] = default_profiles['daemon']
KeyError: 'daemon'
```

The reason is that the migration code seems to assume that, if the `default_profiles` key is present, that a `daemon` key must also be present.

https://github.com/ltalirz/aiida-core/blob/45c167717bf84446393fd4e141d923227bf3bd48/aiida/manage/configuration/migrations/migrations.py#L73-L74

In our case this is not true:
```
{
    "default_profiles": {
        "verdi": "COFs"
    }, 
    "CONFIG_VERSION": {
        "CURRENT": 1, 
        "OLDEST_COMPATIBLE": 0
    }, 
    "profiles": {
        "COFs": {
            "AIIDADB_ENGINE": "postgresql_psycopg2
            ...
```

@sphuber : Is this a bug in the code or have we somehow ended up with an "invalid" configuration file?
In any case, I think it would be nice to be able to handle this case

**Comment by ltalirz** [comment]
I'll take care of this one

**Comment by sphuber** [comment]
Not sure to be honest. I think in principle there should always be a default for the daemon because otherwise it wouldn't know what to do when starting the daemon. But maybe if the daemon has never been started? Anyway, I agree that is better to just include this edge-case
