### ISSUE TITLE
Unable to migrate database

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3584]
We are trying to migrate a database from aiida 0.12.2 to aiida 1.0.
`verdi status` runs into an exception connecting to the postgres DB (just shown as an "x" for the postgres service).

We get the same exception when trying to migrate:
```
$ verdi database migrate
Warning: Migrating your database might take a while and is not reversible.
Warning: Before continuing, make sure you have completed the following steps:
Warning:
Warning:  1. Make sure you have no active calculations and workflows.
Warning:  2. If you do, revert the code to the previous version and finish running them first.
Warning:  3. Stop the daemon using `verdi daemon stop`
Warning:  4. Make a backup of your database and repository
Warning:
Warning: If you have completed the steps above and want to migrate profile "COFs", type MIGRATE NOW: MIGRATE NOW
Traceback (most recent call last):
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column db_dbsetting.val does not exist
LINE 1: SELECT "db_dbsetting"."id", "db_dbsetting"."key", "db_dbsett...
                                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kdeeg/miniconda3/envs/aiida1/bin/verdi", line 11, in <module>
    sys.exit(verdi())
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/cmdline/commands/cmd_database.py", line 70, in database_migrate
    backend.migrate()
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/orm/implementation/django/backend.py", line 53, in migrate
    migrate_database()
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/backends/djsite/utils.py", line 124, in migrate_database
    validate_schema_generation()
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/backends/utils.py", line 78, in validate_schema_generation
    schema_generation_database = get_db_schema_generation().value
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/backends/utils.py", line 97, in get_db_schema_generation
    return manager.get(SCHEMA_GENERATION_KEY)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/aiida/backends/djsite/utils.py", line 50, in get
    setting = DbSetting.objects.filter(key=key).first()
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/django/db/models/query.py", line 567, in first
    objects = list((self if self.ordered else self.order_by('pk'))[:1])
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column db_dbsetting.val does not exist
LINE 1: SELECT "db_dbsetting"."id", "db_dbsetting"."key", "db_dbsett...
```

I.e. the migration code assumes that a column `db_dbsetting.val` exists, which does not exist in our case.

@sphuber Is this a bug in the migrations?

Besides fixing the bug, I also don't know how to proceed here to complete the migration...

**Comment by ltalirz** [comment]
Here are the columns of the table
```
# \d+ db_dbsetting
 id          | integer                  | not null default nextval('db_dbsetting_id_seq'::regclass) | plain    |              |
 key         | character varying(1024)  | not null                                                  | extended |              |
 datatype    | character varying(10)    | not null                                                  | extended |              |
 tval        | text                     | not null                                                  | extended |              |
 fval        | double precision         |                                                           | plain    |              |
 ival        | integer                  |                                                           | plain    |              |
 bval        | boolean                  |                                                           | plain    |              |
 dval        | timestamp with time zone |                                                           | plain    |              |
 description | text                     | not null                                                  | extended |              |
 time        | timestamp with time zone | not null                                                  | plain    |              |
```

**Comment by sphuber** [comment]
Yes this is a bug. Could you try and check out this branch: https://github.com/sphuber/aiida_core/tree/fix_3530_refactor_backend_manager
I think there the problem should be fixed and you can migrate.

**Comment by ltalirz** [comment]
Thanks a lot for the quick fix!

Now I get another error:
```
Traceback (most recent call last):
  File "/home/kdeeg/miniconda3/envs/aiida1/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kdeeg/miniconda3/envs/aiida1/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kdeeg/0_daniele/aiida_core/aiida/cmdline/commands/cmd_database.py", line 75, in database_migrate
    backend.migrate()
  File "/home/kdeeg/0_daniele/aiida_core/aiida/orm/implementation/django/backend.py", line 53, in migrate
    self._backend_manager.migrate()
  File "/home/kdeeg/0_daniele/aiida_core/aiida/backends/manager.py", line 140, in migrate
    if SCHEMA_GENERATION_VALUE != self.get_schema_generation_database():
  File "/home/kdeeg/0_daniele/aiida_core/aiida/backends/djsite/manager.py", line 77, in get_schema_generation_database
    return str(int(result[0][0]))
IndexError: list index out of range
```

**Comment by sphuber** [comment]
Can you try inserting `print(result)` in line 76 in `aiida_core/aiida/backends/djsite/manager.py`? If you can maybe come on slack so we can debug more easily.

**Comment by ltalirz** [comment]
`result` is an empty list

**Comment by ltalirz** [comment]
@asle85 has migrated the SSSP export files to AiiDA 1.0.

Migration worked fine but when she tried to import them, she got an error that looks related:
```
TASK [mc_aiida : import migrated export file SSSP.1_5.aiida for sssp] **************************************************************************************************************************************
fatal: [dev-aiida-dev]: FAILED! => changed=true
  cmd: |-
    TMPDIR=/home/ubuntu/aiida_profiles/home/ubuntu/.aiida/repository/sssp/archives /home/ubuntu/.virtualenvs/aiida/bin/verdi -p sssp import --non-interactive   "/home/ubuntu/aiida_profiles/home/ubuntu/.aiida/repository/sssp/archives/SSSP.1_5.aiida"
  delta: '0:00:05.036302'
  end: '2020-09-25 09:43:47.099485'
  msg: non-zero return code
  rc: 1
  start: '2020-09-25 09:43:42.063183'
  stderr: |-
    Traceback (most recent call last):
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
        return self.cursor.execute(sql)
    psycopg2.errors.UndefinedTable: relation "db_dbsetting" does not exist
    LINE 1: SELECT tval FROM db_dbsetting WHERE key = 'schema_generation...
                             ^
 
 
    The above exception was the direct cause of the following exception:
 
    Traceback (most recent call last):
      File "/home/ubuntu/aiida-core/aiida/backends/djsite/manager.py", line 90, in get_schema_generation_database
        result = backend.execute_raw(r"""SELECT tval FROM db_dbsetting WHERE key = 'schema_generation';""")
      File "/home/ubuntu/aiida-core/aiida/orm/implementation/django/backend.py", line 128, in execute_raw
        cursor.execute(query)
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
        return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
        return executor(sql, params, many, context)
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
        return self.cursor.execute(sql, params)
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
        raise dj_exc_value.with_traceback(traceback) from exc_value
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
        return self.cursor.execute(sql)
    django.db.utils.ProgrammingError: relation "db_dbsetting" does not exist
    LINE 1: SELECT tval FROM db_dbsetting WHERE key = 'schema_generation...
                             ^
 
 
    During handling of the above exception, another exception occurred:
 
    Traceback (most recent call last):
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
        return self.cursor.execute(sql)
    psycopg2.errors.UndefinedTable: relation "db_dbsetting" does not exist
    LINE 1: SELECT val FROM db_dbsetting WHERE key = 'schema_generation'...
                            ^
 
 
    The above exception was the direct cause of the following exception:
 
    Traceback (most recent call last):
      File "/home/ubuntu/.virtualenvs/aiida/bin/verdi", line 12, in <module>
        sys.exit(verdi())
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/home/ubuntu/aiida-core/aiida/cmdline/utils/decorators.py", line 61, in wrapper
        load_backend_if_not_loaded()
      File "/home/ubuntu/aiida-core/aiida/cmdline/utils/decorators.py", line 41, in load_backend_if_not_loaded
        get_manager().get_backend()
      File "/home/ubuntu/aiida-core/aiida/manage/manager.py", line 139, in get_backend
        self._load_backend()
      File "/home/ubuntu/aiida-core/aiida/manage/manager.py", line 90, in _load_backend
        manager.load_backend_environment(profile, validate_schema=schema_check)
      File "/home/ubuntu/aiida-core/aiida/backends/manager.py", line 119, in load_backend_environment
        self.validate_schema(profile)
      File "/home/ubuntu/aiida-core/aiida/backends/manager.py", line 230, in validate_schema
        self.validate_schema_generation(profile)
      File "/home/ubuntu/aiida-core/aiida/backends/manager.py", line 289, in validate_schema_generation
        schema_generation_database = self.get_schema_generation_database()
      File "/home/ubuntu/aiida-core/aiida/backends/djsite/manager.py", line 92, in get_schema_generation_database
        result = backend.execute_raw(r"""SELECT val FROM db_dbsetting WHERE key = 'schema_generation';""")
      File "/home/ubuntu/aiida-core/aiida/orm/implementation/django/backend.py", line 128, in execute_raw
        cursor.execute(query)
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
        return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
        return executor(sql, params, many, context)
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
        return self.cursor.execute(sql, params)
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
        raise dj_exc_value.with_traceback(traceback) from exc_value
      File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
        return self.cursor.execute(sql)
    django.db.utils.ProgrammingError: relation "db_dbsetting" does not exist
    LINE 1: SELECT val FROM db_dbsetting WHERE key = 'schema_generation'...
```

@sphuber any idea what could be the cause?

**Comment by sphuber** [comment]
This should not have anything to do with the archive, but simply a problem with the database schema. I think any `verdi` command that loads the backend will error. Check `verdi status --print-traceback` to confirm. If that fails, can she log into `psql` and run `select * from db_dbsetting;`. I think this will even fail, because the traceback suggest that the `db_dbsetting` table does not even exist. Which means something really bad happened. After you confirm or disconfirm this, we can continue the investigation

**Comment by ltalirz** [comment]
Thanks for the quick comment @sphuber, this helped track down the issue - indeed it stemmed from trying to import the export file into an empty database (no verdi setup had run).

Would it be possible to intercept such cases at an earlier point in the code and warn the user that the database is missing the AiiDA schema?
