### ISSUE TITLE
Improved input validation of `verdi computer setup`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3596]
It is currently possible for example to define a name with a space making it impossible to address it by the name in the CLI. This is unexpected behavior and leading/trailing whitespace should either be automatically trimmed or raise a validation error.

**Comment by greschd** [comment]
> 
> making it impossible to address it by the name in the CLI

Agree on the general point, but I think you can address it in the CLI either by quoting the string, or escaping the whitespace. I tried setting up a computer with label ``local host``, and both of these work:

```verdi computer configure local\ host```
```verdi computer configure 'local host'```

**Comment by pzarabadip** [comment]
Hi, we also had sort of similar issue before which is explained in #2974.

**Comment by dev-zero** [comment]
also, passing `!` as the `Mpirun command` as an attempt to setup a code without `mpirun` results in:

```
Mpirun command [mpirun -np {tot_num_mpiprocs}]: !
Default number of CPUs per machine: 4
Traceback (most recent call last):
  File "/home/tiziano/.local/share/virtualenvs/aiida/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/tiziano/.local/share/virtualenvs/aiida/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/tiziano/.local/share/virtualenvs/aiida/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/tiziano/.local/share/virtualenvs/aiida/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tiziano/.local/share/virtualenvs/aiida/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tiziano/.local/share/virtualenvs/aiida/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tiziano/.local/share/virtualenvs/aiida/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/tiziano/.local/share/virtualenvs/aiida/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tiziano/work/aiida/aiida_core/aiida/cmdline/utils/decorators.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/tiziano/work/aiida/aiida_core/aiida/cmdline/commands/cmd_computer.py", line 254, in computer_setup
    computer = computer_builder.new()
  File "/home/tiziano/work/aiida/aiida_core/aiida/cmdline/utils/decorators.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/tiziano/work/aiida/aiida_core/aiida/orm/utils/builders/computer.py", line 107, in new
    mpirun_command_internal = self._get_and_count('mpirun_command', used).strip().split(' ')
AttributeError: 'NoneType' object has no attribute 'strip'
```
