### ISSUE TITLE
verdi import from URL broken

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3610]
I believe this is due to the recent drop of python2 support and a switch in the url library used
```
$ verdi import https://github.com/aiidateam/aiida_core/files/2145695/test-db.tar.gz
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/types.py", line 530, in convert
    st = os.stat(rv)
FileNotFoundError: [Errno 2] No such file or directory: 'https://github.com/aiidateam/aiida_core/files/2145695/test-db.tar.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/cmdline/params/types/path.py", line 59, in convert
    return super().convert(value, param, ctx)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/types.py", line 537, in convert
    ), param, ctx)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/types.py", line 69, in fail
    raise BadParameter(message, ctx=ctx, param=param)
click.exceptions.BadParameter: Path "https://github.com/aiidateam/aiida_core/files/2145695/test-db.tar.gz" does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/cmdline/params/types/path.py", line 71, in checks_url
    urllib.request.urlopen(url, data=None, timeout=self.timeout_seconds)
AttributeError: module 'urllib' has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 1135, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 1469, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 1438, in full_process_value
    value = self.process_value(ctx, value)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 1428, in process_value
    return self.type_cast_value(ctx, value)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 1417, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 1416, in _convert
    return tuple(_convert(x, level - 1) for x in value or ())
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 1416, in <genexpr>
    return tuple(_convert(x, level - 1) for x in value or ())
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/core.py", line 1415, in _convert
    return self.type(value, self, ctx)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_rmq_py3/lib/python3.7/site-packages/click/types.py", line 39, in __call__
    return self.convert(value, param, ctx)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/cmdline/params/types/path.py", line 62, in convert
    return self.checks_url(value, param, ctx)
  File "/Users/leopold/Personal/Postdoc-MARVEL/repos/aiida/aiida_rmq/aiida/cmdline/params/types/path.py", line 72, in checks_url
    except (urllib.error.URLError, urllib.error.HTTPError, timeout):
AttributeError: module 'urllib' has no attribute 'error'
```

It also seems to mean that verdi import from url is currently untested.
Maybe we can use this to mock import from a url:
https://requests-mock.readthedocs.io/en/latest/mocker.html

I also notice that `requests` is imported here:
https://github.com/aiidateam/aiida-core/blob/0644e7d9ff492fdb2c94d608c575c697daee6d32/aiida/tools/dbimporters/plugins/materialsproject.py#L15
but is not a direct dependency of aiida-core. This should be fixed.

So, the question is: should we use requests or should we use urllib?
See e.g. https://stackoverflow.com/a/14804320/1069467

Mentioning @giovannipizzi @sphuber for comment

**Comment by ltalirz** [comment]
Hm... there were tests - but the import was broken on my machine and the PR fixed it (which now unearthed some pymatgen issues...).
I'll look into this tomorrow.

**Comment by CasperWA** [comment]
`requests` is fine, although using `urllib` will not add another dependency. But I think `requests` is a better package for this task.

There should be tests, yes. Pointing to specific commit sha's.

**Comment by CasperWA** [comment]
> Hm... it turns out there _were_ tests - but the import was broken on my machine and the PR fixed it (which now unearthed some pymatgen issues...).
> I'll look into this tomorrow.

This seems to be a general problem, not specific to your PR.

**Comment by ltalirz** [comment]
My apologies - I think this was due to a fluke on my system where I may have accidentally deleted some folders from my conda environments a couple of weeks back (so, my `urllib` of python3.7 does not have an `errors` submodule).
I think everything is fine on the aiida-core side (except for this import of `requests` mentioned above).

**Comment by ltalirz** [comment]
Just tested on @sponce24  machine and he had the same issue.

requests was installed in the correct (python 3.6.9) environment, with requests version 2.22.0
