### ISSUE TITLE
ModuleNotFoundError when using "verdi run" with script which has local import statement 

### ISSUE THREAD

**Issue by TsumiNa** [aiidateam/aiida-core#3624]
I'm following the tutorials. When I try to reproduce the section [run-a-simple-workflow](https://aiida-tutorials.readthedocs.io/en/latest/pages/2019_ISSP_Chiba_Japan/sections/workflows.html#run-a-simple-workflow). I got this issue.

Execute
```
verdi run simple_sync_workflow.py
```
will raise the error `ModuleNotFoundError: No module named 'create_rescale'`.

Following are the details:
```
Traceback (most recent call last):
  File "/home/liuchang/miniconda3/envs/aiida/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/home/liuchang/miniconda3/envs/aiida/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/liuchang/miniconda3/envs/aiida/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/liuchang/miniconda3/envs/aiida/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/liuchang/miniconda3/envs/aiida/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/liuchang/miniconda3/envs/aiida/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/liuchang/miniconda3/envs/aiida/lib/python3.7/site-packages/wrapt/wrappers.py", line 564, in __call__
    args, kwargs)
  File "/home/liuchang/miniconda3/envs/aiida/lib/python3.7/site-packages/aiida/cmdline/utils/decorators.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/liuchang/miniconda3/envs/aiida/lib/python3.7/site-packages/aiida/cmdline/commands/cmd_run.py", line 112, in run
    exec(compile(handle.read(), scriptname, 'exec', dont_inherit=True), globals_dict)  # yapf: disable # pylint: disable=exec-used
  File "simple_sync_workflow.py", line 11, in <module>
    from create_rescale import create_diamond_fcc, rescale
ModuleNotFoundError: No module named 'create_rescale'
```

This the screenshot of file `simple_sync_workflow.py`:
<img width="744" alt="截屏2019-12-10上午2 20 51" src="https://user-images.githubusercontent.com/6410921/70457683-e5066c80-1af3-11ea-8f4f-56228180807c.png">

and my file structure is:
<img width="676" alt="截屏2019-12-10上午2 18 13" src="https://user-images.githubusercontent.com/6410921/70457354-5a257200-1af3-11ea-8bc2-3a8d16488733.png">

**Comment by sphuber** [comment]
This is confirmed and I have opened a PR with a fix. Thanks for the report
