### ISSUE TITLE
Sessions not handled correctly in QB for asynchronous function calls

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3645]
I have found in my [`aiida-optimade`](https://github.com/aiidateam/aiida-optimade) REST API implementation exposing an AiiDA DB in the OPTiMaDe spec format that I get the [SQLA QueuePool error](https://docs.sqlalchemy.org/en/13/errors.html#queuepool-limit-of-size-x-overflow-y-reached-connection-timed-out-timeout-z) when making more than ~15 HTTP GET requests.

I have remedied this in my implementation by an AiiDA hack that creates a new DB session per request and closes it at the end.

It seems to me the native AiiDA REST API will have a similar problem for too many (concurrent) requests.

**Comment by CasperWA** [comment]
Using the branch [szoupanos/aiida_core:fix_issue_3645](https://github.com/szoupanos/aiida_core/tree/fix_issue_3645) I have created a test branch for `aiida-optimade` [here](https://github.com/CasperWA/aiida-optimade/tree/change_for_aiida-core_fix_3645).

Currently, my tests are failing with the error:

```shell
self = <sqlalchemy.pool.impl.QueuePool object at 0x7f77894c1d10>

    def _do_get(self):
        use_overflow = self._max_overflow > -1

        try:
            wait = use_overflow and self._overflow >= self._max_overflow
            return self._pool.get(wait, self._timeout)
        except sqla_queue.Empty:
            # don't do things inside of "except Empty", because when we say
            # we timed out or can't connect and raise, Python 3 tells
            # people the real error is queue.Empty which it isn't.
            pass
        if use_overflow and self._overflow >= self._max_overflow:
            if not wait:
                return self._do_get()
            else:
                raise exc.TimeoutError(
                    "QueuePool limit of size %d overflow %d reached, "
                    "connection timed out, timeout %d"
                    % (self.size(), self.overflow(), self._timeout),
>                   code="3o7r",
                )
E               sqlalchemy.exc.TimeoutError: QueuePool limit of size 2 overflow 1 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)
```

This fail occurs for a test that tries to iterate through the result pages until there are no more results returning under an entry resource endpoint.

After this, tests do not fail but raise a pytest error. In the output it reveals the same error as shown above, meaning a new session is not provided to the new requests, instead it seems to reuse the same session, where the QueuePool error has occurred and a time-out has been set.

**Comment by CasperWA** [comment]
I think the solution is a context manager I can invoke in a HTTP middleware function, wherein I can await the response handling?

**Comment by CasperWA** [comment]
After upping the QueuePool number in a recent commit, I am still getting the following error after several tests have run through fine:

```shell
Thread 140539476825856: Close_session_on_exit is True
Traceback (most recent call last):
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/fastapi/routing.py", line 129, in app
    raw_response = await run_in_threadpool(dependant.call, **values)
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/starlette/concurrency.py", line 25, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cwa/venv/aiida-core-optimade/aiida-optimade/aiida_optimade/routers/structures.py", line 44, in get_structures
    params=params,
  File "/home/cwa/venv/aiida-core-optimade/aiida-optimade/aiida_optimade/routers/utils.py", line 100, in get_entries
    ) = collection.find(params)
  File "/home/cwa/venv/aiida-core-optimade/aiida-optimade/aiida_optimade/entry_collections.py", line 160, in find
    self.set_data_returned(**criteria)
  File "/home/cwa/venv/aiida-core-optimade/aiida-optimade/aiida_optimade/entry_collections.py", line 142, in set_data_returned
    self._data_returned = self.count(**criteria)
  File "/home/cwa/venv/aiida-core-optimade/aiida-optimade/aiida_optimade/entry_collections.py", line 104, in count
    res = query.count()
  File "/home/cwa/venv/aiida-core-optimade/aiida-core/aiida/orm/querybuilder.py", line 2100, in count
    return self._impl.count(query)
  File "/home/cwa/venv/aiida-core-optimade/aiida-core/aiida/orm/implementation/sqlalchemy/querybuilder.py", line 437, in count
    return query.count()
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3630, in count
    return self.from_self(col).scalar()
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3355, in scalar
    ret = self.one()
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3325, in one
    ret = self.one_or_none()
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3294, in one_or_none
    ret = list(self)
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3389, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3404, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3382, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
    execution_options=execution_options,
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
    engine, execution_options
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 431, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2242, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/cwa/.virtualenvs/aiida-core-optimade/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 131, in _do_get
    code="3o7r",
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)
```

This seems to me that a new session is not provided per QB and/or it is not closed properly.

**Comment by szoupanos** [comment]
What I propose is to sit together to have a closer look at it

**Comment by CasperWA** [comment]
@giovannipizzi @szoupanos So I have found the least invasive solution: Reset the backend prior to any HTTP request, i.e., for each request the following happens:

1. `dispose` of the engine and set the global session to `None`
2. AiiDA will start a new global scoped session
3. Rinse and repeat

My concerns for this was that if something was still being processed for a scoped session that has now been left without a proper reference to it, then bad things may happen - I need to test this more - but if `async` is truly sequential (as stated by @sphuber), then it shouldn't matter in the end. The only problem is that the method to reset the backend does not actually _close_ the session. It just sets the global variable to `None`.

For the django backend, this is a simple matter of repeating the same thing for it's reset backend function, which doesn't do anything at the moment, i.e., it doesn't actually reset anything.
Furthermore, the special django `get_session()` method in the backend `QueryBuilder` should be set equal to the same method for its SQLA counter-part, I think.
