### ISSUE TITLE
Error when using local code: uses inexistent 'get_folder_list' method

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#3705]
When trying to run a local code, I get the following error:

```
+-> ERROR at 2019-12-29 16:25:26.778537+00:00
 | Traceback (most recent call last):
 |   File "/home/a-dogres/programming/aiida/aiida-core/aiida/engine/utils.py", line 172, in exponential_backoff_retry
 |     result = yield coro()
 |   File "/home/a-dogres/.virtualenvs/aiida/lib/python3.7/site-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/home/a-dogres/.virtualenvs/aiida/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/home/a-dogres/.virtualenvs/aiida/lib/python3.7/site-packages/tornado/gen.py", line 1069, in run
 |     yielded = self.gen.send(value)
 |   File "/home/a-dogres/programming/aiida/aiida-core/aiida/engine/processes/calcjobs/tasks.py", line 82, in do_upload
 |     execmanager.upload_calculation(node, transport, calc_info, folder)
 |   File "/home/a-dogres/programming/aiida/aiida-core/aiida/engine/daemon/execmanager.py", line 142, in upload_calculation
 |     for f in code.get_folder_list():
 | AttributeError: 'Code' object has no attribute 'get_folder_list'
```

This comes from https://github.com/aiidateam/aiida-core/blob/develop/aiida/engine/daemon/execmanager.py#L142, which appears to be the instance of ``get_folder_list`` in the AiiDA codebase. I think this using the old node <-> repository interface (which is now removed), and should be updated to use the new one.

**Comment by greschd** [comment]
Not sure if this means that all uses of local codes are currently broken - I was manually setting up the code, so there might have been other things wrong with it.

**Comment by sphuber** [comment]
Yes, this means that all `CalcJob` launches using local codes are broken. This tells us quite a bit how much local codes are being used :)

**Comment by greschd** [comment]
FWIW, I was only trying to use them for mocking codes 🤣
