### ISSUE TITLE
REST API crashes on classes that do not support certain methods

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4185]
### Describe the bug

When using the REST API, I get an exception that one of the plugins does not support a given method: `type object 'FleurinpModifier' has no attribute 'get_export_formats'`

### Expected behavior

This should instead gracefully ignore the error, since this just should mena that that class does not have export formats.

### Your environment

- Quantum Mobile RC 20.06.0 (AiiDA 1.2.1)

### Additional context

Error I get:
```
Error on request:
Traceback (most recent call last):
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/max/codes/aiida-core/aiida/restapi/resources.py", line 377, in get
    return self.utils.build_response(status=200, headers=headers, data=data)
  File "/home/max/codes/aiida-core/aiida/restapi/common/utils.py", line 438, in build_response
    response = jsonify(data)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/max/codes/aiida-core/aiida/restapi/common/utils.py", line 60, in default
    return JSONEncoder.default(self, o)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
127.0.0.1 - - [18/Jun/2020 15:52:36] "GET /api/v4/nodes/download_formats HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/max/codes/aiida-core/aiida/restapi/resources.py", line 290, in get
    results = self.trans.get_all_download_formats(full_type)
  File "/home/max/codes/aiida-core/aiida/restapi/translator/nodes/node.py", line 422, in get_all_download_formats
    node_cls.get_export_formats()
AttributeError: type object 'FleurinpModifier' has no attribute 'get_export_formats'
```

**Comment by sphuber** [comment]
If this is supposed to go in `1.3.0` which needs to be released early next week, who will take care of this one?

**Comment by sphuber** [comment]
@giovannipizzi does this crop up during the tutorial on the machine where we will run? Or given that this is triggered by an installed plugin, we won't have this problem? Id est, is this blocking for the `1.3.0` release?
