### ISSUE TITLE
Jenkins build started failing

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4342]
Builds on Jenkins started failing roughly since yesterday, [example](https://theossrv6.epfl.ch/jenkins/blue/organizations/jenkins/aiida_core_aiidateam/detail/develop/863/pipeline):
```
+ pip install --user '.[all]'
Processing /var/jenkins_home/workspace/iida_core_aiidateam_develop-RU3QBMA2T4T22WXTAWCIC67XUQPUWZ2VD4IVEUVDEEPJCLO4QU2Q
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 215, in prepare_linked_requirement
    finder, self.build_isolation,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/distributions/source.py", line 70, in prepare_distribution_metadata
    reqs = self.req.pep517_backend.get_requires_for_build_wheel()
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/wrappers.py", line 71, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/wrappers.py", line 162, in _call_hook
    raise BackendUnavailable
pip._vendor.pep517.wrappers.BackendUnavailable
WARNING: You are using pip version 19.2.3, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

This may very well have to do with `setuptools==0.50.0` that was [released yesterday](https://pypi.org/project/setuptools/).

**Comment by sphuber** [comment]
Tagging @csadorf

**Comment by greschd** [comment]
For the time being, I think it would be reasonable to put ``"setuptools>=40.8.0<50"`` in our ``pyproject.toml`` (haven't checked if this fixes the error).

The setuptools release appears to be broken for quite a large number of targets :dizzy_face:

**Comment by csadorf** [comment]
I see that you already created a PR, but should we maybe wait a day or so to see if this being fixed upstream?

**Comment by sphuber** [comment]
> I see that you already created a PR, but should we maybe wait a day or so to see if this being fixed upstream?

Fine by me to wait a day or two. Luckily we don't really rely heavily on the Jenkins build for problem detection, but it would be nice to get rid of all those red crosses in the build lists and branch/PR statuses
