### ISSUE TITLE
`CalcJob`: paramiko failing to change into working directory during submit because it does not exist

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4621]
@maxamsler reported that recently calculation jobs have been hitting the EBM because of the following exception:
```
+-> ERROR at 2020-11-30 22:42:46.748739+00:00
 | Traceback (most recent call last):
 |   File "/home/maxamsler/Homefolder/venv_python3_aiida/lib/python3.6/site-packages/paramiko/sftp_client.py", line 843, in _read_response
 |     t, data = self._read_packet()
 |   File "/home/maxamsler/Homefolder/venv_python3_aiida/lib/python3.6/site-packages/paramiko/sftp.py", line 201, in _read_packet
 |     x = self._read_all(4)
 |   File "/home/maxamsler/Homefolder/venv_python3_aiida/lib/python3.6/site-packages/paramiko/sftp.py", line 188, in _read_all
 |     raise EOFError()
 | EOFError
 | 
 | During handling of the above exception, another exception occurred:
 | 
 | Traceback (most recent call last):
 |   File "/home/maxamsler/Homefolder/Software/aiida-core/aiida/engine/utils.py", line 172, in exponential_backoff_retry
 |     result = yield coro()
 |   File "/home/maxamsler/Homefolder/venv_python3_aiida/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/home/maxamsler/Homefolder/venv_python3_aiida/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/home/maxamsler/Homefolder/venv_python3_aiida/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
 |     yielded = self.gen.send(value)
 |   File "/home/maxamsler/Homefolder/Software/aiida-core/aiida/engine/processes/calcjobs/tasks.py", line 136, in do_submit
 |     raise Return(execmanager.submit_calculation(node, transport))
 |   File "/home/maxamsler/Homefolder/Software/aiida-core/aiida/engine/daemon/execmanager.py", line 321, in submit_calculation
 |     job_id = scheduler.submit_from_script(workdir, submit_script_filename)
 |   File "/home/maxamsler/Homefolder/Software/aiida-core/aiida/schedulers/scheduler.py", line 389, in submit_from_script
 |     self.transport.chdir(working_directory)
 |   File "/home/maxamsler/Homefolder/Software/aiida-core/aiida/transports/plugins/ssh.py", line 507, in chdir
 |     self.sftp.chdir(path)
 |   File "/home/maxamsler/Homefolder/venv_python3_aiida/lib/python3.6/site-packages/paramiko/sftp_client.py", line 659, in chdir
 |     if not stat.S_ISDIR(self.stat(path).st_mode):
 |   File "/home/maxamsler/Homefolder/venv_python3_aiida/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
 |     t, msg = self._request(CMD_STAT, path)
 |   File "/home/maxamsler/Homefolder/venv_python3_aiida/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
 |     return self._read_response(num)
 |   File "/home/maxamsler/Homefolder/venv_python3_aiida/lib/python3.6/site-packages/paramiko/sftp_client.py", line 845, in _read_response
 |     raise SSHException("Server connection dropped: {}".format(e))
 | paramiko.ssh_exception.SSHException: Server connection dropped:
```
The problem seems to be that when the engine tries to change directory to the working directory in the submit step, it fails because apparently it doesn't exist. When checking on the remote it was confirmed that indeed these working directories did not exist. Weirdly enough the process report showed no indication of the upload step failing. The only possible explanation then is that the upload failed silently or somehow the successfully created folders were deleted before the submit started.

**Comment by sphuber** [comment]
@giovannipizzi we are still trying to determine whether this is a transient problem (it started recently and uploads to that machine were working fine before) but do you have an idea at a possible cause or something to look into so we can try and debug further?

**Comment by giovannipizzi** [comment]
This indeed seems very strange. Is this daint? Today I experienced very strange errors (but related to the scheduler: 
```
srun: Job 27487893 step creation temporarily disabled, retrying (Socket timed out on send/recv operation)
srun: Job 27487893 step creation still disabled, retrying (Requested nodes are busy)
srun: Job 27487893 step creation still disabled, retrying (Requested nodes are busy)
srun: Job 27487893 step creation still disabled, retrying (Requested nodes are busy)
srun: Job 27487893 step creation still disabled, retrying (Requested nodes are busy)
srun: Job 27487893 step creation still disabled, retrying (Requested nodes are busy)
...
```
Indeed, I never saw the folder go away (unless you wait weeks before submitting). This is really strange. Probably one could increase the paramiko logging (or add some prints/logging to the ssh transport) to see if the folders are being uploaded, but I was imagining/hoping that errors would result in a failed upload step. Strange also if the folder was deleted (unless the user run by mistake some `rm` command). Was the submit run right after the upload? Or a lot of time passed?
