### ISSUE TITLE
Engine: incorrect RabbitMQ connection parameters cause connection to fail

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4622]
On `develop`, which will be `v1.6.0` launching any process fails with following exception:
```
Traceback (most recent call last):
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
  File "/usr/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 173, in result
    raise exceptions.CancelledError
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/kiwipy/rmq/communicator.py", line 480, in task_send
    task_queue = await self.get_default_task_queue()
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/kiwipy/rmq/communicator.py", line 359, in get_default_task_queue
    await task_queue.connect()
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/kiwipy/rmq/tasks.py", line 436, in connect
    await self._subscriber.connect()
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/kiwipy/rmq/tasks.py", line 96, in connect
    await self._create_task_queue()
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/kiwipy/rmq/tasks.py", line 143, in _create_task_queue
    self._task_queue = await self._channel.declare_queue(
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/aio_pika/robust_channel.py", line 173, in declare_queue
    queue = await super().declare_queue(
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/aio_pika/channel.py", line 310, in declare_queue
    await queue.declare(timeout=timeout)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/aio_pika/queue.py", line 92, in declare
    self.declaration_result = await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/aiormq/channel.py", line 636, in queue_declare
    return await self.rpc(
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
aiormq.exceptions.ChannelPreconditionFailed: PRECONDITION_FAILED - inequivalent arg 'x-message-ttl' for queue 'aiida-4c272a87d7f543b08da9fe738d88bb13.process.queue' in vhost '/': received '72576000000' but current is '604800000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sph/.virtualenvs/aiida_dev/bin/aiida-quantumespresso", line 12, in <module>
    sys.exit(cmd_root())
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/wrapt/wrappers.py", line 563, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/home/sph/code/aiida/env/dev/aiida-core/aiida/cmdline/utils/decorators.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/sph/code/aiida/env/dev/aiida-quantumespresso/aiida_quantumespresso/cli/calculations/pw.py", line 128, in launch_calculation
    launch.launch_process(CalculationFactory('quantumespresso.pw'), daemon, **inputs)
  File "/home/sph/code/aiida/env/dev/aiida-quantumespresso/aiida_quantumespresso/cli/utils/launch.py", line 27, in launch_process
    node = launch.submit(process, **inputs)
  File "/home/sph/code/aiida/env/dev/aiida-core/aiida/engine/launch.py", line 121, in submit
    runner.controller.continue_process(process.pid, nowait=False, no_reply=True)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/plumpy/process_comms.py", line 369, in continue_process
    return self.task_send(message, no_reply=no_reply)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/plumpy/process_comms.py", line 436, in task_send
    return self._communicator.task_send(message, no_reply=no_reply)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/kiwipy/rmq/threadcomms.py", line 211, in task_send
    return self._loop_scheduler.await_(self._communicator.task_send(task, no_reply))
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/pytray/aiothreads.py", line 155, in await_
    return self.await_submit(awaitable).result(timeout=self.task_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/pytray/aiothreads.py", line 35, in done
    result = done_future.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/pytray/aiothreads.py", line 169, in proxy
    return await awaitable
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.8/site-packages/kiwipy/rmq/communicator.py", line 487, in task_send
    raise kiwipy.TaskRejected(str(exception))
kiwipy.exceptions.TaskRejected: PRECONDITION_FAILED - inequivalent arg 'x-message-ttl' for queue 'aiida-4c272a87d7f543b08da9fe738d88bb13.process.queue' in vhost '/': received '72576000000' but current is '604800000'
```
The reason is that the existing process queue (which is never deleted) has a different TTL setting for messages than the value that is being set when connecting to it when submitting a process. A safety mechanism in RabbitMQ prevents from changing these values on existing queues. This problem has happened before when we ourselves tried to change this value in `kiwipy` and so we reverted the change because it would break all existing installations.

However, this time around I am not aware of us having changed this value. It must have changed in the lower lying libraries then, i.e. `aio-pika` or `aiormq`. This wouldn't have been caught by tests because it will only crop up against an existing installation.

**Comment by sphuber** [comment]
The problem is that the [reverting commit](https://github.com/aiidateam/kiwipy/commit/7dc23c9675fd010d4e737032216a9c89522c2f84) was released in `kiwipy==0.5.5` but was never merged into `develop` so all other minor version after that suffer from this problem. This means we will have to release `v0.6.2` and `v0.7.1` with the same revert.
