### ISSUE TITLE
`jedi==0.18.0` is not compatible with `ipython==7.19.0`

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#4668]
### Describe the bug

The latest `jedi` release (`0.18.0`) seems to be incompatible with `ipython==7.19.0`. I first noticed this when tab-completion no longer worked in Jupyterlab, but it seems to be causing issues in the `verdi shell` as well:

```python
Python 3.7.9 (default, Aug 18 2020, 06:22:45) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from aiida.engine import calcfunction
   ...: @calcfunction
   ...: def multiply(x, y):
   ...:     return x * y
   ...: 

In [2]: z = multiply(Int(2), Int(3))
Traceback (most recent call last):
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 113, in get_completions
    yield from self._get_completions(body, offset, cursor_position, self.ipy_completer)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 129, in _get_completions
    for c in completions:
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/core/completer.py", line 438, in _deduplicate_completions
    completions = list(completions)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/core/completer.py", line 1862, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/core/completer.py", line 2030, in _complete
    cursor_pos, cursor_line, full_text)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/core/completer.py", line 1374, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/jedi/api/__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/.virtualenvs/dev-test/bin/verdi", line 12, in <module>
    sys.exit(verdi())
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/max/codes/aiida-core/aiida/cmdline/utils/decorators.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/max/codes/aiida-core/aiida/cmdline/commands/cmd_shell.py", line 46, in shell
    run_shell(interface=interface)
  File "/home/max/codes/aiida-core/aiida/cmdline/utils/shell.py", line 82, in run_shell
    curr_shell()
  File "/home/max/codes/aiida-core/aiida/cmdline/utils/shell.py", line 48, in ipython
    ipy_version()
  File "/home/max/codes/aiida-core/aiida/cmdline/utils/shell.py", line 146, in _ipython
    start_ipython(argv=[], user_ns=user_ns)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
    self.interact()
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 475, in prompt_for_code
    **self._extra_prompt_options())
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 826, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 792, in run_async
    return await _run_async2()
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 780, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 881, in cancel_and_wait_for_background_tasks
    await task
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/prompt_toolkit/buffer.py", line 1893, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/prompt_toolkit/buffer.py", line 1723, in async_completer
    document, complete_event
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/prompt_toolkit/completion/base.py", line 270, in get_completions_async
    document, complete_event
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/prompt_toolkit/completion/base.py", line 196, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/home/max/.virtualenvs/dev-test/lib/python3.7/site-packages/IPython/terminal/ptutils.py", line 116, in get_completions
    exc_type, exc_value, exc_tb = sys.exc_info()
NameError: name 'sys' is not defined

If you suspect this is an IPython 7.19.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

For more details, see [this issue](https://github.com/ipython/ipython/issues/12740) on the `ipython` GitHub repo.

### Steps to reproduce

1. `pip install` the `aiida-core` `develop` branch in a fresh environment.
2. The conflicting versions of `jedi` and `ipython` should now be installed:
```console
$ pip freeze | grep 'ipython\|jedi'
ipython==7.19.0
ipython-genutils==0.2.0
jedi==0.18.0
```
3. Open a `verdi shell`
4. Try to define a simple `calcfunction` and run it after trying to tab-complete the command:
```python
In [1]: from aiida.engine import calcfunction
   ...: @calcfunction
   ...: def multiply(x, y):
   ...:     return x * y
   ...: 

# Try to use tab-completion for `multiply` in the following command:
In [2]: z = multiply(Int(2), Int(3))
```

### Your environment

- Operating system [e.g. Linux]: Tested in Quantum Mobile version 20.11.2a
- Python version [e.g. 3.7.1]: 3.7.9
- aiida-core version [e.g. 1.2.1]: 1.5.2 _and_ `develop` branch

**Comment by mbercx** [comment]
A temporary fix is to install a previous version of `jedi`:

```
pip install jedi==0.17.2
```

@csadorf and @chrisjsewell  should we perhaps temporarily pin the `jedi` version until this issue is fixed for `ipython`?

**Comment by mbercx** [comment]
I just realized that this of course is also an issue for v1.5.2, and probably previous releases. So anyone that installs `aiida-core` or one of the plugins will most likely run into trouble when trying to use tab-completion in the `verdi shell`.

**Comment by csadorf** [comment]
> A temporary fix is to install a previous version of `jedi`:
> 
> ```
> pip install jedi==0.17.2
> ```
> 
> @csadorf and @chrisjsewell should we perhaps temporarily pin the `jedi` version until this issue is fixed for `ipython`?

@mbercx Has the issue been reported to jedi? I think they should fix that on their end, before we pin the version.

**Comment by greschd** [comment]
They know, this comment https://github.com/ipython/ipython/issues/12740#issuecomment-751273584 is by the main jedi dev.

**Comment by ltalirz** [comment]
ipython 7.20 is out https://discourse.jupyter.org/t/release-of-ipython-7-20/7752

**Comment by mbercx** [comment]
> ipython 7.20 is out https://discourse.jupyter.org/t/release-of-ipython-7-20/7752

Indeed, and it seems to have fixed the issue. Just created a fresh environment and no longer have any trouble using autocomplete in the `verdi` shell.

So, I'd say it's ok to close? Or should we perhaps still pin the versions to avoid issues in the future?

**Comment by ltalirz** [comment]
we should probably require this as a minimal ipython version then?

**Comment by csadorf** [comment]
> we should probably require this as a minimal ipython version then?

Yes, please don't close this issue. I'll likely increase the ipython minimal version in response to this issue.
