### ISSUE TITLE
Process excepts with TypeError: heap argument must be a list`

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4694]
### Describe the bug

Workchain excepted with  `TypeError: heap argument must be a list` - stacktrace in the report:
```
(aiida) ubuntu@qmobile:~/aiida-lsmo$ verdi process report 57355
2021-01-29 03:38:18 [29872 | REPORT]: [57355|Cp2kBaseWorkChain|run_process]: launching Cp2kCalculation<57356> iteration #1
2021-01-29 03:38:18 [29873 |  ERROR]: Traceback (most recent call last):
  File "/home/ubuntu/aiida-core/aiida/manage/external/rmq.py", line 201, in _continue
    result = yield super()._continue(communicator, pid, nowait, tag)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/plumpy/process_comms.py", line 547, in _continue
    yield proc.step_until_terminated()
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/plumpy/processes.py", line 1117, in step_until_terminated
    yield self.step()
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/plumpy/processes.py", line 1108, in step
    self.transition_to(next_state)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/plumpy/base/state_machine.py", line 318, in transition_to
    self.transition_failed(initial_state_label, label, *sys.exc_info()[1:])
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/plumpy/base/state_machine.py", line 332, in transition_failed
    raise exception.with_traceback(trace)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/plumpy/base/state_machine.py", line 302, in transition_to
    self._enter_next_state(new_state)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/plumpy/base/state_machine.py", line 363, in _enter_next_state
    self._fire_state_event(StateEventHook.ENTERING_STATE, next_state)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/plumpy/base/state_machine.py", line 281, in _fire_state_event
    callback(self, hook, state)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/plumpy/processes.py", line 310, in <lambda>
    state_machine.StateEventHook.ENTERING_STATE, lambda _s, _h, state: self.on_entering(state)
  File "/home/ubuntu/aiida-core/aiida/engine/processes/process.py", line 329, in on_entering
    super().on_entering(state)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/plumpy/processes.py", line 612, in on_entering
    call_with_super_check(self.on_wait, state.data)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/plumpy/base/utils.py", line 28, in call_with_super_check
    wrapped(*args, **kwargs)
  File "/home/ubuntu/aiida-core/aiida/engine/processes/workchains/workchain.py", line 260, in on_wait
    self.action_awaitables()
  File "/home/ubuntu/aiida-core/aiida/engine/processes/workchains/workchain.py", line 274, in action_awaitables
    self.runner.call_on_process_finish(awaitable.pk, callback)
  File "/home/ubuntu/aiida-core/aiida/engine/runners.py", line 312, in call_on_process_finish
    self._poll_process(node, functools.partial(inline_callback, event))
  File "/home/ubuntu/aiida-core/aiida/engine/runners.py", line 334, in _poll_process
    self._loop.call_later(self._poll_interval, self._poll_process, node, callback)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/tornado/ioloop.py", line 520, in call_later
    return self.call_at(self.time() + delay, callback, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/aiida/lib/python3.6/site-packages/tornado/ioloop.py", line 921, in call_at
    heapq.heappush(self._timeouts, timeout)
TypeError: heap argument must be a list

```

### Steps to reproduce

Don't know - may have been related to restarting the daemon

### Expected behavior

Looks like `self._timeouts` (the [heap argument](https://docs.python.org/3/library/heapq.html#heapq.heappush) ) was not a list, while it should have been

### Your environment
- Ubuntu 18.04
- python 3.6.9
- aiida-core 1.5.2, i.e. pre-asyncio

**Comment by ltalirz** [comment]
As the 1.6.0 release with asyncio is imminent, I think we won't spend extra time to fix this.
If anyone else encounters this issue and can't switch to 1.6 we can consider reopening
