### ISSUE TITLE
Cpaturing "background" asyncio exceptions in pytest

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4775]
As discussed in #4773, processes/workchains can raise "background" exceptions that will go unnoticed by pytest.

For example, with `tests/engine/test_work_chain.py::TestWorkChainAbortChildren::test_simple_kill_through_process` you can get the exception to manifest, with caveats:

1. you need to wait longer than the end of the process, because the exception is raised by later code, e.g.

```python
        async def run_async():
            await run_until_waiting(process)

            result = process.kill()
            if asyncio.isfuture(result):
                await result

            with self.assertRaises(plumpy.KilledError):
                await process.future()

			await asyncio.sleep(1)
```

but what do you wait for to make this consistent?

you could do something like this, but it seems hacky:

```python
        async def no_awaitables(process):
            while process._awaitables:
                await asyncio.sleep(0.1)

        async def run_async():
            await run_until_waiting(process)

            result = process.kill()
            if asyncio.isfuture(result):
                await result

            with self.assertRaises(plumpy.KilledError):
                await process.future()

            await asyncio.wait_for(no_awaitables(process), timeout=1.0)
```

2. pytest still does not actually fail if you do (1), you have to manually except the test, then you will see the excetion in the captured log:

```python
        self.assertEqual(process.node.is_killed, True)
    
>       raise
E       RuntimeError: No active exception to reraise

tests/engine/test_work_chain.py:1043: RuntimeError
------------------------------------------------------------------------------------------- Captured log call -------------------------------------------------------------------------------------------
ERROR    asyncio:base_events.py:1619 Task exception was never retrieved
future: <Task finished coro=<ProcessCallback.run() done, defined at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/events.py:99> exception=RuntimeError('Cannot transition from ProcessState.KILLED to ProcessState.EXCEPTED')>
Traceback (most recent call last):
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/events.py", line 103, in run
    await self._callback(*self._args, **self._kwargs)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/processes.py", line 548, in _run_task
    result = await coro(*args, **kwargs)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/utils.py", line 246, in wrap
    return coro_or_fn(*args, **kwargs)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/aiida/engine/processes/workchains/workchain.py", line 308, in on_process_finished
    self.resolve_awaitable(awaitable, value)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/aiida/engine/processes/workchains/workchain.py", line 173, in resolve_awaitable
    self._update_process_status()
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/aiida/engine/processes/workchains/workchain.py", line 192, in _update_process_status
    self.node.set_process_status(None)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/aiida/orm/nodes/process/process.py", line 202, in set_process_status
    self.delete_attribute(self.PROCESS_STATUS_KEY)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/aiida/orm/utils/mixins.py", line 193, in delete_attribute
    raise exceptions.ModificationNotAllowed('attributes of a sealed node are immutable')
aiida.common.exceptions.ModificationNotAllowed: attributes of a sealed node are immutable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/events.py", line 106, in run
    self._process.callback_excepted(self._callback, exc_info[1], exc_info[2])
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/processes.py", line 513, in callback_excepted
    self.fail(exception, trace)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/base/state_machine.py", line 97, in transition
    result = wrapped(self, *a, **kw)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/processes.py", line 1080, in fail
    self.transition_to(process_states.ProcessState.EXCEPTED, exception, trace_back)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/base/state_machine.py", line 335, in transition_to
    self.transition_failed(initial_state_label, label, *sys.exc_info()[1:])
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/base/state_machine.py", line 351, in transition_failed
    raise exception.with_traceback(trace)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/base/state_machine.py", line 317, in transition_to
    self._exit_current_state(new_state)
  File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/base/state_machine.py", line 376, in _exit_current_state
    raise RuntimeError('Cannot transition from {} to {}'.format(self._state.LABEL, next_state.label))
RuntimeError: Cannot transition from ProcessState.KILLED to ProcessState.EXCEPTED
```

how can you get pytest to fail on such (background) asyncio exceptions?

Note, you can intercept the exception by replacing the loops exception handler:

```python
        def _exception_handler(loop, context):
            print(context)

        runner.loop.set_exception_handler(_exception_handler)
        runner.schedule(process)
        runner.loop.run_until_complete(run_async())
```

but I have no idea how you can use this to actually make the test fail

I've tried googling answers, but could not find any obvious answers 😢

_Originally posted by @chrisjsewell in https://github.com/aiidateam/aiida-core/issues/4773#issuecomment-784951666_

**Comment by chrisjsewell** [comment]
cc'ing @unkcpz and @muhrin, if they have any thoughts?

**Comment by chrisjsewell** [comment]
Perhaps we should do something like `await asyncio.gather(*asyncio.all_tasks())` to ensure all pending task are complete (see https://stackoverflow.com/a/27910822/5033292), perhaps with a timeout.

A good example of asyncio "issues" is `tests/engine/test_work_chain.py`:

```
py37-django run-test: commands[0] | pytest tests/engine/test_work_chain.py
================================== test session starts ===================================
platform darwin -- Python 3.7.10, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py37-django/.pytest_cache
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/chrisjsewell/Documents/GitHub/aiida_core_develop, configfile: pyproject.toml
plugins: rerunfailures-9.1.1, cov-2.10.1, asyncio-0.14.0, benchmark-3.2.3, timeout-1.4.2
collected 43 items                                                                       

tests/engine/test_work_chain.py ......................................s....        [100%]

==================================== warnings summary ====================================
tests/engine/test_work_chain.py::TestWorkchain::test_run
tests/engine/test_work_chain.py::TestWorkchain::test_same_input_node
tests/engine/test_work_chain.py::TestWorkChainAbortChildren::test_simple_kill_through_process
  /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/base_events.py:626: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
    source=self)

tests/engine/test_work_chain.py::TestWorkchain::test_run
tests/engine/test_work_chain.py::TestWorkChainAbortChildren::test_simple_kill_through_process
  /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/base_events.py:612: RuntimeWarning: coroutine 'create_task.<locals>.run_task' was never awaited
    self._ready.clear()

tests/engine/test_work_chain.py::TestWorkchain::test_same_input_node
  /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/base_events.py:612: RuntimeWarning: coroutine 'create_task.<locals>.run_task' was never awaited
  Coroutine created at (most recent call last)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
      self.run_forever()
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/nest_asyncio.py", line 132, in _run_once
      handle._run()
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/nest_asyncio.py", line 201, in run
      ctx.run(self._callback, *self._args)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/nest_asyncio.py", line 159, in step
      step_orig(task, exc)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/tasks.py", line 249, in __step
      result = coro.send(None)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/kiwipy/rmq/communicator.py", line 232, in _on_broadcast
      msg[messages.BroadcastMessage.SUBJECT], msg[messages.BroadcastMessage.CORRELATION_ID]
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/kiwipy/rmq/utils.py", line 118, in wrap
      return coro_or_fn(*args, **kwargs)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/communications.py", line 73, in converted
      task_future = futures.create_task(msg_fn, loop)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py", line 76, in create_task
      asyncio.run_coroutine_threadsafe(run_task(), loop)
    self._ready.clear()

tests/engine/test_work_chain.py::TestWorkchain::test_same_input_node
  /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/sqlalchemy/sql/selectable.py:566: RuntimeWarning: coroutine 'create_task.<locals>.run_task' was never awaited
  Coroutine created at (most recent call last)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
      self.run_forever()
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
      self._run_once()
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/nest_asyncio.py", line 132, in _run_once
      handle._run()
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/nest_asyncio.py", line 201, in run
      ctx.run(self._callback, *self._args)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/nest_asyncio.py", line 159, in step
      step_orig(task, exc)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/tasks.py", line 249, in __step
      result = coro.send(None)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/kiwipy/rmq/communicator.py", line 232, in _on_broadcast
      msg[messages.BroadcastMessage.SUBJECT], msg[messages.BroadcastMessage.CORRELATION_ID]
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/kiwipy/rmq/utils.py", line 118, in wrap
      return coro_or_fn(*args, **kwargs)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/communications.py", line 73, in converted
      task_future = futures.create_task(msg_fn, loop)
    File "/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py", line 76, in create_task
      asyncio.run_coroutine_threadsafe(run_task(), loop)
    expanded_proxy_set = set(_expand_cloned(c.proxy_set))

tests/engine/test_work_chain.py::TestWorkChainAbortChildren::test_simple_kill_through_process
  /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/sqlalchemy/sql/base.py:619: RuntimeWarning: coroutine 'create_task.<locals>.run_task' was never awaited
    return col in set(self._all_columns)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================= 42 passed, 1 skipped, 8 warnings in 20.35s =======================
Task was destroyed but it is pending!
task: <Task pending coro=<ProcessCallback.run() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/events.py:99>>
/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/base_events.py:612: RuntimeWarning: coroutine 'ProcessCallback.run' was never awaited
  self._ready.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending coro=<Process.step_until_terminated() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/processes.py:1219> wait_for=<SavableFuture pending cb=[Task.__wakeup()]>>
sys:1: RuntimeWarning: coroutine 'create_task.<locals>.run_task' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
/Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/base_events.py:612: RuntimeWarning: coroutine 'create_task.<locals>.run_task' was never awaited
  self._ready.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<create_task.<locals>.run_task() running at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/site-packages/plumpy/futures.py:71> cb=[_chain_future.<locals>._call_set_state() at /Users/chrisjsewell/Documents/GitHub/aiida_core_develop/.tox/py37-django/lib/python3.7/asyncio/futures.py:358]>
```
