### ISSUE TITLE
Daemon processes not stopped when using a script as python executable

### ISSUE THREAD

**Issue by louisponet** [aiidateam/aiida-core#4806]
### Describe the bug

`verdi daemon stop` does not stop daemons. 

### Steps to reproduce

1. `cd` to directory with python exec 
2. Rename python exec to e.g. `python3.8_real`
3. create a bash script with name `python3.8` in the directory of the original executable:
```
#!/bin/bash
/dir/with/python/exec/python3.8_real $@
```
4. `chmod +x python3.8`
5. `verdi daemon start`
6. `verdi daemon stop`
7. check top/htop to find daemons are still there

### Expected behavior
Daemons are correctly killed

### Your environment

- Operating system [e.g. Linux]: Linux 3.10 centos 7
- Python version [e.g. 3.7.1]: 3.8.8
- aiida-core version [e.g. 1.2.1]: 1.5.2

**Comment by chrisjsewell** [comment]
Thanks @louisponet. That's certainly a use-case I have not seen before lol, out of interest why use a script as a python executable?
To debug though, do you see anything notable logged in the files in the `.aiida/daemon/log` folder?

**Comment by louisponet** [comment]
Long story short, I needed a non-statically compiled python to use with `pyjulia` (something to do with loading the symbols), so in conda I compiled my own, for which I needed some LD_LIBRARY_PATH.

I found this error:
```
03/12/2021 03:04:40 PM <9572> tornado.application: [ERROR] Exception in callback None
Traceback (most recent call last):
  File "/home/ponet/miniconda3/envs/aiida/lib/python3.8/site-packages/tornado/ioloop.py", line 887, in start
    fd_obj, handler_func = self._handlers[fd]
KeyError: 10
03/12/2021 03:04:43 PM <14390> tornado.application: [ERROR] Exception in callback None
Traceback (most recent call last):
  File "/home/ponet/miniconda3/envs/aiida/lib/python3.8/site-packages/tornado/ioloop.py", line 887, in start
    fd_obj, handler_func = self._handlers[fd]
KeyError: 10
Traceback (most recent call last):
  File "/home/ponet/miniconda3/envs/aiida_test/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/ponet/miniconda3/envs/aiida_test/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ponet/miniconda3/envs/aiida_test/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ponet/miniconda3/envs/aiida_test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ponet/miniconda3/envs/aiida_test/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ponet/miniconda3/envs/aiida_test/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ponet/miniconda3/envs/aiida_test/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ponet/miniconda3/envs/aiida_test/lib/python3.8/site-packages/aiida/cmdline/utils/decorators.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/ponet/miniconda3/envs/aiida_test/lib/python3.8/site-packages/aiida/cmdline/commands/cmd_devel.py", line 74, in devel_run_daemon
    start_daemon()
  File "/home/ponet/miniconda3/envs/aiida_test/lib/python3.8/site-packages/aiida/engine/daemon/runner.py", line 44, in start_daemon
    runner.start()
  File "/home/ponet/miniconda3/envs/aiida_test/lib/python3.8/site-packages/aiida/engine/runners.py", line 145, in start
    self._loop.start()
  File "/home/ponet/miniconda3/envs/aiida_test/lib/python3.8/site-packages/tornado/ioloop.py", line 863, in start
    event_pairs = self._impl.poll(poll_timeout)
OSError: [Errno 9] Bad file descriptor
```
