### ISSUE TITLE
(v1.6.3) Cannot kill process by using `verdi process kill`

### ISSUE THREAD

**Issue by hezhengda** [aiidateam/aiida-core#4909]
Dear aiida-core developers,

My aiida settings are:
* aiida-core (1.6.3)
* aio-pika (6.8.0)
* aiormq (3.3.1)
* rabbitmq (3.8.9)

When I try to use the lastest version of aiida-core (1.6.3), I have found a bug described below:

1. create a process (the process should be submitted to the cluster as usual, but it only said created, no upload and submit)
2. check `verdi process list`:
![image](https://user-images.githubusercontent.com/26743576/116992515-6e64a300-acd6-11eb-8fe7-8d85d2d50770.png)

3. If I want to delete pk=11396 (`verdi process kill 11396`)
4. I get this error:
```
Traceback (most recent call last):
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/z.he/.conda/envs/aiida/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aiida/cmdline/utils/decorators.py", line 74, in wrapper
    return wrapped(*args, **kwargs)
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aiida/cmdline/utils/decorators.py", line 149, in wrapper
    return wrapped(*args, **kwargs)
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aiida/cmdline/commands/cmd_process.py", line 186, in process_kill
    future = controller.kill_process(process.pk, msg='Killed through `verdi process kill`')
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/plumpy/process_comms.py", line 394, in kill_process
    return self._communicator.rpc_send(pid, message)
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/kiwipy/rmq/threadcomms.py", line 223, in rpc_send
    return self._loop_scheduler.await_(self._communicator.rpc_send(recipient_id, msg))
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/pytray/aiothreads.py", line 155, in await_
    return self.await_submit(awaitable).result(timeout=self.task_timeout)
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/pytray/aiothreads.py", line 35, in done
    result = done_future.result()
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/pytray/aiothreads.py", line 169, in proxy
    return await awaitable
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/kiwipy/rmq/communicator.py", line 480, in rpc_send
    publisher = await self.get_message_publisher()
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/kiwipy/rmq/communicator.py", line 414, in get_message_publisher
    await publisher.connect()
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/kiwipy/rmq/messages.py", line 170, in connect
    self._reply_queue = await self._channel.declare_queue(
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aio_pika/robust_channel.py", line 173, in declare_queue
    queue = await super().declare_queue(
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aio_pika/channel.py", line 325, in declare_queue
    await queue.declare(timeout=timeout)
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aio_pika/queue.py", line 92, in declare
    self.declaration_result = await asyncio.wait_for(
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aiormq/channel.py", line 703, in queue_declare
    return await self.rpc(
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/z.he/.conda/envs/aiida/lib/python3.8/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
aiormq.exceptions.ConnectionInternalError: INTERNAL_ERROR

```

Looking forward to the solution.
Best,
ZDH

**Comment by hezhengda** [comment]
Solve the issue. Just restart the rabbitmq server, then the issue will disappear.
