### ISSUE TITLE
AiiDA fails on concurrent sandbox creation

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4911]
This was reported by @chrisjsewell, see here:
https://github.com/aiidateam/aiida-core/issues/4899#issuecomment-830133804

The error message is:
```
04/30/2021 02:22:43 PM <1613> aiida.engine.transports: [ERROR] Exception whilst using transport:
Traceback (most recent call last):
  File "/root/aiida-core/aiida/engine/transports.py", line 110, in request_transport
    yield transport_request.future
  File "/root/aiida-core/aiida/engine/processes/calcjobs/tasks.py", line 82, in do_upload
    with SandboxFolder() as folder:
  File "/root/aiida-core/aiida/common/folders.py", line 421, in __init__
    os.makedirs(sandbox)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.aiida/repository/default/sandbox'

04/30/2021 02:22:43 PM <1613> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [ERROR] iteration 1 of do_upload excepted, retrying after 20 seconds
Traceback (most recent call last):
  File "/root/aiida-core/aiida/engine/utils.py", line 188, in exponential_backoff_retry
    result = await coro()
  File "/root/aiida-core/aiida/engine/processes/calcjobs/tasks.py", line 82, in do_upload
    with SandboxFolder() as folder:
  File "/root/aiida-core/aiida/common/folders.py", line 421, in __init__
    os.makedirs(sandbox)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.aiida/repository/default/sandbox'
```

This has been tested on AiiDA post-1.6.3, after the repository migration (even if a similar issue might have been there even before).

**Comment by giovannipizzi** [comment]
The solutions should be easy, see https://github.com/aiidateam/aiida-core/issues/4899#issuecomment-830860033

Just replace these two lines:
https://github.com/aiidateam/aiida-core/blob/944f61fd118738984f2465bfd5c31d4c556702a0/aiida/common/folders.py#L420-L421
with a single line:
```python
os.makedirs(sandbox, exists_ok=True)
```
(this is a concurrency issue, happening if the very first usage of AiiDA happens through more than one daemon: both will try at the same time to create the sandbox, the second will fail as it has been created by the first one).
