### ISSUE TITLE
CLI: logging exception in `verdi process list` through `aiida.common.utils.check_worker_load`

### ISSUE THREAD

**Issue by nkeilbart** [aiidateam/aiida-core#5144]
I am just seeing some small issues when I recently installed the develop branch. Everything appears to be working fine and gives positive responses for verdi status. I have some jobs running as well so it doesn't appear to affecting anything. When I type verdi process list I get the following reply:

PK    Created    Process label    Process State    Process status
----  ---------  ---------------  ---------------  ----------------

Total results: 0

Report: last time an entry changed state: 3h ago (at 17:34:15 on 2021-09-21)
--- Logging error ---
Traceback (most recent call last):
  File "/home/g12/keilbart/aiida-core/aiida/cmdline/utils/log.py", line 37, in emit
    msg = self.format(record)
  File "/g/g12/keilbart/miniconda3/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/home/g12/keilbart/aiida-core/aiida/cmdline/utils/log.py", line 60, in format
    return f'{click.style(record.levelname.capitalize(), fg=fg, bold=True)}: {record.msg % record.args}'
TypeError: not enough arguments for format string
Call stack:
  File "/home/g12/keilbart/aiida-core/aiidavenv/bin/verdi", line 12, in <module>
    sys.exit(verdi())
  File "/home/g12/keilbart/aiida-core/aiidavenv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/g12/keilbart/aiida-core/aiidavenv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/g12/keilbart/aiida-core/aiidavenv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/g12/keilbart/aiida-core/aiidavenv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/g12/keilbart/aiida-core/aiidavenv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/g12/keilbart/aiida-core/aiidavenv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/g12/keilbart/aiida-core/aiida/cmdline/utils/decorators.py", line 74, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/g12/keilbart/aiida-core/aiida/cmdline/commands/cmd_process.py", line 93, in process_list
    check_worker_load(worker_slot_use)
  File "/home/g12/keilbart/aiida-core/aiida/cmdline/utils/common.py", line 521, in check_worker_load
    echo.echo_report(f'Using {percent_load * 100:.0f}% of the available daemon worker slots')
  File "/home/g12/keilbart/aiida-core/aiida/cmdline/utils/echo.py", line 97, in echo_report
    CMDLINE_LOGGER.report(message, extra=dict(nl=nl, err=err, prefix=prefix))
  File "/home/g12/keilbart/aiida-core/aiida/common/log.py", line 29, in report
    self.log(LOG_LEVEL_REPORT, msg, *args, **kwargs)
  File "/g/g12/keilbart/miniconda3/lib/python3.8/logging/__init__.py", line 1500, in log
    self._log(level, msg, args, **kwargs)
  File "/g/g12/keilbart/miniconda3/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/g/g12/keilbart/miniconda3/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/g/g12/keilbart/miniconda3/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/g/g12/keilbart/miniconda3/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/home/g12/keilbart/aiida-core/aiida/cmdline/utils/log.py", line 40, in emit
    self.handleError(record)
Message: '\x1b[22mUsing 0% of the available daemon worker slots\x1b[0m'
Arguments: ()

It appears to be a simple formatting issue that is occuring. 

Other issues I have when installing is a enum error which can be fixed by uninstalling enum34 which appeared to be part of my python environment. 

I have this installed in a virtual environment using python3.8 and as mentioned using the develop branch. Please let me know if there is any other relevant information you might need.

**Comment by nkeilbart** [comment]
There in lies my issue. I seem to have mistakenly used the develop branch at some point and now I'm stuck with the upgraded version. I don't have control over my database but I could ask the people at the server to reset my account. I don't currently have anything worth saving on that particular database as of yet.

**Comment by sphuber** [comment]
I can confirm this bug that was recently introduced by the changed logging system in the CLI. I will make sure it gets fixed.
