### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#5146]
According to the Python 3.10 release schedule ([PEP 619](https://www.python.org/dev/peps/pep-0619/)), the second release candidate is scheduled to be released on 2021-09-07 with the final release on 2021-10-04. 

RC 2 is available for download: https://www.python.org/downloads/release/python-3100rc2/

I will track preparations to support Python 3.10 on this issue.

**Comment by dev-zero** [comment]
Found an issue in circus:

```
 verdi -p default daemon start-circus --foreground
{'controller': 'ipc:///var/folders/q_/hmjtsjld2d7csxq_lt8ttrtc0000gn/T/tmpjt1s9i80/circus.c.sock', 'pubsub_endpoint': 'ipc:///var/folders/q_/hmjtsjld2d7csxq_lt8ttrtc0000gn/T/tmpjt1s9i80/circus.p.sock', 'stats_endpoint': 'ipc:///var/folders/q_/hmjtsjld2d7csxq_lt8ttrtc0000gn/T/tmpjt1s9i80/circus.s.sock', 'logoutput': '-', 'loglevel': 'INFO', 'debug': False, 'statsd': True, 'pidfile': '/Users/tiziano/.aiida/daemon/circus-default.pid', 'watchers': [{'cmd': '/Users/tiziano/.local/share/virtualenvs/aiida/bin/verdi -p default devel run_daemon', 'name': 'aiida-default', 'numprocesses': 1, 'virtualenv': '/Users/tiziano/.local/share/virtualenvs/aiida', 'copy_env': True, 'stdout_stream': {'class': 'FileStream', 'filename': '/Users/tiziano/.aiida/daemon/log/aiida-default.log'}, 'stderr_stream': {'class': 'FileStream', 'filename': '/Users/tiziano/.aiida/daemon/log/aiida-default.log'}, 'env': {'COLORTERM': 'truecolor', 'COMMAND_MODE': 'unix2003', 'DISPLAY': '/private/tmp/com.apple.launchd.giVx114fDg/org.xquartz:0', 'HOME': '/Users/tiziano', 'LIBGL_ALWAYS_SOFTWARE': 'true', 'LOGNAME': 'tiziano', 'LaunchInstanceID': '36459028-8E95-4685-8CFC-AE243A18ADBC', 'PATH': '/Users/tiziano/.local/share/virtualenvs/aiida/bin:/Users/tiziano/.local/share/virtualenvs/aiida/bin:/usr/local/opt/postgresql@13/bin:/Users/tiziano/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin', 'SECURITYSESSIONID': '186a9', 'SHELL': '/bin/zsh', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.Kk0Ha54dN7/Listeners', 'TERM': 'xterm-256color', 'TERM_PROGRAM': 'WezTerm', 'TERM_PROGRAM_VERSION': '20211007-192622-8c347700', 'TMPDIR': '/var/folders/q_/hmjtsjld2d7csxq_lt8ttrtc0000gn/T/', 'USER': 'tiziano', 'WEZTERM_CONFIG_DIR': '/Users/tiziano/.config/wezterm', 'WEZTERM_CONFIG_FILE': '/Users/tiziano/.config/wezterm/wezterm.lua', 'WEZTERM_EXECUTABLE': '/Applications/WezTerm.app/Contents/MacOS/wezterm-gui', 'WEZTERM_EXECUTABLE_DIR': '/Applications/WezTerm.app/Contents/MacOS', 'WEZTERM_PANE': '14', 'WEZTERM_UNIX_SOCKET': '/Users/tiziano/.local/share/wezterm/gui-sock-11533', 'XPC_FLAGS': '0x0', 'XPC_SERVICE_NAME': '0', '__CFBundleIdentifier': 'com.github.wez.wezterm', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'SHLVL': '1', 'PWD': '/Users/tiziano/Projects/aiida', 'OLDPWD': '/Users/tiziano/Projects/aiida/aiida-diff', 'LANG': 'en_US.UTF-8', 'LC_COLLATE': 'C', 'PAGER': 'less', 'LESS': '-R', 'LSCOLORS':'Gxfxcxdxbxegedabagacad', 'FZF_DEFAULT_COMMAND': 'rg --files --hidden --glob "!.git/*"', '_VIRTUALENVWRAPPER_API': ' mkvirtualenv rmvirtualenv lsvirtualenv showvirtualenv workon add2virtualenv cdsitepackages cdvirtualenv lssitepackages toggleglobalsitepackages cpvirtualenv setvirtualenvproject mkproject cdproject mktmpenv wipeenv allvirtualenv', 'VIRTUALENVWRAPPER_SCRIPT': '/usr/local/bin/virtualenvwrapper.sh', 'WORKON_HOME': '/Users/tiziano/.local/share/virtualenvs', 'EDITOR': 'nvim', 'RIPGREP_CONFIG_PATH': '/Users/tiziano/.config/ripgreprc', 'LDFLAGS': '-L/usr/local/opt/postgresql@13/lib', 'CPPFLAGS': '-I/usr/local/opt/postgresql@13/include', 'PKG_CONFIG_PATH': '/usr/local/opt/postgresql@13/lib/pkgconfig', 'STARSHIP_SHELL': 'zsh', 'STARSHIP_SESSION_KEY': '3258421717290633', 'VIRTUALENVWRAPPER_PYTHON': '/usr/local/Cellar/virtualenvwrapper/4.8.4_1/libexec/bin/python', 'VIRTUALENVWRAPPER_PROJECT_FILENAME': '.project', 'VIRTUALENVWRAPPER_WORKON_CD': '1', 'VIRTUALENVWRAPPER_HOOK_DIR': '/Users/tiziano/.local/share/virtualenvs', 'VIRTUAL_ENV': '/Users/tiziano/.local/share/virtualenvs/aiida', '_': '/Users/tiziano/.local/share/virtualenvs/aiida/bin/verdi', 'AIIDA_PATH': '/Users/tiziano/.aiida', 'PYTHONUNBUFFERED': 'True'}}]}
Traceback (most recent call last):
  File "/Users/tiziano/.local/share/virtualenvs/aiida/bin/verdi", line 12, in <module>
    sys.exit(verdi())
  File "/Users/tiziano/.local/share/virtualenvs/aiida/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tiziano/.local/share/virtualenvs/aiida/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/tiziano/.local/share/virtualenvs/aiida/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tiziano/.local/share/virtualenvs/aiida/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tiziano/.local/share/virtualenvs/aiida/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tiziano/.local/share/virtualenvs/aiida/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tiziano/Projects/aiida/aiida-core/aiida/cmdline/utils/decorators.py", line 74, in wrapper
    return wrapped(*args, **kwargs)
  File "/Users/tiziano/Projects/aiida/aiida-core/aiida/cmdline/utils/decorators.py", line 177, in check_circus_zmq_version
    return wrapped(*args, **kwargs)
  File "/Users/tiziano/Projects/aiida/aiida-core/aiida/cmdline/commands/cmd_daemon.py", line 324, in start_circus
    arbiter = get_arbiter(**arbiter_config)
  File "/Users/tiziano/.local/share/virtualenvs/aiida/lib/python3.10/site-packages/circus/__init__.py", line 135, in __call__
    _watchers.append(Watcher.load_from_config(watcher))
  File "/Users/tiziano/.local/share/virtualenvs/aiida/lib/python3.10/site-packages/circus/watcher.py", line 407, in load_from_config
    w = cls(name=config.pop('name'), cmd=config.pop('cmd'), **config)
  File "/Users/tiziano/.local/share/virtualenvs/aiida/lib/python3.10/site-packages/circus/watcher.py", line 300, in __init__
    util.load_virtualenv(self, py_ver=virtualenv_py_ver)
  File "/Users/tiziano/.local/share/virtualenvs/aiida/lib/python3.10/site-packages/circus/util.py", line 874, in load_virtualenv
    raise ValueError("%s does not exist" % sitedir)
ValueError: /Users/tiziano/.local/share/virtualenvs/aiida/lib/python3.1/site-packages does not exist
```

I guess it's this part here in `circus/util.py` which starts to fail as soon as the minor version has 2 digits:

```
...
def load_virtualenv(watcher, py_ver=None):
    if not watcher.copy_env:
        raise ValueError('copy_env must be True to to use virtualenv')

    if not py_ver:
        py_ver = sys.version.split()[0][:3]
...
```
