### ISSUE TITLE
Caching: ph process failed if previous pw.x process finished_ok and cached but remote folder cleaned. 

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#5178]
- [ ] [AiiDA Troubleshooting Documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html)
- [ ] [AiiDA Users Forum](https://groups.google.com/forum/#!forum/aiidausers)

### Describe the bug

This problem happened when chain the `PwBaseWorkChain` and `PwBaseWorkChain` in a Workflow and using QE plugin with caching on for `aiida.calculations:quantumespresso.pw`. 
The `quantumespresso.ph` CalcJob require the remote folder of `quantumespresso.pw` run as input, but when it pw process finishes and remote folder is cleaned, the `quantumespresso.ph` will continues to fail since it can not found the saved files to do the calculation. 

### Steps to reproduce

This my workflow code to calculate the phonon frequencies, which do a SCF calculation and set the `scf_remote_folder` for next ph process step. 

```python
class PhononFrequenciesWorkChain(WorkChain):
    """WorkChain to calculate cohisive energy of input structure"""
    @classmethod
    def define(cls, spec):
    ....

    ....
    def inspect_scf(self):
        """inspect the result of scf calculation if fail do not continue."""
        workchain = self.ctx.workchain_scf

        if not workchain.is_finished_ok:
            self.report(
                f'PwBaseWorkChain failed with exit status {workchain.exit_status}'
            )
            return self.exit_codes.ERROR_SUB_PROCESS_FAILED_SCF

        try:
            self.ctx.scf_remote_folder = workchain.outputs.remote_folder
        except NotExistentAttributeError:
            return self.exit_codes.ERROR_NO_REMOTE_FOLDER

    def run_ph(self):
        """
        set the inputs and submit ph calculation to get quantities for phonon evaluation
        """
        inputs = {
            'metadata': {
                'call_link_label': 'PH'
            },
            'ph': {
                'code': self.inputs.ph_code,
                'qpoints': self.ctx.qpoints,
                'parameters': orm.Dict(dict=self.ctx.ph_parameters),
                'parent_folder': self.ctx.scf_remote_folder,
                'metadata': {
                    'options': self.ctx.options,
                },
                # CMDLINE setting for parallelization
            },
        }

        running = self.submit(PhBaseWorkflow, **inputs)
        self.report(f'Running ph calculation pk={running.pk}')
        return ToContext(workchain_ph=running)
```

### Expected behavior

The caching mechanism will also detect the remote folder, if it finds the required remote folder is cleaned, do not use the caching process but rerun the previous calculation.

### Your environment

- Operating system [e.g. Linux]:
- Python version [e.g. 3.7.1]:
- aiida-core version [e.g. 1.2.1]:

Other relevant software versions, e.g. Postres & RabbitMQ

**Comment by sphuber** [comment]
>  Every time we call clean() we change the input remote_folder hash so the process is not cached. The same code can be included in other operations which definitely modified the remote folder.

I think what you mean is that if the `remote_folder` output node of a `CalcJobNode` is cleaned, than it should change (probably simply remove, as that is what currently the unofficial way of invalidating a process node as a valid cache node) of the `CalcJobNode` and not the `RemoteData` node. When considering if a calculation should be cached from, only its *inputs* are taken into account, not its outputs. Or am I misunderstanding you?

**Comment by giovannipizzi** [comment]
I see. Question to discuss: is using the latest node always the 'right' thing to do? (Maybe yes, but happy to get feedback, e.g. from @greschd). Maybe this should be configurable? (I mean in 'verdi config', per profile, where maybe the default is 'pick the latest' but you have options to e.g. pick the oldest, if we think there's a usecase for that).

Otherwise, one other thing to do is to define a function to search for all nodes that have the same hash and remove the hash key for those that match certain rules (e.g.: remove the hash from all duplicates except the newest?) Or this could create problems (maybe we should do this only for CalcJob nodes and not for Data nodes?).

**Comment by unkcpz** [comment]
I just encounter another problem with caching that is a little different from the initial scenario I reported here in the first place. 
Now, my work chain which run PwCalculation and then PhCalculation is finished ok. I assume another run of the same workchain will all use the cached node and quickly finished without any problem. But the catch is even `CJ1 -> RemoteData -> CJ2` is finished I have another calculation `CJ1'` which is identical with `CJ1` but running standalone without the subsequent calculation `CJ2`. The second run of the workchain tries to use the `CJ1'` as the caching node which makes the workchain fail since I have already cleaned the remote folder of `CJ1'`. 

I think the "backtracking" may be the only way to solve this problem. But maybe we can have another level of 'process' just for caching purpose for the calculation like `PhCalculation` which always required a `remote_folder` as the input parameter. We hash this node also with the information of its previous step process identification like the inputs or just the hash of the previous PwCalculation? 

@sphuber This is the issue I mentioned in the aiida meeting, I look into it and find it is not the problem that `presubmit` will run even the node was cached. Sorry about the misleading.

In this case, it is confirmed that under the current implementation using the latest node for caching is not a good idea.

**Comment by sphuber** [comment]
Thanks for double-checking @unkcpz . Good to know that it isn't the case, because that would have been a bad bug.

Before looking into backtracking, I think the more direct and simple approach is still to simply actively mark a node that should no longer be used for caching using the `is_active_cache` property, which I added in 7cea5bebd15737cb7ae0f4f38dc4f8ca61935ae8. I know that this is not a perfect solution, because typically one will run into at least one failed calculation to figure out that a cache source should be marked as invalid, but I think the backtracking will be particularly complex to implement.

**Comment by unkcpz** [comment]
Thanks @sphuber. 
Do you think it is possible to implement a way to custom the hash for the `CalcJobNode`? In this case, it would be for the `PhCalculation` since the `parent_folder` always read from `remote_folder` of a `PwCalculation`. I customly hash the PhCaluclation node without using the `remote_folder` node but the define the hash my own way with using the hash of PwCalculation node?

**Comment by sphuber** [comment]
I am not sure I follow what you are trying to say @unkcpz . Even _if_ it was possible to change how the hash of the `PhCalculation` is computed, that won't solve your problem. The problem you have is that in a workchain that runs a `PwCalculation` and then a `PhCalculation`, when the `PwCalculation` is executed, it is taken from the cache, but the source is not a `PwCalculation` that was run in that work chain before, but some other one (whose remote folder happens to have been cleaned). The decision of AiiDA to take a particular caching source for this `PwCalculation` is based on the hash of the `PwCalculation` and is completely independent of the upcoming `PhCalculation`. So changing the hash of the `PhCalculation` won't change anything. If anything you need to change the hash of the _`PwCalculation`_

**Comment by greschd** [comment]
> use the hash of the previous PwCalculation step

In this case, aren't the two hashes of `PwCJ_1` and `PwCJ_1'` the same? The "safe" option discussed previously of ignoring any `PwCalculation` whose `RemoteFolder` output no longer exists in caching should still work here -- but this obviously means that we will re-do the work even if the `PhCalculation` could _also_ be cached.

**Comment by unkcpz** [comment]
Thanks for the comment! @greschd 

> In this case, aren't the two hashes of PwCJ_1 and PwCJ_1' the same?

Yes, those are the same, this is why I think we can use the hash of PwCalculation to make a hash of PhCalculation rather than use `remote_folder` which will differ. 

> but this obviously means that we will re-do the work even if the PhCalculation could also be cached.

I do not quite understand what you mean here.

**Comment by sphuber** [comment]
I see the problem now. It seems indeed that the hash of the remote folder of the `PwCalculation` is different in both runs and so the `PhCalculation` is not hit in the cache. The reason is because of the `_get_objects_to_hash`:
```python
    def _get_objects_to_hash(self) -> List[Any]:
        """Return a list of objects which should be included in the hash."""
        assert self._repository is not None, 'repository not initialised'
        top_level_module = self.__module__.split('.', 1)[0]
        try:
            version = importlib.import_module(top_level_module).__version__  # type: ignore[attr-defined]
        except (ImportError, AttributeError) as exc:
            raise exceptions.HashingError("The node's package version could not be determined") from exc
        objects = [
            version,
            {
                key: val
                for key, val in self.attributes_items()
                if key not in self._hash_ignored_attributes and key not in self._updatable_attributes  # pylint: disable=unsupported-membership-test
            },
            self._repository.hash(),
            self.computer.uuid if self.computer is not None else None
        ]
        return objects
```
For a `RemoteData` node, this returns something like:
```
['2.0.0a1',
 {'remote_path': '/home/sph/.scratch/f0/83/18fe-de81-449f-9e50-f98287b5f695'},
 '076c4a75b0e7f3de89d0f21d3c4fad9c09fb83054f8e6c467b875095d93fd154',
 '6a3e7df5-79a9-45f3-ad4b-a25e08af92b2']
```
The last hash is that of the computer and should be the same if the calculation is run on the same machine (that makes sense). The one just before it is the hash of the repository contents, but that will be empty, because it is the _local_ repository content, which is empty by definition for a `RemoteData`. Then there is the `remote_path` attribute and this is where the problem lies. This is going to be different for `remote_folder_0` and `remote_folder_1`.  Maybe we should simply remove this from the hash for `RemoteData` nodes?

I am trying to see if there are cases where we _should_ actually include it because it should mean that the hash of the associated calcjob node is different if it was run in a different folder.

**Comment by sphuber** [comment]
_If_ we decide that it should not be included, the fix is easy. We simply add
```python
_hash_ignored_attributes = ('remote_path',)
```
to the `RemoteData` class.

**Comment by greschd** [comment]
I don't think we can change this globally. In essence, it would make all `RemoteData` hash to the same value, which produces false positives in the caching.

The behavior you're seeing here isn't _completely_ unique to `RemoteData`, either: If there are two calcjobs with identical hash, which one is picked is essentially random. Of course, the _outputs_ of these two calcjobs (if they weren't cache clones of each other) will differ, however slightly -- and hash to different values.

Because "regular" outputs cannot become invalid, this is less of a problem. But one could still imagine a scenario where one "branch" of calculations has a lot of downstream calculations already executed, while another has yet to perform these same calculations.
Of course, it's more serious in the `RemoteData` case because the calculation will _fail_, instead of just having to re-do the work.

**Comment by sphuber** [comment]
> I don't think we can change this globally. In essence, it would make all RemoteData hash to the same value, which produces false positives in the caching.

Well, only those that were run on the same computer. But sure, I take your point. I guess that shows indeed that there is a good reason that we include the remote path. I now see @unkcpz 's point, that looking at the `RemoteData` the caching misses the hit, even though the associated `PwCalculation` would have had identical inputs and so would have matched. Still I am not sure if we can solve this by simply including the hash of the creator of a `RemoteData` that is used as input, because I think this merely kicks the can down the road. Because that creator may _itself_ have a `RemoteData` as input and so _its_ hash needs to consider the hash of its creator and so forth. There may very well be an end to this recursion, but I am not sure how feasible it is to implement and how reliable it would be. Also, there could be the possibility that a calculation has more than one `RemoteData` as inputs (currently probably not very common, but nothing stopping that from happening in theory). This would become quite complicated very quickly.

>  Of course, the outputs of these two calcjobs (if they weren't cache clones of each other) will differ, however slightly -- and hash to different values.

Is this a guarantee, or just something that is likely? That is to say, we cannot _assume_ that the hashes of the outputs will be identical if the hashes of the calculations themselves are identical. What exactly in the outputs would be guaranteed to be different, even if "ever so slightly"?

> In either case, this situation will not arise if caching is always turned on.

This I don't follow. In @unkcpz examples caching _is_ turned on, but it clearly shows the problem. If the "wrong" node is taken as the source for the cache hit, the next calculation may not exist in the cache, whereas if another node would have been selected as source (randomly) it may well have existed.

**Comment by greschd** [comment]
> Is this a guarantee, or just something that is likely? That is to say, we cannot assume that the hashes of the outputs will be identical if the hashes of the calculations themselves are identical. What exactly in the outputs would be guaranteed to be different, even if "ever so slightly"?

You're right, that's not a guarantee -- but very likely unless one is careful that the calculation is bit-wise reproducible.

> In @unkcpz examples caching is turned on, but it clearly shows the problem.

Ah, you're right. I was thinking if caching is turned on there _can't_ be two nodes with the same hash, otherwise they would be cache clones. But if they were run simultaneously, that is not the case.

**Comment by sphuber** [comment]
> Ah, you're right. I was thinking if caching is turned on there can't be two nodes with the same hash, otherwise they would be cache clones. But if they were run simultaneously, that can still happen.

Ah I see now what you mean. It might indeed very well have been possible that for the individual and isolated `PwCalculation` (the one that wasn't run as part of the work chain) he turned off caching, or simply didn't enable it. Still this is a very likely scenario so poses a real problem.

**Comment by greschd** [comment]
Right, but in the grand scheme of things I am _more_ worried about the fact that the subsequent calculation _fails_, and _less_ about the fact that it might have to re-run if we implement any of the strategies discussed previously.

**Comment by unkcpz** [comment]
Thanks for the discussion @sphuber @greschd !! I am so happy you got my point and looks we are on the same page now. 

> But if they were run simultaneously, that can still happen.

That's true, I turn on the caching from the first place and the case happened because two same inputs calculations run simultaneously. 

> I don't think we can change this globally. In essence, it would make all RemoteData hash to the same value, which produces false positives in the caching.

I agree with it. Hashing RemoteData with only computer seems overdoing and problematic. It makes no sense that two RemoteData objects will be the same only if they are produced on the same computer. 

> Still I am not sure if we can solve this by simply including the hash of the creator of a RemoteData that is used as input, because I think this merely kicks the can down the road. Because that creator may itself have a RemoteData as input and so its hash needs to consider the hash of its creator and so forth. There may very well be an end to this recursion, but I am not sure how feasible it is to implement and how reliable it would be. Also, there could be the possibility that a calculation has more than one RemoteData as inputs (currently probably not very common, but nothing stopping that from happening in theory). This would become quite complicated very quickly.

Let me try to kick the can farther away. Since we find the problem is caused by the hash of RemoteData. I think instead of including the hash of the creator of a RemoteData to hash the PhCalculation, can we hash the RemoteData with the hash of its creator? It makes sense that the RemoteData is always created by some CalcJob, so the creator of the RemoteData can be a safe identifier to make hash.

**Comment by greschd** [comment]
> can we hash the RemoteData with the hash of its creator

I like the idea, but haven't thought deeply about it yet. Since @sphuber brought up the issue of multiple `RemoteData` from the same calculation, maybe it should also include the link name?

**Comment by sphuber** [comment]
> Since we find the problem is caused by the hash of RemoteData. I think instead of including the hash of the creator of a RemoteData to hash the PhCalculation, can we hash the RemoteData with the hash of its creator? It makes sense that the RemoteData is always created by some CalcJob, so the creator of the RemoteData can be a safe identifier bind to the RemeteData and make hash. Then even there are more than one RemoteData as inputs, we still can handle this situation.

Ok, I am trying to figure out whether this would solve your problem. To make discussion and thinking easier, I have created a sketch of the situation as I understand it:
![caching_problem](https://user-images.githubusercontent.com/6992332/146514431-c9634668-6a0d-43ca-8829-4a3a69c16d27.png)

We have `W1` that launches a `PwCalculation` (`Pw1`) which creates a `RemoteData` (`R1`), which is used as input for a `PhCalculation` (`Ph1`). Another `PwCalculation`  (`Pw2`) is run outside of a workchain with the same input `D1`. The hash of `Pw1` and `Pw2` are identical, but the hashes of their `RemoteData`, `R1` and `R2` are different. Now the user launches a new workchain `W1'` which uses the exact same inputs as `W1`. The  `PwCalculation` can now be cached from both `Pw1` and `Pw2` since their hashes are identical. Let's say that `Pw2` is chosen (by chance). This produces `RemoteData` (`R2'`) which has the same hash as `R2` since it is a clone. Now the workchain moves on to running the `PhCalculation`, but it won't find a cache source, because no `PhCalculation` has been run yet with `R2` as an input.

If this description is correct of the situation and problem that @unkcpz describes (please correct me if not the case), then I don't see how including the hash of the creator into the `RemoteData` will solve this issue. As long as you include the hash of the `RemoteData` itself, which is different for `R1` and `R2`, then `Ph2` will _never_ be cached from `Ph1`, even if its predecessor `Pw2'` has an analogue (`Pw1`) with the same hash.

**Comment by unkcpz** [comment]
This exactly what the situation is, thanks for the figure. But I am not talk about **including** the hash of creator but replace the path which used now in hashing the RemoteData.

**Comment by sphuber** [comment]
I see now. Yes I think that would solve this particular case, but it is difficult to foresee if it might touch other pathways in a negative way. At least for now try adding the following to your `aiida-core` locally and see if it then fixes your problem:
```python
class RemoteData(data):

    def _get_objects_to_hash(self) -> List[Any]:
        from importlib import import_module

        creator = self.creator

        if creator is not None:
            return [
                creator.get_hash(),
                import_module(self.__module__.split('.', 1)[0]).__version__, 
                self.computer.uuid if self.computer is not None else None,
            ]
        
        return super()._get_objects_to_hash()
```

**Comment by ramirezfranciscof** [comment]
One thing I was thinking for a more generic way to deal with these, could maybe be to allow users to insert their own selection functions for the cached calcjobs. So I'm thinking, we could add a `calculation_selector` property to the `CalculationNode` which would take functions with the following signature, and that would default to the following:

```
def default_selector( iterable_of_candidates: Iterable[CalculationNode] ):
   return next(iter(iterable_of_candidates), None)
```

The the caching mechanism on the engine would (1) get the iterable of equivalent nodes, (2) run it through the `calculation_selector` (which can be set by the user to something different or default to the option above), and then use the result of that if it is not `None` or proceed with running the calculation if it is `None`.

Not sure if passing an `Iterable` would be enough for keeping the current performance for the default behavior, but if it is not we can be more specific and pass a querybuilder instance directly.

```
def default_selector( candidates_query: QueryBuilder ):
   return candidates_query.first()
```

**Comment by unkcpz** [comment]
I'll keep on adding a comment for the newly found caching issue mentioned in this morning's [aiida meeting](https://hackmd.io/BNrk9mHKRt2Yt0p3M3DmRg?view). 

When there are two processes running subsequently in a row, for example, I have run two processes `CalcJob_A` then `CalcJob_B`, `B` use the `RemoteData` of `A` as input. Assume `A` is finished ok and cached, `B` is not cached and will rerun. During the job submit phase, aiida will copy remote folder of `A` to a remote folder for `B`. However, the remote folder name of destination path (for `B`) is the same as previously running but not finished or cached `B`, it raises exception that 'directory exist and can't be override'. 

I am sure this issue happened but I only noticed recently that when the other two caching problems (in this issue report) are workaround and suppressed.

Hi @sphuber, what tool you used for drawing the flow sketch above? I think it will be more explainable if I can summarize all three caching issues with flow sketch diagrams respectively.

**Comment by sphuber** [comment]
> it raises exception that 'directory exist and can't be override'.

Can you please post the stacktrace

> Hi @sphuber, what tool you used for drawing the flow sketch above? I think it will be more explainable if I can summarize all three caching issues with flow sketch diagrams respectively.

It is just an svg that I made with Inkscape and then converted to png. There is no automated tooling

**Comment by unkcpz** [comment]
Hi @sphuber, here is the stacktrace of the issue. To reproduce this you can:

- Step 1: config caching setting that only pw is on but ph is off. 
- Step 2: running a workflow has pw calcjob and then ph calcjob.
- Step 3: running the workflow again the exception raised when doing the pw calculation.

```
    os.mkdir(os.path.join(self.curdir, path))                                                                                                                                                                                      [7/8479]
FileExistsError: [Errno 17] File exists: '/scratch/jyu/aiida_run/6c/64/9293-9c94-47c4-b862-0c0316653e9a'                                                                                                                                   
                                                                                                                                                                                                                                           
During handling of the above exception, another exception occurred:                                                                                                                                                                        
                                                                                                                                                                                                                                           
Traceback (most recent call last):                                                                                                                                                                                                         
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/aiida/engine/utils.py", line 188, in exponential_backoff_retry                                                                                                
    result = await coro()                                                                                                                                                                                                                  
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/aiida/engine/processes/calcjobs/tasks.py", line 89, in do_upload                                                                                              
    execmanager.upload_calculation(node, transport, calc_info, folder)                                                                                                                                                                     
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/aiida/engine/daemon/execmanager.py", line 156, in upload_calculation   

    result = await coro()                                                                                                                                                                                                          [0/8479]
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/aiida/engine/processes/calcjobs/tasks.py", line 89, in do_upload                                                                                              
    execmanager.upload_calculation(node, transport, calc_info, folder)                                                                                                                                                                     
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/aiida/engine/daemon/execmanager.py", line 156, in upload_calculation                                                                                          
    transport.copytree(path_existing, path_target)                                                                                                                                                                                         
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/aiida/transports/plugins/local.py", line 646, in copytree                                                                                                     
    shutil.copytree(the_source, the_destination, symlinks=not dereference)                                                                                                                                                                 
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/shutil.py", line 557, in copytree                                                                                                                                           
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,                                                                                                                                                                 
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/shutil.py", line 458, in _copytree                                                                                                                                          
    os.makedirs(dst, exist_ok=dirs_exist_ok)                                                                                                                                                                                               
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/os.py", line 225, in makedirs                                                                                                                                               
    mkdir(name, mode)                                                                                                                                                                                                                      
FileExistsError: [Errno 17] File exists: '/scratch/jyu/aiida_run/lost+found/6c649293-9c94-47c4-b862-0c0316653e9a/9293-9c94-47c4-b862-0c0316653e9a'                                                                                         
04/06/2022 12:48:40 PM <629816> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [WARNING] maximum attempts 5 of calling do_upload, exceeded                                                                                       
04/06/2022 12:48:40 PM <629816> aiida.engine.processes.calcjobs.tasks: [WARNING] uploading CalcJob<71057> failed   
```

**Comment by sphuber** [comment]
The message `tried to create path /scratch/jyu/aiida_run/6c/64/9293-9c94-47c4-b862-0c0316653e9a but it already exists` is just a warning and is not actually causing the exception. What you are hitting their is the safety check I added in the `upload_calculation` that checks if the run directory on the scratch folder of the computer already exist. As you can see this folder, `/scratch/jyu/aiida_run/6c/64/9293-9c94-47c4-b862-0c0316653e9a` in this case, contains the UUID of the `CalcJob`. This _should_ in principle guarantee that it is unique. However, there are some edge cases where it can already exist: for example when the `upload_calculation` is called but then interrupted without reaching the end (daemon shut down) and then when it restarts the daemon, it reexecutes the `upload_calculation` which will find the folder already exists. For safety it doesn't override it but moves it to the `lost+found` directory, as stated in the warning message.

The exception is actually caused later at line 225 (btw, what version are you running, because that is not the same in `develop`) and the problem is that the source files that is being copied no longer exists apparently. I can't say what could've happened here with more information, but please check that the `remote_folder` that is passed in the calculation and from which the content is copied, is still there and is not empty.

**Comment by unkcpz** [comment]
I am in version v1.6.5.

> The exception is actually caused later at line 225 

You are right, I check it and this is the initial issue of this thread and I forget to invalidate the pw caching of the CalcJob which has its remote folder cleaned and use it for Ph calculation.
