### ISSUE TITLE
Unable to delete computer - null value in column "dbcomputer_id" violates not-null constraint

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5396]
While looking into https://github.com/aiidateam/aiida-core/issues/5395 I noticed that I'm not able to delete a computer despite the fact that no nodes are associated with it:

```
In [26]: nodes=QueryBuilder().append(Node).all()

# no nodes left that are associated with a computer
In [27]: [n[0].computer for n in nodes]
Out[27]: [None, None, None, None]

# deleting computer still fails
In [28]: !verdi computer delete localhost
--- Logging error ---
Traceback (most recent call last):
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "dbcomputer_id" violates not-null constraint
DETAIL:  Failing row contains (1, 1, null, {}, {"safe_interval": 0.0, "use_login_shell": true}, t).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aiida/aiida-core/aiida/storage/psql_dos/orm/computers.py", line 130, in delete
    session.commit()
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    _emit_update_statements(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1000, in _emit_update_statements
    c = connection._execute_20(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/aiida/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "dbcomputer_id" violates not-null constraint
DETAIL:  Failing row contains (1, 1, null, {}, {"safe_interval": 0.0, "use_login_shell": true}, t).

[SQL: UPDATE db_dbauthinfo SET dbcomputer_id=%(dbcomputer_id)s WHERE db_dbauthinfo.id = %(db_dbauthinfo_id)s]
[parameters: {'dbcomputer_id': None, 'db_dbauthinfo_id': 1}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aiida/aiida-core/aiida/cmdline/commands/cmd_computer.py", line 550, in computer_delete
    orm.Computer.objects.delete(computer.id)
  File "/home/aiida/aiida-core/aiida/orm/computers.py", line 62, in delete
    return self._backend.computers.delete(pk)
  File "/home/aiida/aiida-core/aiida/storage/psql_dos/orm/computers.py", line 132, in delete
    raise exceptions.InvalidOperation(
aiida.common.exceptions.InvalidOperation: Unable to delete the requested computer: it is possible that there is at least one node using this computer (original message: (psycopg2.errors.NotNullViolation) null value in column "dbcomputer_id" violates not-null constraint
DETAIL:  Failing row contains (1, 1, null, {}, {"safe_interval": 0.0, "use_login_shell": true}, t).

[SQL: UPDATE db_dbauthinfo SET dbcomputer_id=%(dbcomputer_id)s WHERE db_dbauthinfo.id = %(db_dbauthinfo_id)s]
[parameters: {'dbcomputer_id': None, 'db_dbauthinfo_id': 1}]
(Background on this error at: https://sqlalche.me/e/14/gkpj))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aiida/aiida-core/aiida/cmdline/utils/log.py", line 37, in emit
    msg = self.format(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/home/aiida/aiida-core/aiida/cmdline/utils/log.py", line 60, in format
    return f'{click.style(record.levelname.capitalize(), fg=fg, bold=True)}: {record.msg % record.args}'
TypeError: format requires a mapping
Call stack:
  File "/opt/conda/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aiida/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/aiida/aiida-core/aiida/cmdline/utils/decorators.py", line 73, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/aiida/aiida-core/aiida/cmdline/commands/cmd_computer.py", line 552, in computer_delete
    echo.echo_critical(str(error))
  File "/home/aiida/aiida-core/aiida/cmdline/utils/echo.py", line 158, in echo_critical
    CMDLINE_LOGGER.critical(message, extra=dict(nl=nl, err=err, prefix=prefix))
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1493, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/opt/conda/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/home/aiida/aiida-core/aiida/cmdline/utils/log.py", line 40, in emit
    self.handleError(record)
Message: '\x1b[22mUnable to delete the requested computer: it is possible that there is at least one node using this computer (original message: (psycopg2.errors.NotNullViolation) null value in column "dbcomputer_id" violates not-null constraint\nDETAIL:  Failing row contains (1, 1, null, {}, {"safe_interval": 0.0, "use_login_shell": true}, t).\n\n[SQL: UPDATE db_dbauthinfo SET dbcomputer_id=%(dbcomputer_id)s WHERE db_dbauthinfo.id = %(db_dbauthinfo_id)s]\n[parameters: {\'dbcomputer_id\': None, \'db_dbauthinfo_id\': 1}]\n(Background on this error at: https://sqlalche.me/e/14/gkpj))\x1b[0m'
Arguments: ()

``` 

The issue seems to be that my computer row has "dbcomputer_id" null, which is not allowed.

This computer was created under aiida 2.0 (not migrated).
I'll try whether I can get a minimal reproduction of this issue.

**Comment by ltalirz** [comment]
I can reproduce this as follows:


```yaml
# computer.yaml
hostname: localhost
label: localhost2
description: AiiDAlab docker container
transport: core.local
scheduler: core.direct
work_dir: /home/{username}/aiida_run
```
```
verdi computer setup --config computer.yaml -n
verdi computer delete localhost
``` 

It seems like it is triggered by not providing a value for certain fields (that are missing in the `computer.yaml`) as the issue does not occur if I set the computer up interactively.

**Comment by chrisjsewell** [comment]
Note it's the authinfo's `dbcomputer_id` not the nodes.

I'm not sue how this can happen, since that field is non-nullable: https://github.com/aiidateam/aiida-core/blob/61b84e1eaf5bbe9e22ada33e9145315374c676e5/aiida/storage/psql_dos/models/authinfo.py#L37-L41

Perhaps something to do with the delete cascade or deferability

**Comment by chrisjsewell** [comment]
> I can reproduce this as follows

you are not configuring it here, so should there even be an authinfo created 🤔

**Comment by ltalirz** [comment]
Sorry, you're right, I was missing the
```
verdi computer configure core.local localhost3
```
step (which is indeed necessary to make it fail).

**Comment by chrisjsewell** [comment]
It seems it is deleting the computer, then trying to change the authinfo's `db_dbcomputer` to `null`, rather than actually deleting the authinfo

**Comment by ltalirz** [comment]
And indeed it happens for any computer that I configure, also if it is set up interactively.

**Comment by sphuber** [comment]
> I'm not sue how this can happen, since that field is non-nullable: 

But that is exactly the point no? When trying to delete the computer associated with an `AuthInfo` it will try to set `db_dbcomputer_id` to `null` which is not allowed.

**Comment by chrisjsewell** [comment]
I think the relationships may need to be also set with delete: https://docs.sqlalchemy.org/en/14/orm/cascades.html#delete

https://github.com/aiidateam/aiida-core/blob/61b84e1eaf5bbe9e22ada33e9145315374c676e5/aiida/storage/psql_dos/models/authinfo.py#L47-L48

**Comment by sphuber** [comment]
We should decide what should happen to `Node` and `AuthInfo` instances when their related `Computer` is deleted. If it is not acceptable to set the foreign key to null, then the only solution is to delete all associated nodes and authinfos before deleting the computer.

**Comment by chrisjsewell** [comment]
> If it is not acceptable to set the foreign key to null

For authinfo, it certainly makes no sense to have one with a `null` user or computer

**Comment by ltalirz** [comment]
For the `Node`-`Computer` relationship, I would perhaps allow the user to break it, just as the user is able to break the provenance if they explicitly desire to do so.

**Comment by chrisjsewell** [comment]
I imagine this is very relevant: https://docs.sqlalchemy.org/en/14/orm/cascades.html#using-foreign-key-on-delete-cascade-with-orm-relationships

**Comment by ltalirz** [comment]
Since you are the sqla experts, is one of you interested in taking this on?

I can give it a stab as well, it just might take a bit longer.

**Comment by chrisjsewell** [comment]
I think, for the authinfo, adding to `DbComputer` and `DbUser`:

```python
    authinfo = relationship(
        "DbAuthInfo", back_populates="aiidauser",  # / dbcomputer
        cascade="all, delete",
        passive_deletes=True
    )
```

should work

Should add some tests as well

**Comment by chrisjsewell** [comment]
Should double-check the other ORM relationships as well, there's not many:

```
11 results - 5 files

aiida/storage/psql_dos/models/authinfo.py:
  47:     aiidauser = relationship('DbUser', backref='authinfos')
  48:     dbcomputer = relationship('DbComputer', backref='authinfos')

aiida/storage/psql_dos/models/comment.py:
  45:     dbnode = relationship('DbNode', backref='dbcomments')
  46:     user = relationship('DbUser')

aiida/storage/psql_dos/models/group.py:
  66:     user = relationship('DbUser', backref=backref('dbgroups', cascade='merge'))
  67:     dbnodes = relationship('DbNode', secondary=table_groups_nodes, backref='dbgroups', lazy='dynamic')

aiida/storage/psql_dos/models/log.py:
  41:     dbnode = relationship('DbNode', backref=backref('dblogs', passive_deletes='all', cascade='merge'))

aiida/storage/psql_dos/models/node.py:
   72:     dbcomputer = relationship('DbComputer', backref=backref('dbnodes', passive_deletes='all', cascade='merge'))
   73:     user = relationship('DbUser', backref=backref(
  196:     input = relationship('DbNode', primaryjoin='DbLink.input_id == DbNode.id', overlaps='inputs_q,outputs_q')
  197:     output = relationship('DbNode', primaryjoin='DbLink.output_id == DbNode.id', overlaps='inputs_q,outputs_q')
```

**Comment by chrisjsewell** [comment]
> I think, for the authinfo, adding to DbComputer and DbUser:

I think you maybe can optionally just change the `DbAuthInfo` relationships:

```python
    aiidauser = relationship('DbUser', backref=backref('authinfos', passive_deletes=True, cascade="all, delete"))
    dbcomputer = relationship('DbComputer', backref=backref('authinfos', passive_deletes=True, cascade="all, delete"))
```

not sure what the best approach is

**Comment by ltalirz** [comment]
To me the more succinct 2nd solution looks better.
Are you planning to prepare a PR?

**Comment by chrisjsewell** [comment]
> Are you planning to prepare a PR?

I doubt I'll get round to it today, so feel free to give it a go
