### ISSUE TITLE
`the user cannot be None` when running test with `TemporaryProfileManager`

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#5511]
I encounter the following issue when running tests for the plugin `aiida-optimize` where the test has a fixture that opens a daemon and then submit process to the daemon (Is that right to do so using `subprocess.Popen` is there ready to use fixture for this? Or not recommend to test in this way?). The test and fixtures are:

```
@pytest.fixture
def with_daemon():
    """Starts the daemon process and then makes sure to kill it once the test is done."""
    import subprocess
    import sys

    from aiida.cmdline.utils.common import get_env_with_venv_bin
    from aiida.engine.daemon.client import DaemonClient

    # Add the current python path to the environment that will be used for the daemon sub process.
    # This is necessary to guarantee the daemon can also import all the classes that are defined
    # in this `tests` module.
    env = get_env_with_venv_bin()
    env['PYTHONPATH'] = ':'.join(sys.path)

    profile = get_profile()

    process = subprocess.Popen(
        DaemonClient(profile).cmd_string.split(),
        stderr=sys.stderr,
        stdout=sys.stdout,
        env=env,
    )

    yield
    
    process.terminate()
    


# @pytest.mark.usefixtures('aiida_profile_clean')
@pytest.fixture(params=[
    # 'run', 
    'submit',
])
def run_optimization(request, with_daemon, wait_for):  # pylint: disable=unused-argument
    """
    Checks an optimization engine with the given parameters.
    """
    def inner(engine, func_workchain, engine_kwargs, evaluate=None):  # pylint: disable=missing-docstring,useless-suppression
        inputs = dict(
            engine=engine,
            engine_kwargs=orm.Dict(dict=dict(engine_kwargs)),
            evaluate_process=func_workchain,
            evaluate=evaluate if evaluate is not None else {},
        )

        if request.param == 'run':
            _, result_node = run_get_node(OptimizationWorkChain, **inputs)
        else:
            assert request.param == 'submit'

            pk = submit(OptimizationWorkChain, **inputs).pk
            wait_for(pk)
            # time.sleep(6000)
            result_node = orm.load_node(pk)
            print(result_node.process_state)
        return result_node

    return inner
```

The error traceback is:
```
Report: [4|OptimizationWorkChain|on_except]: Traceback (most recent call last):
  File "/home/jyu/miniconda3/envs/opsp-ea/lib/python3.9/site-packages/plumpy/process_states.py", line 228, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/home/jyu/Projects/WP-OPSP/aiida-core/aiida/engine/processes/workchains/workchain.py", line 252, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/home/jyu/miniconda3/envs/opsp-ea/lib/python3.9/site-packages/plumpy/workchains.py", line 295, in step
    finished, result = self._child_stepper.step()
  File "/home/jyu/miniconda3/envs/opsp-ea/lib/python3.9/site-packages/plumpy/workchains.py", line 528, in step
    finished, result = self._child_stepper.step()
  File "/home/jyu/miniconda3/envs/opsp-ea/lib/python3.9/site-packages/plumpy/workchains.py", line 295, in step
    finished, result = self._child_stepper.step()
  File "/home/jyu/miniconda3/envs/opsp-ea/lib/python3.9/site-packages/plumpy/workchains.py", line 246, in step
    return True, self._fn(self._workchain)
  File "/home/jyu/miniconda3/envs/opsp-ea/lib/python3.9/site-packages/aiida_tools/_check_workchain_step.py", line 25, in inner
    raise e
  File "/home/jyu/miniconda3/envs/opsp-ea/lib/python3.9/site-packages/aiida_tools/_check_workchain_step.py", line 20, in inner
    return func(self, *args, **kwargs)
  File "/home/jyu/Projects/WP-OPSP/aiida-optimize/aiida_optimize/_optimization_workchain.py", line 120, in launch_evaluations
    for idx, inputs in opt.create_inputs().items():
  File "/home/jyu/Projects/WP-OPSP/aiida-optimize/aiida_optimize/engines/base.py", line 76, in create_inputs
    return self._result_mapping.add_inputs(self._create_inputs())
  File "/home/jyu/Projects/WP-OPSP/aiida-optimize/aiida_optimize/engines/_bisection.py", line 63, in _create_inputs
    return [{in_key: orm.Float(self.lower)
  File "/home/jyu/Projects/WP-OPSP/aiida-optimize/aiida_optimize/engines/_bisection.py", line 63, in <dictcomp>
    return [{in_key: orm.Float(self.lower)
  File "/home/jyu/Projects/WP-OPSP/aiida-core/aiida/orm/nodes/data/base.py", line 33, in __init__
    super().__init__(**kwargs)
  File "/home/jyu/Projects/WP-OPSP/aiida-core/aiida/orm/nodes/data/data.py", line 47, in __init__
    super().__init__(*args, **kwargs)
  File "/home/jyu/Projects/WP-OPSP/aiida-core/aiida/orm/nodes/node.py", line 189, in __init__
    raise ValueError('the user cannot be None')
ValueError: the user cannot be None
```

**Comment by unkcpz** [comment]
I had debugged a bit for this, and think it comes from the default user can be get (maybe not properly set for `TestManager`?). 
I can sure the user is there and when I change in https://github.com/aiidateam/aiida-core/blob/874c8dfe4ee6eab22a2f8fecf5b7984b6c9fa0c2/aiida/orm/nodes/node.py#L184 `user = user if user else User.collection(backend).get_default()` to `user = user if user else User.collection(backend).all()[0]`, the test pass without complain.

**Comment by unkcpz** [comment]
> If you use the new started_daemon_client fixture, this should no longer be a problem

@sphuber Sure! that's exactly the plan for the `aiida-optimize`. Thanks!
