### ISSUE TITLE
`archive create` failing with 'invalid value for `whence`'

### ISSUE THREAD

**Issue by eimrek** [aiidateam/aiida-core#5589]
### Describe the bug

I migrated a large aiida profile (`li-ion-conductors` on Materials Cloud) from aiida 1.6.5 to 2.0 using `verdi storage migrate`. The migration succeeded but there was a Warning. I am not sure if it's relevant, but i'm including it here for completeness:

```
Report: Migrating to the head of the legacy django branch
Report: - django_0045 -> django_0046
Warning: Detected repository folders that were missing the required subfolder `path` or `raw_input`. The paths of those nodes repository folders have been written to a log file: /home/ubuntu/aiida_profiles/home/ubuntu/.aiida/repository/li-ion-conductors/archives/migration-repository-missing-subfolder-3mfb1i2b.json
Warning: Migrated file repository to the new disk object store. The old repository has not been deleted out of safety and can be found at /home/ubuntu/.aiida/repository/li-ion-conductors/repository.
Report: - django_0046 -> django_0047
Report: - django_0047 -> django_0048
Report: - django_0048 -> django_0049
Report: - django_0049 -> django_0050
Report: Migrating to the head of the main branch
Success: migration completed
```

When using `verdi archive create`, it goes until around 90% and then this error occurrs:

```
Report: 
Archive Parameters
--------------------  -----------------------
Path                  li-ion-conductors.aiida
Version               main_0001
Compression           6

Inclusion rules
----------------------------  -----
Computers/Nodes/Groups/Users  All
Computer Authinfos            False
Node Comments                 True
Node Logs                     True

Report: Validating Nodes                                       
Report: Creating archive with:
-----------  -------
users              3
computers          4
groups             5
nodes        4505808
logs               1
links        4631147
group_nodes  4504481
-----------  -------
Traceback (most recent call last):                                           
  File "/home/ubuntu/Miniconda3-py39_4.9.2-Linux-x86_64/envs/aiida/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/home/ubuntu/Miniconda3-py39_4.9.2-Linux-x86_64/envs/aiida/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/Miniconda3-py39_4.9.2-Linux-x86_64/envs/aiida/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/Miniconda3-py39_4.9.2-Linux-x86_64/envs/aiida/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/Miniconda3-py39_4.9.2-Linux-x86_64/envs/aiida/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/Miniconda3-py39_4.9.2-Linux-x86_64/envs/aiida/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/Miniconda3-py39_4.9.2-Linux-x86_64/envs/aiida/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/aiida-core/aiida/cmdline/utils/decorators.py", line 73, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/aiida-core/aiida/cmdline/commands/cmd_archive.py", line 197, in create
    create_archive(entities, filename=output_file, archive_format=archive_format, **kwargs)
  File "/home/ubuntu/aiida-core/aiida/tools/archive/create.py", line 341, in create_archive
    _stream_repo_files(archive_format.key_format, writer, entity_ids[EntityTypes.NODE], backend, batch_size)
  File "/home/ubuntu/aiida-core/aiida/tools/archive/create.py", line 585, in _stream_repo_files
    writer.put_object(stream, key=key)
  File "/home/ubuntu/aiida-core/aiida/tools/archive/implementations/sqlite_zip/writer.py", line 186, in put_object
    self._stream_binary(f'{utils.REPO_FOLDER}/{key}', stream, buffer_size=buffer_size)
  File "/home/ubuntu/aiida-core/aiida/tools/archive/implementations/sqlite_zip/writer.py", line 171, in _stream_binary
    handle.seek(0, os.SEEK_END)
  File "/home/ubuntu/Miniconda3-py39_4.9.2-Linux-x86_64/envs/aiida/lib/python3.9/site-packages/disk_objectstore/utils.py", line 421, in seek
    raise NotImplementedError(
NotImplementedError: Invalid value for `whence`: only 0 and 1 are currently implemented.
```

I also ran `verdi storage maintain --full`, which succeeded, but the same error remained on archive creation.

### Your environment

- Operating system [e.g. Linux]: ubuntu 20.04
- Python version: 3.9.6
- aiida-core version: 2.0.1

**Comment by eimrek** [comment]
Here's the output of `verdi storage info --detailed`:

```
entities:
  Users:
    count: 3
    emails:
    - giovanni.pizzi@epfl.ch
    - info@materialscloud.org
    - leonid.kahle@epfl.ch
  Computers:
    count: 4
    labels:
    - daint_gpu
    - daint_mc
    - deneb
    - fidis
  Nodes:
    count: 4505808
    node_types:
    - data.core.array.ArrayData.
    - data.core.array.kpoints.KpointsData.
    - data.core.array.trajectory.TrajectoryData.
    - data.core.code.Code.
    - data.core.dict.Dict.
    - data.core.folder.FolderData.
    - data.core.int.Int.
    - data.core.remote.RemoteData.
    - data.core.structure.StructureData.
    - data.core.upf.UpfData.
    - process.calculation.calcfunction.CalcFunctionNode.
    - process.calculation.calcjob.CalcJobNode.
    process_types:
    - __main__.unpack_calcfunction
    - aiida.calculations:quantumespresso.pw
    - quantumespresso.flipper.FlipperCalculation
  Groups:
    count: 5
    type_strings:
    - core
    - core.import
  Comments:
    count: 0
  Logs:
    count: 1
  Links:
    count: 4631147
repository:
  SHA-hash algorithm: sha256
  Compression algorithm: zlib+1
  Packs: 6
  Objects:
    unpacked: 0
    packed: 195911
  Size (MB):
    unpacked: 0.0
    packed: 22010.268579483032
    other: 30.7734375
```
