### ISSUE TITLE
Catching workchain internal submit timeouts

### ISSUE THREAD

**Issue by janssenhenning** [aiidateam/aiida-core#5756]
### Is your feature request related to a problem? Please describe

At our institute we have an AiiDA installation on a jupyterhub server. This server performs a nightly backup
of it's filesystem. During this period the AiiDA daemon process can sometimes become unresponsive for a period leading to error messages
like below both for submitting new processes and workchains trying to submit new child calculations, which except the workchain
```
2022-11-11 02:17:17 [1469436 | REPORT]:     [2030618|FleurBaseWorkChain|on_except]: Traceback (most recent call last):
  File "/opt/aiida-kernel/lib/python3.8/site-packages/pytray/aiothreads.py", line 159, in await_
    return self.await_submit(awaitable).result(timeout=self.task_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 446, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/aiida-kernel/lib/python3.8/site-packages/plumpy/process_states.py", line 231, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/opt/aiida-core/aiida/engine/processes/workchains/workchain.py", line 214, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/opt/aiida-kernel/lib/python3.8/site-packages/plumpy/workchains.py", line 299, in step
    finished, result = self._child_stepper.step()
  File "/opt/aiida-kernel/lib/python3.8/site-packages/plumpy/workchains.py", line 532, in step
    finished, result = self._child_stepper.step()
  File "/opt/aiida-kernel/lib/python3.8/site-packages/plumpy/workchains.py", line 299, in step
    finished, result = self._child_stepper.step()
  File "/opt/aiida-kernel/lib/python3.8/site-packages/plumpy/workchains.py", line 250, in step
    return True, self._fn(self._workchain)
  File "/opt/aiida-core/aiida/engine/processes/workchains/restart.py", line 183, in run_process
    node = self.submit(self.process_class, **inputs)
  File "/opt/aiida-core/aiida/engine/processes/process.py", line 498, in submit
    return self.runner.submit(process, *args, **kwargs)
  File "/opt/aiida-core/aiida/engine/runners.py", line 197, in submit
    self.controller.continue_process(process_inited.pid, nowait=False, no_reply=True)
  File "/opt/aiida-kernel/lib/python3.8/site-packages/plumpy/process_comms.py", line 412, in continue_process
    return self.task_send(message, no_reply=no_reply)
  File "/opt/aiida-kernel/lib/python3.8/site-packages/plumpy/process_comms.py", line 485, in task_send
    return self._communicator.task_send(message, no_reply=no_reply)
  File "/opt/aiida-kernel/lib/python3.8/site-packages/kiwipy/rmq/threadcomms.py", line 243, in task_send
    return self._loop_scheduler.await_(self._communicator.task_send(task, no_reply))
  File "/opt/aiida-kernel/lib/python3.8/site-packages/pytray/aiothreads.py", line 163, in await_
    raise concurrent.futures.TimeoutError('{} after {} seconds'.format(
concurrent.futures._base.TimeoutError: task_send after 10 seconds
```
Since this can occur at any point, where a workchain submits processes, salvaging the failed calculations can become as complicated as you'd like

### Describe the solution you'd like

With this issue I would like to ask if it would be possible for the internal submits of workchains to have a retry mechanism as with transport tasks and putting the process on pause if it fails too often.

### Additional context

If it's helpful these are the versions we run on our infrastructure

AiiDA version: 1.6.9
Python Version: 3.8.10

**Comment by sphuber** [comment]
As just shortly discussed, this is feasible in principle, however, it is currently only implemented for `CalcJob`s and it is not clear how much time it would take to port it to `WorkChains`. However, I think this will not be a trivial feature to implement. But I agree that it makes a lot of sense to be able to deal with these transient problems.
