### ISSUE TITLE
Bug introduced from commit `d86017f` 

### ISSUE THREAD

**Issue by khsrali** [aiidateam/aiida-core#6507]
[src/aiida/brokers/rabbitmq/broker.py](https://github.com/aiidateam/aiida-core/commit/d86017f42cb5359d0272694247756d547057a663#diff-a084854da1088d050a36423b826e7e9ebd98702cf0b590410c294a6b88da96ec)

This line 
```python
        return parse(self.get_communicator().server_properties['version'].decode('utf-8'))
```
has changed to
```python
        return parse(self.get_communicator().server_properties['version'])

```

Which is giving me this error:

```
Traceback (most recent call last):
  File "/home/khosra_a/development/scripts/firecrest/how_to_run_pw_calculation_to_profile_firecrest/run_or_submit_add.py", line 42, in <module>
    do_some_aiida()
  File "/home/khosra_a/development/scripts/firecrest/how_to_run_pw_calculation_to_profile_firecrest/run_or_submit_add.py", line 38, in do_some_aiida
    engine.submit(builderREMO)
  File "/home/khosra_a/development/repo/aiida-core/src/aiida/engine/launch.py", line 113, in submit
    runner = manager.get_manager().get_runner()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khosra_a/development/repo/aiida-core/src/aiida/manage/manager.py", line 386, in get_runner
    self._runner = self.create_runner(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khosra_a/development/repo/aiida-core/src/aiida/manage/manager.py", line 425, in create_runner
    settings['communicator'] = self.get_communicator()
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khosra_a/development/repo/aiida-core/src/aiida/manage/manager.py", line 343, in get_communicator
    return broker.get_communicator()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khosra_a/development/repo/aiida-core/src/aiida/brokers/rabbitmq/broker.py", line 57, in get_communicator
    self.check_rabbitmq_version()
  File "/home/khosra_a/development/repo/aiida-core/src/aiida/brokers/rabbitmq/broker.py", line 86, in check_rabbitmq_version
    version = self.get_rabbitmq_version()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khosra_a/development/repo/aiida-core/src/aiida/brokers/rabbitmq/broker.py", line 125, in get_rabbitmq_version
    return parse(self.get_communicator().server_properties['version'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khosra_a/development/venv/aiida-firecrest/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/home/khosra_a/development/venv/aiida-firecrest/lib/python3.11/site-packages/packaging/version.py", line 196, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object
```

why `.decode('utf-8')` has removed?

**Comment by sphuber** [comment]
The underlying dependencies for RabbitMQ were updated. Please reinstall the package to update the packages and the problem should go away.

**Comment by khsrali** [comment]
thanks @sphuber and sorry for raising this, which wasn't a bug  :)
