### ISSUE TITLE
Failed to delete a profile

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#6531]
- `aiida-core==2.6.1`

I got following error when I try to delete a profile, not sure what happened.

```
❯ verdi profile delete 2024-07-daint
Warning: Do you also want to permanently delete all data? [y/N]: y
Warning: Deleting profile `2024-07-daint`, including all data.
Warning: This operation cannot be undone, are you sure you want to continue? [y/N]: y
sudo: a password is required

Unable to autodetect postgres setup.
Report: Deleted repository at `/home/jyu/project/sssp-project/.aiida/repository/2024-07-daint`.
Traceback (most recent call last):
  File "/home/jyu/.aiida_venvs/sssp-project/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jyu/project/sssp-project/aiida-core/src/aiida/cmdline/groups/verdi.py", line 117, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jyu/project/sssp-project/aiida-core/src/aiida/cmdline/commands/cmd_profile.py", line 268, in profile_delete
    get_config().delete_profile(profile.name, delete_storage=delete_data)
  File "/home/jyu/project/sssp-project/aiida-core/src/aiida/manage/configuration/config.py", line 584, in delete_profile
    storage.delete()
  File "/home/jyu/project/sssp-project/aiida-core/src/aiida/storage/psql_dos/backend.py", line 372, in delete
    if postgres.db_exists(config['database_name']):
  File "/home/jyu/project/sssp-project/aiida-core/src/aiida/manage/external/postgres.py", line 162, in db_exists
    return bool(self.execute(_CHECK_DB_EXISTS_COMMAND.format(dbname)))
  File "/home/jyu/.aiida_venvs/sssp-project/lib/python3.10/site-packages/pgsu/__init__.py", line 122, in execute
    raise ConnectionError(
ConnectionError: Could not connect to PostgreSQL server using dsn={dsn}.
Consider providing connection parameters via PGSU(dsn={...}).
```

**Comment by unkcpz** [comment]
Hi @sphuber, I try to implement a flag to allow disable the storage validation check in "File "/home/jyu/project/sssp-project/aiida-core/src/aiida/storage/psql_dos/backend.py", line 140" where the issue raised. But then I need to change all `__init__` method of backends, which is not idea I assume.
Can you give a suggestion which is best way to fix it? I comment out the `validate_storage` and it back to the first error I have ask me to input password but not actually wait me to do so.

**Comment by sphuber** [comment]
Yeah that is a tricky one. The design intentionally only allows a `StorageBackend` implementation to be instantiated if the storage is valid. I am not sure if we should start building in exceptions or workarounds to this principle.

I think we should leave that problem for now and simply change the deletion order of object-store and PSQL database. The former is very unlikely to fail compared to the latter. So if the former succeeds, we can be relatively sure that the object store deletion will also work (since it is just deleting a folder) and so the profile storage deletion should be "pseudo-atomic".

So I would for now just change that order and manually restore the container in your storage so the validation passes. You can then try to figure out why the PSQL connection fails.

**Comment by mbercx** [comment]
I also ran into this issue when trying to delete a profile because the database was still being accessed (see all steps execute below). Besides @sphuber's suggestion to swap the order of deleting the storage, I think we should also check if the daemon is running for that profile and stop it (with or without prompt).

@agoscinski I see you already flagged the issue as important, and I tend to agree. ^^ Now my profile needs to be deleted manually, which is a pain. And it's quite common to face this problem. I'm focussing on `aiida-quantumespresso` for now, but I'll flag and loop back to this one once I'm done there, my contract ends, or we face the heat death of the universe, whichever comes first.

<details><summary> All steps </summary>

```python
❯ verdi profile delete dev
Warning: Do you also want to permanently delete all data? [y/N]: y
Warning: Deleting profile `dev`, including all data.
Warning: This operation cannot be undone, are you sure you want to continue? [y/N]: y
Report: Deleted repository at `/Users/mbercx/project/qe/repositories/dev`.
Traceback (most recent call last):
  File "/Users/mbercx/.aiida_venvs/qe/bin/verdi", line 7, in <module>
    sys.exit(verdi())
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/cmdline/groups/verdi.py", line 119, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/cmdline/commands/cmd_profile.py", line 287, in profile_delete
    get_config().delete_profile(profile.name, delete_storage=delete_data)
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/manage/configuration/config.py", line 602, in delete_profile
    storage.delete()
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/storage/psql_dos/backend.py", line 374, in delete
    postgres.drop_db(config['database_name'])
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/manage/external/postgres.py", line 176, in drop_db
    self.execute(_DROP_DB_COMMAND.format(dbname))
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/pgsu/__init__.py", line 124, in execute
    return _execute_psyco(command, dsn)
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/pgsu/__init__.py", line 266, in _execute_psyco
    cursor.execute(command)
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.ObjectInUse: database "qe-dev" is being accessed by other users
DETAIL:  There are 3 other sessions using the database.
❯ verdi profile list
Report: configuration folder: /Users/mbercx/project/qe/.aiida
  clean
  dev
  new
* newer
  test
❯ verdi -p dev daemon stop
Profile: dev
Stopping the daemon... OK
❯ verdi profile delete dev
Warning: Do you also want to permanently delete all data? [y/N]: y
Warning: Deleting profile `dev`, including all data.
Warning: This operation cannot be undone, are you sure you want to continue? [y/N]: y
Traceback (most recent call last):
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/storage/psql_dos/migrator.py", line 192, in get_repository_uuid
    return self.get_container().container_id
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/disk_objectstore/container.py", line 433, in container_id
    return self._get_repository_config()['container_id']  # type: ignore[return-value]
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/disk_objectstore/container.py", line 394, in _get_repository_config
    raise NotInitialised('The container is not initialised yet - use .init_container() first')
disk_objectstore.exceptions.NotInitialised: The container is not initialised yet - use .init_container() first

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mbercx/.aiida_venvs/qe/bin/verdi", line 7, in <module>
    sys.exit(verdi())
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/cmdline/groups/verdi.py", line 119, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mbercx/.aiida_venvs/qe/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/cmdline/commands/cmd_profile.py", line 287, in profile_delete
    get_config().delete_profile(profile.name, delete_storage=delete_data)
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/manage/configuration/config.py", line 601, in delete_profile
    storage = storage_cls(profile)
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/storage/psql_dos/backend.py", line 141, in __init__
    migrator.validate_storage()
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/storage/psql_dos/migrator.py", line 162, in validate_storage
    repository_uuid = self.get_repository_uuid()
  File "/Users/mbercx/project/qe/git/aiida-core/src/aiida/storage/psql_dos/migrator.py", line 194, in get_repository_uuid
    raise exceptions.UnreachableStorage(
aiida.common.exceptions.UnreachableStorage: Could not access disk-objectstore <disk_objectstore.container.Container object at 0x14485fb20>: The container is not initialised yet - use .init_container() first
```

</details>
