### ISSUE TITLE
🐛 `OperationalError` during archive creation

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#6545]
When trying to create an archive:

```python
verdi archive create -G workchain/relax -- relax_workchains.aiida
```

I'm running into the following error 

```python
sqlalchemy.exc.OperationalError: (psycopg.OperationalError) sending query and params failed: number of parameters must be between 0 and 65535
[SQL: SELECT DISTINCT db_dbcomputer_1.id
FROM db_dbnode AS db_dbnode_1 JOIN db_dbcomputer AS db_dbcomputer_1 ON db_dbnode_1.dbcomputer_id = db_dbcomputer_1.id
```

<details><summary>Full Output + Traceback</summary>

```python
Report:
Archive Parameters
--------------------  ---------------------
Path                  relax_workchains.aiida
Version               main_0001
Compression           6

Inclusion rules
----------------------------  --------
Computers/Nodes/Groups/Users  Selected
Computer Authinfos            False
Node Comments                 True
Node Logs                     True

Traversal rules
---------------------------------  -----
Follow links input calc forwards   False
Follow links input calc backwards  True
Follow links create forwards       True
Follow links create backwards      True
Follow links return forwards       True
Follow links return backwards      False
Follow links input work forwards   False
Follow links input work backwards  True
Follow links call calc forwards    True
Follow links call calc backwards   True
Follow links call work forwards    True
Follow links call work backwards   True

Traceback (most recent call last):
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/psycopg/server_cursor.py", line 292, in execute
    raise ex.with_traceback(None)
psycopg.OperationalError: sending query and params failed: number of parameters must be between 0 and 65535

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mbercx/.aiida_venvs/mc3d/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mbercx/project/mc3d/git/aiida-core/src/aiida/cmdline/groups/verdi.py", line 117, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mbercx/project/mc3d/git/aiida-core/src/aiida/cmdline/utils/decorators.py", line 104, in wrapper
    return wrapped(*args, **kwargs)
  File "/Users/mbercx/project/mc3d/git/aiida-core/src/aiida/cmdline/commands/cmd_archive.py", line 220, in create
    create_archive(entities, filename=output_file, archive_format=archive_format, **kwargs)
  File "/Users/mbercx/project/mc3d/git/aiida-core/src/aiida/tools/archive/create.py", line 244, in create_archive
    group_nodes, link_data = _collect_required_entities(
  File "/Users/mbercx/project/mc3d/git/aiida-core/src/aiida/tools/archive/create.py", line 541, in _collect_required_entities
    entity_ids[EntityTypes.COMPUTER].update(
  File "/Users/mbercx/project/mc3d/git/aiida-core/src/aiida/tools/archive/create.py", line 541, in <genexpr>
    entity_ids[EntityTypes.COMPUTER].update(
  File "/Users/mbercx/project/mc3d/git/aiida-core/src/aiida/orm/querybuilder.py", line 1083, in iterall
    for item in self._impl.iterall(self.as_dict(), batch_size):
  File "/Users/mbercx/project/mc3d/git/aiida-core/src/aiida/storage/psql_dos/orm/querybuilder/main.py", line 210, in iterall
    for resultrow in session.execute(stmt):
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2351, in execute
    return self._execute_internal(
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2236, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/mbercx/.aiida_venvs/mc3d/lib/python3.10/site-packages/psycopg/server_cursor.py", line 292, in execute
    raise ex.with_traceback(None)
sqlalchemy.exc.OperationalError: (psycopg.OperationalError) sending query and params failed: number of parameters must be between 0 and 65535
[SQL: SELECT DISTINCT db_dbcomputer_1.id
FROM db_dbnode AS db_dbnode_1 JOIN db_dbcomputer AS db_dbcomputer_1 ON db_dbnode_1.dbcomputer_id = db_dbcomputer_1.id
```

</details>

System: macOS Ventura 13.4 (22F2063)
`aiida-core` version: `main` branch, installed locally.
Python version: 3.10.13

**Comment by giovannipizzi** [comment]
The issue is that we are probably generating a query that is very long, with something like 'id = 1 OR id = 2 OR id = 3 OR ....', with more than the max allowed paramerers. The output is truncated there? No closed square bracket? Not very helpful from the pat of SQLA :-) 
I'm guessing you have many nodes in the group, and the query that actually fails is not the one reported (maybe). Can you report how many nodes you have in the group workchain/relax? 
If the number is very large, can you try making a group with a subset of those nodes, and see if there is a threshold number of nodes for which the query stops working? (my guess is 65535 from the error message, but I'm not sure).

So we better understand if this is the problem, and can further debug.

**Comment by mbercx** [comment]
Thanks @giovannipizzi! In the end I did the export in two batches indeed. I should also note that I cut off the query, since the next line was a very long one, here is the `tail -n3` of the error (cut off the third last line again):

```
70)s::INTEGER, %(id_1_414471)s::INTEGER, %(id_1_414472)s::INTEGER, %(id_1_414473)s::INTEGER, %(id_1_414474)s::INTEGER, %(id_1_414475)s::INTEGER, %(id_1_414476)s::INTEGER, %(id_1_414477)s::INTEGER, %(id_1_414478)s::INTEGER, %(id_1_414479)s::INTEGER, %(id_1_414480)s::INTEGER, %(id_1_414481)s::INTEGER, %(id_1_414482)s::INTEGER, %(id_1_414483)s::INTEGER, %(id_1_414484)s::INTEGER, %(id_1_414485)s::INTEGER, %(id_1_414486)s::INTEGER, %(id_1_414487)s::INTEGER, %(id_1_414488)s::INTEGER, %(id_1_414489)s::INTEGER, %(id_1_414490)s::INTEGER, %(id_1_414491)s::INTEGER, %(id_1_414492)s::INTEGER, %(id_1_414493)s::INTEGER, %(id_1_414494)s::INTEGER, %(id_1_414495)s::INTEGER, %(id_1_414496)s::INTEGER, %(id_1_414497)s::INTEGER, %(id_1_414498)s::INTEGER, %(id_1_414499)s::INTEGER, %(id_1_414500)s::INTEGER, %(id_1_414501)s::INTEGER, %(id_1_414502)s::INTEGER, %(id_1_414503)s::INTEGER, %(id_1_414504)s::INTEGER, %(id_1_414505)s::INTEGER, %(id_1_414506)s::INTEGER, %(id_1_414507)s::INTEGER, %(id_1_414508)s::INTEGER, %(id_1_414509)s::INTEGER, %(id_1_414510)s::INTEGER, %(id_1_414511)s::INTEGER, %(id_1_414512)s::INTEGER, %(id_1_414513)s::INTEGER, %(id_1_414514)s::INTEGER, %(id_1_414515)s::INTEGER, %(id_1_414516)s::INTEGER, %(id_1_414517)s::INTEGER, %(id_1_414518)s::INTEGER, %(id_1_414519)s::INTEGER, %(id_1_414520)s::INTEGER, %(id_1_414521)s::INTEGER, %(id_1_414522)s::INTEGER, %(id_1_414523)s::INTEGER, %(id_1_414524)s::INTEGER, %(id_1_414525)s::INTEGER, %(id_1_414526)s::INTEGER, %(id_1_414527)s::INTEGER, %(id_1_414528)s::INTEGER, %(id_1_414529)s::INTEGER, %(id_1_414530)s::INTEGER, %(id_1_414531)s::INTEGER, %(id_1_414532)s::INTEGER, %(id_1_414533)s::INTEGER, %(id_1_414534)s::INTEGER, %(id_1_414535)s::INTEGER, %(id_1_414536)s::INTEGER, %(id_1_414537)s::INTEGER, %(id_1_414538)s::INTEGER, %(id_1_414539)s::INTEGER, %(id_1_414540)s::INTEGER, %(id_1_414541)s::INTEGER, %(id_1_414542)s::INTEGER, %(id_1_414543)s::INTEGER, %(id_1_414544)s::INTEGER, %(id_1_414545)s::INTEGER, %(id_1_414546)s::INTEGER, %(id_1_414547)s::INTEGER, %(id_1_414548)s::INTEGER, %(id_1_414549)s::INTEGER, %(id_1_414550)s::INTEGER, %(id_1_414551)s::INTEGER, %(id_1_414552)s::INTEGER, %(id_1_414553)s::INTEGER, %(id_1_414554)s::INTEGER, %(id_1_414555)s::INTEGER, %(id_1_414556)s::INTEGER, %(id_1_414557)s::INTEGER, %(id_1_414558)s::INTEGER, %(id_1_414559)s::INTEGER, %(id_1_414560)s::INTEGER, %(id_1_414561)s::INTEGER, %(id_1_414562)s::INTEGER, %(id_1_414563)s::INTEGER, %(id_1_414564)s::INTEGER) AND CAST(db_dbnode_1.node_type AS VARCHAR) LIKE %(param_2)s::VARCHAR AND db_dblink_1.type IN (%(type_1_1)s::VARCHAR, %(type_1_2)s::VARCHAR, %(type_1_3)s::VARCHAR, %(type_1_4)s::VARCHAR)]
[parameters: {'param_1': '%', 'param_2': '%', 'id_1_1': 1, 'id_1_2': 3, 'id_1_3': 6, 'id_1_4': 7, 'id_1_5': 9, 'id_1_6': 10, 'id_1_7': 12, 'id_1_8': 13, 'id_1_9': 18, 'id_1_10': 19, 'id_1_11': 22, 'id_1_12': 23, 'id_1_13': 26, 'id_1_14': 30, 'id_1_15': 31, 'id_1_16': 37, 'id_1_17': 38, 'id_1_18': 39, 'id_1_19': 41, 'id_1_20': 48, 'id_1_21': 50, 'id_1_22': 51, 'id_1_23': 52, 'id_1_24': 56, 'id_1_25': 60, 'id_1_26': 62, 'id_1_27': 67, 'id_1_28': 71, 'id_1_29': 85, 'id_1_30': 87, 'id_1_31': 88, 'id_1_32': 94, 'id_1_33': 102, 'id_1_34': 105, 'id_1_35': 107, 'id_1_36': 108, 'id_1_37': 112, 'id_1_38': 117, 'id_1_39': 122, 'id_1_40': 126, 'id_1_41': 127, 'id_1_42': 128, 'id_1_43': 142, 'id_1_44': 145, 'id_1_45': 149, 'id_1_46': 150, 'id_1_47': 151, 'id_1_48': 154 ... 414470 parameters truncated ... 'id_1_414519': 1014279, 'id_1_414520': 1014368, 'id_1_414521': 1014369, 'id_1_414522': 1014370, 'id_1_414523': 1014371, 'id_1_414524': 1014372, 'id_1_414525': 1014387, 'id_1_414526': 1014388, 'id_1_414527': 1014389, 'id_1_414528': 1014390, 'id_1_414529': 1014391, 'id_1_414530': 1014393, 'id_1_414531': 1014394, 'id_1_414532': 1014395, 'id_1_414533': 1014396, 'id_1_414534': 1014397, 'id_1_414535': 1014398, 'id_1_414536': 1014399, 'id_1_414537': 1014400, 'id_1_414538': 1014401, 'id_1_414539': 1014402, 'id_1_414540': 1014433, 'id_1_414541': 1014435, 'id_1_414542': 1014436, 'id_1_414543': 1014437, 'id_1_414544': 1014438, 'id_1_414545': 1014439, 'id_1_414546': 1014441, 'id_1_414547': 1014442, 'id_1_414548': 1014443, 'id_1_414549': 1014444, 'id_1_414550': 1014489, 'id_1_414551': 1014536, 'id_1_414552': 1014537, 'id_1_414553': 1014538, 'id_1_414554': 1014539, 'id_1_414555': 1014578, 'id_1_414556': 1014579, 'id_1_414557': 1014580, 'id_1_414558': 1014581, 'id_1_414559': 1014582, 'id_1_414560': 1014583, 'id_1_414561': 1014584, 'id_1_414562': 1014585, 'id_1_414563': 1014586, 'id_1_414564': 1014587, 'type_1_1': 'create', 'type_1_2': 'return', 'type_1_3': 'call_calc', 'type_1_4': 'call_work'}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by giovannipizzi** [comment]
Ok. We need to rewrite those queries, most probably. Would be good to find which query this is, exactly - probably the one in your original stack trace. One would need to do a join, rather than an explicit list of pks, but one needs to look into the specifics...

**Comment by mbercx** [comment]
I ran into this issue again. I'll work around it for now, but for larger databases this is quite a limiting problem.

**Comment by mbercx** [comment]
The limit of the number of e.g. `PwBaseWorkChain`s I can add to a single export seems surprisingly low. Even 5000 breaks the export. I'm _very_ sure I did bigger exports in the past.

**Comment by zhubonan** [comment]
I saw this as well. Interestingly I did not see it in the past when trying to export the same amount of data...

**Comment by zhubonan** [comment]
I am on version:     AiiDA v2.7.1

**Comment by zhubonan** [comment]
OK down grading to 2.6.4 seems to solve the issue, the changes to the dependences (2.7.1 to 2.6.4) are as follows:

```
 $ uv pip install aiida-core==2.6.
4
Using Python 3.10.12 environment at: /home/bonan/aiida_env/aiida-acwf/.venv
Resolved 76 packages in 508ms
Prepared 1 package in 707ms
Uninstalled 9 packages in 52ms
Installed 9 packages in 15ms
 - aiida-core==2.7.1
 + aiida-core==2.6.4
 - aio-pika==9.4.3
 + aio-pika==6.8.1
 - aiormq==6.8.1
 + aiormq==3.3.1
 - circus==0.19.0
 + circus==0.18.0
 - kiwipy==0.8.5
 + kiwipy==0.7.8
 - pamqp==3.3.0
 + pamqp==2.3.0
 - paramiko==3.5.1
 + paramiko==2.12.0
 - pgsu==0.3.0
 + pgsu==0.2.4
 - plumpy==0.25.0
 + plumpy==0.21.11

```

Perhaps it was related to `pgsu` being upgraded to 0.3.0? I don't see any other SQL related packages. The code in aiida-core is not changed in the `tools/archive/create.py` from 2.6.4 to 2.7.1.

**Comment by unkcpz** [comment]
`pgsu` has only devops change over the years https://github.com/aiidateam/pgsu/commits/master/

**Comment by zhubonan** [comment]
I meant the use of 'in' in `filters` here, this is where the big SQL query came from if one tries to export a lot of nodes (with their ancestors/descendants): 

https://github.com/aiidateam/aiida-core/blob/adf6fc04161ab13b8dcd003a6875cbe387ffe7f6/src/aiida/tools/archive/create.py#L539-L547

**Comment by GeigerJ2** [comment]
> Thanks [@GeigerJ2](https://github.com/GeigerJ2), will do some more testing later this week! Not that in case you generate 32768 `Int` nodes and add them to a group, you should also be able to break the `add_nodes` method for testing :)

~Hm, I didn't manage to reproduce it like this when I tried:~

EDIT: Was still on outdated depencies, so it was working. Now, I managed to reproduce it, and seems indeed that the change proposed in https://github.com/psycopg/psycopg/issues/620 fixes it. I added this in PR #6991. Let's see if CI passes, and behavior is as expected. Might be worth also adding some additional tests for it.

**Comment by mbercx** [comment]
I think we still have to merge https://github.com/aiidateam/aiida-core/issues/6993 before this is fully fixed?
