### ISSUE TITLE
`verdi storage migrate` fails for profiles without broker

### ISSUE THREAD

**Issue by danielhollas** [aiidateam/aiida-core#6546]
Here's what I see when I run `verdi storage migrate` on a profile created with verdi presto. (this is on latest main which should support sqlite migration)

```python
❯ verdi storage migrate
Traceback (most recent call last):
  File "/home/hollas/atmospec/aiida-core/.venv/bin/verdi", line 8, in <module>
    sys.exit(verdi())
             ^^^^^^^
  File "/home/hollas/atmospec/aiida-core/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiida-core/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiida-core/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiida-core/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiida-core/src/aiida/cmdline/groups/verdi.py", line 117, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiida-core/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiida-core/src/aiida/cmdline/commands/cmd_storage.py", line 44, in storage_migrate
    client = get_daemon_client()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiida-core/src/aiida/engine/daemon/client.py", line 80, in get_daemon_client
    return DaemonClient(profile)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hollas/atmospec/aiida-core/src/aiida/engine/daemon/client.py", line 103, in __init__
    raise ConfigurationError(
aiida.common.exceptions.ConfigurationError: profile `presto-3` does not define a broker so the daemon cannot be used. See https://aiida-core.readthedocs.io/en/stable/installation/guide_quick.html#quick-install-limitations for more details.
```

In the implementation, I believe we should first load the profile and skip the running-daemon check if it doesn't define broker.

https://github.com/aiidateam/aiida-core/blob/71422eb872040a9ba23047d2ec031f6deaa6a7cc/src/aiida/cmdline/commands/cmd_storage.py#L49

**Comment by danielhollas** [comment]
Look, I just like migrating okay? :sweat_smile: 

My goal was to profile it, we'd like to speed it up for AiiDAlab, since we call it at every container startup, and I suspect there's an opportunity for a fast path that skips the verdi daemon check, since in the starting container we know that the daemon is not running. I am planning to open a separate issue for that. (CC @superstar54)

**Comment by sphuber** [comment]
For your use case I imagine it would be even better if there would simply be an endpoint that would check whether the storage is up to date or needs migrating. I think we could either add this to `verdi storage version` and have it actually validate the storage and return a specific exit code if it needs to be migrated, or we could add `verdi storage status` or something like that. These commands wouldn't have to check whether the daemon is running so could be made faster.
